/// <reference no-default-lib="true" />

declare interface CATransform3D {}
declare interface CGAffineTransform {}
declare interface CGDataConsumerCallbacks {}
declare interface CGDataProviderDirectCallbacks {}
declare interface CGDataProviderSequentialCallbacks {}
declare interface CGDeviceColor {}
declare interface CGEventTapInformation {}
declare interface CGFunctionCallbacks {}
declare interface CGPSConverterCallbacks {}
declare interface CGPathElement {}
declare interface CGPatternCallbacks {}
declare interface CGPoint {}
declare interface CGRect {}
declare interface CGScreenUpdateMoveDelta {}
declare interface CGSize {}
declare interface CGVector {}
declare interface NSAffineTransformStruct {}
declare interface NSDecimal {}
declare interface NSEdgeInsets {}
declare interface NSFastEnumerationState {}
declare interface NSHashEnumerator {}
declare interface NSHashTableCallBacks {}
declare interface NSMapEnumerator {}
declare interface NSMapTableKeyCallBacks {}
declare interface NSMapTableValueCallBacks {}
declare interface NSOperatingSystemVersion {}
declare interface NSPoint {}
declare interface NSRange {}
declare interface NSRect {}
declare interface NSSize {}
declare interface NSSwappedDouble {}
declare interface NSSwappedFloat {}
