/// <reference no-default-lib="true" />

declare namespace cocoa {
  export interface MSTheme<T = any> extends cocoa.NSObject {
    cxx_destruct<R = void>(): R;
    changeApplicationAppearanceInBlock<R = void, P0 = cocoa.CDUnknownBlockType>(_changeApplicationAppearanceInBlock: P0): R;
    resolvedNamesForBaseName_options<R = unknown, P0 = unknown, P1 = number>(_resolvedNamesForBaseName: P0, _options: P1): R;
    cachedImageForKey_owner_createBlock<R = unknown, P0 = unknown, P1 = unknown, P2 = cocoa.CDUnknownBlockType>(_cachedImageForKey: P0, _owner: P1, _createBlock: P2): R;
    cachedImageForKey_owner<R = unknown, P0 = unknown, P1 = unknown>(_cachedImageForKey: P0, _owner: P1): R;
    cacheImage_forKey_owner<R = void, P0 = unknown, P1 = unknown, P2 = unknown>(_cacheImage: P0, _forKey: P1, _owner: P2): R;
    imageNamed_options<R = unknown, P0 = unknown, P1 = number>(_imageNamed: P0, _options: P1): R;
    imageNamed<R = unknown, P0 = unknown>(_imageNamed: P0): R;
    systemColorNamed<R = unknown, P0 = unknown>(_systemColorNamed: P0): R;
    _colorForStringValue_cachingKey<R = unknown, P0 = unknown, P1 = unknown>(__colorForStringValue: P0, _cachingKey: P1): R;
    colorForResolvedName<R = unknown, P0 = unknown>(_colorForResolvedName: P0): R;
    colorNamed_options<R = unknown, P0 = unknown, P1 = number>(_colorNamed: P0, _options: P1): R;
    colorNamed<R = unknown, P0 = unknown>(_colorNamed: P0): R;
    setDarkModeScheme<R = void, P0 = number>(_setDarkModeScheme: P0): R;
    darkModeScheme<R = number>(): R;
    layerListTextColorForBackgroundStyle_nodeIsHidden_editing_selected_active<R = unknown, P0 = number, P1 = boolean, P2 = boolean, P3 = boolean, P4 = boolean>(_layerListTextColorForBackgroundStyle: P0, _nodeIsHidden: P1, _editing: P2, _selected: P3, _active: P4): R;
    layerListSymbolOverrideSelectionColorForWindow_isActiveOutlineView<R = unknown, P0 = unknown, P1 = boolean>(_layerListSymbolOverrideSelectionColorForWindow: P0, _isActiveOutlineView: P1): R;
    layerListSelectionColorForWindow_isActiveOutlineView<R = unknown, P0 = unknown, P1 = boolean>(_layerListSelectionColorForWindow: P0, _isActiveOutlineView: P1): R;
    _colorNamed_forWindow_isActiveView<R = unknown, P0 = unknown, P1 = unknown, P2 = boolean>(__colorNamed: P0, _forWindow: P1, _isActiveView: P2): R;
    validateColorPlist<R = void>(): R;
    validate<R = void>(): R;
    attributedStringWithString_color_controlSize<R = unknown, P0 = unknown, P1 = unknown, P2 = number>(_attributedStringWithString: P0, _color: P1, _controlSize: P2): R;
    tintedImages<R = cocoa.MSTintedImages>(): R;
    setTintedImages<R = void, P0 = cocoa.MSTintedImages>(_v: P0): R;
    colorPlist<R = cocoa.NSDictionary>(): R;
    cache<R = cocoa.BCCache>(): R;
    isDark<R = boolean>(): R;
    layerListTabButtonColor<R = cocoa.NSColor>(): R;
    layerListSymbolOverrideIconTintColor<R = cocoa.NSColor>(): R;
    layerListSplitViewDividerColor<R = cocoa.NSColor>(): R;
    layerListIconSharedTintColor<R = cocoa.NSColor>(): R;
    layerListIconSelectedInactiveTintColor<R = cocoa.NSColor>(): R;
    layerListIconSelectedActiveTintColor<R = cocoa.NSColor>(): R;
    layerListIconPressedTintColorSelected<R = cocoa.NSColor>(): R;
    layerListIconPressedTintColor<R = cocoa.NSColor>(): R;
    layerListIconTintColor<R = cocoa.NSColor>(): R;
    layerListFilterTokenSelectedTitleColor<R = cocoa.NSColor>(): R;
    layerListFilterTokenTitleColor<R = cocoa.NSColor>(): R;
    layerListFilterTokenSelectedBackgroundColor<R = cocoa.NSColor>(): R;
    layerListFilterTokenBackgroundColor<R = cocoa.NSColor>(): R;
    layerListFilterBarBorderColor<R = cocoa.NSColor>(): R;
    layerListFilterBarBackgroundColor<R = cocoa.NSColor>(): R;
    layerListLightBackgroundColor<R = cocoa.NSColor>(): R;
    layerListBackgroundColor<R = cocoa.NSColor>(): R;
    layerListSelectedArtboardBorderColor<R = cocoa.NSColor>(): R;
    layerListArtboardBorderColor<R = cocoa.NSColor>(): R;
    windowBadgeUnfocusedPillColor<R = cocoa.NSColor>(): R;
    windowBadgeTextColor<R = cocoa.NSColor>(): R;
    windowBadgeMultipleNotificationsColor<R = cocoa.NSColor>(): R;
    windowBadgeTrialMessageColor<R = cocoa.NSColor>(): R;
    cloudPopoverCancelButtonTintColorPressed<R = cocoa.NSColor>(): R;
    cloudPopoverCancelButtonTintColor<R = cocoa.NSColor>(): R;
    cloudPopoverButtonTintColorPressed<R = cocoa.NSColor>(): R;
    cloudPopoverButtonTintColor<R = cocoa.NSColor>(): R;
    windowBadgePluginUpdatesAvailableColor<R = cocoa.NSColor>(): R;
    windowBadgeLibraryChangesAvailableColor<R = cocoa.NSColor>(): R;
    windowBadgeFontsMissingColor<R = cocoa.NSColor>(): R;
    preferencesWindowErrorTextColor<R = cocoa.NSColor>(): R;
    licenseWindowErrorTextColor<R = cocoa.NSColor>(): R;
    colorPickerSeparatorColor<R = cocoa.NSColor>(): R;
    colorPickerMarkerShadowColor<R = cocoa.NSColor>(): R;
    colorPickerMarkerFillColor<R = cocoa.NSColor>(): R;
    colorPickerLightShadowColor<R = cocoa.NSColor>(): R;
    colorPickerDarkShadowColor<R = cocoa.NSColor>(): R;
    colorPickerCheckerboardBorderColor<R = cocoa.NSColor>(): R;
    colorPickerCheckerboardBackgroundColor<R = cocoa.NSColor>(): R;
    colorPickerAssetBorderColor<R = cocoa.NSColor>(): R;
    canvasSymbolTitleColor<R = cocoa.NSColor>(): R;
    canvasSymbolErrorTextColor<R = cocoa.NSColor>(): R;
    canvasSymbolErrorBorderColor<R = cocoa.NSColor>(): R;
    canvasSymbolErrorBackgroundColor<R = cocoa.NSColor>(): R;
    canvasSliceOutlineColor<R = cocoa.NSColor>(): R;
    canvasRulerTextBackgroundColor<R = cocoa.NSColor>(): R;
    canvasRulerTextColor<R = cocoa.NSColor>(): R;
    canvasRulerOccupiedColor<R = cocoa.NSColor>(): R;
    canvasRulerLockColor<R = cocoa.NSColor>(): R;
    canvasRulerLineOccupiedColor<R = cocoa.NSColor>(): R;
    canvasRulerLineColor<R = cocoa.NSColor>(): R;
    canvasRulerBackgroundColor<R = cocoa.NSColor>(): R;
    canvasPixelLineColor<R = cocoa.NSColor>(): R;
    canvasPageBackgroundColor<R = cocoa.NSColor>(): R;
    canvasMeasurementLabelBackgroundColor<R = cocoa.NSColor>(): R;
    canvasLayerSelectionColor<R = cocoa.NSColor>(): R;
    canvasLayerHighlightColor<R = cocoa.NSColor>(): R;
    canvasFlowArrowColor<R = cocoa.NSColor>(): R;
    canvasBackgroundColor<R = cocoa.NSColor>(): R;
    canvasArtboardTitleColor<R = cocoa.NSColor>(): R;
    hoverButtonNormalColor<R = cocoa.NSColor>(): R;
    hoverButtonHoverColor<R = cocoa.NSColor>(): R;
    splitViewDividerColor<R = cocoa.NSColor>(): R;
    inspectorSecondaryLabelTextColorHighlighted<R = cocoa.NSColor>(): R;
    inspectorSecondaryLabelTextColor<R = cocoa.NSColor>(): R;
    inspectorArtboardPresetTableViewBackgroundColor<R = cocoa.NSColor>(): R;
    inspectorArtboardPresetHeaderColor<R = cocoa.NSColor>(): R;
    inspectorStylePreviewButtonOverlayHighlightingColor<R = cocoa.NSColor>(): R;
    inspectorSliderRightTrackColor<R = cocoa.NSColor>(): R;
    inspectorSliderKnobBorderColor<R = cocoa.NSColor>(): R;
    inspectorSliderKnobColor<R = cocoa.NSColor>(): R;
    inspectorSeparatorColor<R = cocoa.NSColor>(): R;
    inspectorSectionSeparatorColor<R = cocoa.NSColor>(): R;
    inspectorSectionHeaderTextColor<R = cocoa.NSColor>(): R;
    inspectorSectionBackgroundColor<R = cocoa.NSColor>(): R;
    inspectorResizePreviewInnerLayerBorderColor<R = cocoa.NSColor>(): R;
    inspectorResizePreviewInnerLayerBackgroundColor<R = cocoa.NSColor>(): R;
    inspectorResizePreviewEdgeIndicatorColor<R = cocoa.NSColor>(): R;
    inspectorResizePreviewBackgroundColor<R = cocoa.NSColor>(): R;
    inspectorPushButtonBackgroundColor<R = cocoa.NSColor>(): R;
    inspectorLabelTextColor<R = cocoa.NSColor>(): R;
    inspectorLabelBorderColor<R = cocoa.NSColor>(): R;
    inspectorLabelBackgroundColor<R = cocoa.NSColor>(): R;
    inspectorInlineLabelTextColor<R = cocoa.NSColor>(): R;
    inspectorIconAccentColor<R = cocoa.NSColor>(): R;
    inspectorIconColor<R = cocoa.NSColor>(): R;
    inspectorHighlightedSliderKnobColor<R = cocoa.NSColor>(): R;
    inspectorHighlightedIconColor<R = cocoa.NSColor>(): R;
    inspectorHighlightedBorderColor<R = cocoa.NSColor>(): R;
    inspectorHighlightedAccentColor<R = cocoa.NSColor>(): R;
    inspectorDisabledIconColor<R = cocoa.NSColor>(): R;
    inspectorButtonHighlightedBackgroundColor<R = cocoa.NSColor>(): R;
    inspectorButtonDropShadowColor<R = cocoa.NSColor>(): R;
    inspectorButtonBackgroundColor<R = cocoa.NSColor>(): R;
    inspectorBorderColor<R = cocoa.NSColor>(): R;
    inspectorBackgroundColor<R = cocoa.NSColor>(): R;
    inspectorAlignmentViewBackgroundColor<R = cocoa.NSColor>(): R;
    inspectorAlignmentStrutColor<R = cocoa.NSColor>(): R;
    inspectorAlignmentDisabledStrutColor<R = cocoa.NSColor>(): R;
    inspectorAccentColor<R = cocoa.NSColor>(): R;
  }
  namespace classes {
    export interface MSTheme<T = any> extends cocoa.classes.NSObject {
      alloc<R = MSTheme>(): R;
      new: <R = MSTheme>() => R;
      sharedTheme<R = unknown>(): R;
      initialize<R = void>(): R;
    }
  }
}

declare const MSTheme: cocoa.classes.MSTheme;
