/// <reference no-default-lib="true" />

declare namespace cocoa {
  export interface NSCarbonMenuImpl<T0 = void, T1 = void, T2 = void> extends NSObject, NSMenuImplProtocol {
    _boundsIfOpen<R = CGRect>(): R;
    _privateFlagsForMenuDirectionInView<R = number, P0 = unknown>(__privateFlagsForMenuDirectionInView: P0): R;
    _popUpMenuPositioningItem_atCocoaIndex_atLocation_inView_withPrivateFlags_appearance<R = boolean, P0 = unknown, P1 = number, P2 = CGPoint, P3 = unknown, P4 = number, P5 = unknown>(__popUpMenuPositioningItem: P0, _atCocoaIndex: P1, _atLocation: P2, _inView: P3, _withPrivateFlags: P4, _appearance: P5): R;
    _image_frame_forPopUpMenuPositioningItem_atCocoaIndex_atLocation_inView_appearance<R = void, P0 = unknown, P1 = CGRect, P2 = unknown, P3 = number, P4 = CGPoint, P5 = unknown, P6 = unknown>(__image: P0, _frame: P1, _forPopUpMenuPositioningItem: P2, _atCocoaIndex: P3, _atLocation: P4, _inView: P5, _appearance: P6): R;
    _removeCarbonEventHandlerForToken<R = void, P0 = unknown>(__removeCarbonEventHandlerForToken: P0): R;
    _handleCarbonEvents_count_handler<R = unknown, P0 = EventTypeSpec, P1 = number, P2 = CDUnknownBlockType>(__handleCarbonEvents: P0, _count: P1, _handler: P2): R;
    _setPopUpContext<R = void, P0 = SLMPopUpMenuContext_t>(__setPopUpContext: P0): R;
    _popUpContext<R = SLMPopUpMenuContext_t>(): R;
    _setCurrentMenuUpdateFlags<R = void, P0 = number>(__setCurrentMenuUpdateFlags: P0): R;
    _currentMenuUpdateFlags<R = number>(): R;
    _trackingInfo<R = unknown>(): R;
    highlightItemAtIndex<R = void, P0 = number>(_highlightItemAtIndex: P0): R;
    dealloc<R = void>(): R;
    _registeredForCloseEvents<R = boolean>(): R;
    _registeredForOpenEvents<R = boolean>(): R;
    _menuRefStatus<R = unknown>(): R;
    _menuRefIsCheckedOutWithToken<R = boolean, P0 = unknown>(__menuRefIsCheckedOutWithToken: P0): R;
    _returnMenuRefWithToken<R = void, P0 = unknown>(__returnMenuRefWithToken: P0): R;
    _checkoutMenuRefWithToken_creating_populating<R = OpaqueMenuRef, P0 = unknown, P1 = boolean, P2 = boolean>(__checkoutMenuRefWithToken: P0, _creating: P1, _populating: P2): R;
    _menuRefIsCheckedOut<R = boolean>(): R;
    _menuItem_wasAddedToNewIndex<R = void, P0 = unknown, P1 = number>(__menuItem: P0, _wasAddedToNewIndex: P1): R;
    _menuItem_wasRemovedFromPreviousIndex<R = void, P0 = unknown, P1 = number>(__menuItem: P0, _wasRemovedFromPreviousIndex: P1): R;
    _menuLostMainMenuStatus<R = void>(): R;
    _menuAcquiredMainMenuStatus<R = void>(): R;
    _isLinkedToShortcut<R = boolean>(): R;
    _unlinkShortcut<R = void>(): R;
    _linkShortcut<R = void>(): R;
    _backgroundStyle<R = number>(): R;
    _maximumSizeForScreen<R = CGSize, P0 = unknown>(__maximumSizeForScreen: P0): R;
    setIndentationWidth<R = void, P0 = number>(_setIndentationWidth: P0): R;
    _menuDidChangeIndentationWidthFrom_to<R = void, P0 = number, P1 = number>(__menuDidChangeIndentationWidthFrom: P0, _to: P1): R;
    setNCStyle<R = void, P0 = boolean>(_setNCStyle: P0): R;
    _menuDidChangeNCStyleFrom_to<R = void, P0 = boolean, P1 = boolean>(__menuDidChangeNCStyleFrom: P0, _to: P1): R;
    _menuDidChangeFontFrom_to<R = void, P0 = unknown, P1 = unknown>(__menuDidChangeFontFrom: P0, _to: P1): R;
    _limitedViewMenuItemWantsRedisplay_inRect<R = void, P0 = number, P1 = CGRect>(__limitedViewMenuItemWantsRedisplay: P0, _inRect: P1): R;
    _menuDidChangeWidthFrom_to<R = void, P0 = number, P1 = number>(__menuDidChangeWidthFrom: P0, _to: P1): R;
    _itemLostMagicAppleMenuStatus<R = void, P0 = unknown>(__itemLostMagicAppleMenuStatus: P0): R;
    _itemAcquiredMagicAppleMenuStatus<R = void, P0 = unknown>(__itemAcquiredMagicAppleMenuStatus: P0): R;
    _initialMenuRefCreateIfNecessary<R = OpaqueMenuRef>(): R;
    _initialMenuRef<R = OpaqueMenuRef>(): R;
    _principalMenuRefCreateIfNecessary<R = OpaqueMenuRef>(): R;
    _menuItem_atIndex_didChangeRequiresModifiersToBeVisibleFrom_to<R = void, P0 = unknown, P1 = number, P2 = boolean, P3 = boolean>(__menuItem: P0, _atIndex: P1, _didChangeRequiresModifiersToBeVisibleFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeImageSizeFrom_to<R = void, P0 = unknown, P1 = number, P2 = CGSize, P3 = CGSize>(__menuItem: P0, _atIndex: P1, _didChangeImageSizeFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeRespectsKeyEquivalentWhileHiddenFrom_to<R = void, P0 = unknown, P1 = number, P2 = boolean, P3 = boolean>(__menuItem: P0, _atIndex: P1, _didChangeRespectsKeyEquivalentWhileHiddenFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeSeparatorStatusFrom_to<R = void, P0 = unknown, P1 = number, P2 = boolean, P3 = boolean>(__menuItem: P0, _atIndex: P1, _didChangeSeparatorStatusFrom: P2, _to: P3): R;
    _menuDidChangeUserInterfaceLayoutDirectionFrom_to<R = void, P0 = number, P1 = number>(__menuDidChangeUserInterfaceLayoutDirectionFrom: P0, _to: P1): R;
    _menuDidChangeCondensesSeparatorsFrom_to<R = void, P0 = boolean, P1 = boolean>(__menuDidChangeCondensesSeparatorsFrom: P0, _to: P1): R;
    _menuDidChangeAutoenablesFrom_to<R = void, P0 = boolean, P1 = boolean>(__menuDidChangeAutoenablesFrom: P0, _to: P1): R;
    _menuDidChangeShowsStateColumnFrom_to<R = void, P0 = boolean, P1 = boolean>(__menuDidChangeShowsStateColumnFrom: P0, _to: P1): R;
    _menuDidChangeHasBottomPaddingFrom_to<R = void, P0 = boolean, P1 = boolean>(__menuDidChangeHasBottomPaddingFrom: P0, _to: P1): R;
    _menuDidChangeHasTopPaddingFrom_to<R = void, P0 = boolean, P1 = boolean>(__menuDidChangeHasTopPaddingFrom: P0, _to: P1): R;
    _menuDidChangeHasSidebandUpdaterWithRoles_from_to<R = void, P0 = number, P1 = boolean, P2 = boolean>(__menuDidChangeHasSidebandUpdaterWithRoles: P0, _from: P1, _to: P2): R;
    _menuDidChangeDelegateTo<R = void, P0 = unknown>(__menuDidChangeDelegateTo: P0): R;
    _menuItem_atIndex_didChangeAccessibilityOverriddenAttributesFrom_to<R = void, P0 = unknown, P1 = number, P2 = unknown, P3 = unknown>(__menuItem: P0, _atIndex: P1, _didChangeAccessibilityOverriddenAttributesFrom: P2, _to: P3): R;
    _menuDidChangePluginInsertionModeFrom_to<R = void, P0 = number, P1 = number>(__menuDidChangePluginInsertionModeFrom: P0, _to: P1): R;
    _menuDidChangeAccessibilityOverriddenAttribute_from_to<R = void, P0 = unknown, P1 = unknown, P2 = unknown>(__menuDidChangeAccessibilityOverriddenAttribute: P0, _from: P1, _to: P2): R;
    _menuItem_atIndex_didChangeAccessibilityOverriddenAttribute_from_to<R = void, P0 = unknown, P1 = number, P2 = unknown, P3 = unknown, P4 = unknown>(__menuItem: P0, _atIndex: P1, _didChangeAccessibilityOverriddenAttribute: P2, _from: P3, _to: P4): R;
    _menuItem_atIndex_didChangeHiddenFrom_to<R = void, P0 = unknown, P1 = number, P2 = boolean, P3 = boolean>(__menuItem: P0, _atIndex: P1, _didChangeHiddenFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeCustomViewHandlesEventsFrom_to<R = void, P0 = unknown, P1 = number, P2 = boolean, P3 = boolean>(__menuItem: P0, _atIndex: P1, _didChangeCustomViewHandlesEventsFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeCustomViewFrom_to<R = void, P0 = unknown, P1 = number, P2 = unknown, P3 = unknown>(__menuItem: P0, _atIndex: P1, _didChangeCustomViewFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeTooltipFrom_to<R = void, P0 = unknown, P1 = number, P2 = unknown, P3 = unknown>(__menuItem: P0, _atIndex: P1, _didChangeTooltipFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeIndentFrom_to<R = void, P0 = unknown, P1 = number, P2 = number, P3 = number>(__menuItem: P0, _atIndex: P1, _didChangeIndentFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeKeyEquivalentModifierMaskFrom_to<R = void, P0 = unknown, P1 = number, P2 = number, P3 = number>(__menuItem: P0, _atIndex: P1, _didChangeKeyEquivalentModifierMaskFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeKeyEquivalentVirtualKeyCodeFrom_to<R = void, P0 = unknown, P1 = number, P2 = number, P3 = number>(__menuItem: P0, _atIndex: P1, _didChangeKeyEquivalentVirtualKeyCodeFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeKeyEquivalentFrom_to<R = void, P0 = unknown, P1 = number, P2 = unknown, P3 = unknown>(__menuItem: P0, _atIndex: P1, _didChangeKeyEquivalentFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeImageFrom_to<R = void, P0 = unknown, P1 = number, P2 = unknown, P3 = unknown>(__menuItem: P0, _atIndex: P1, _didChangeImageFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeStateImageFrom_to<R = void, P0 = unknown, P1 = number, P2 = unknown, P3 = unknown>(__menuItem: P0, _atIndex: P1, _didChangeStateImageFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeActionFrom_to<R = void, P0 = unknown, P1 = number, P2 = string, P3 = string>(__menuItem: P0, _atIndex: P1, _didChangeActionFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeNewItemsCountFrom_to<R = void, P0 = unknown, P1 = number, P2 = number, P3 = number>(__menuItem: P0, _atIndex: P1, _didChangeNewItemsCountFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeFontFrom_to<R = void, P0 = unknown, P1 = number, P2 = unknown, P3 = unknown>(__menuItem: P0, _atIndex: P1, _didChangeFontFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeAttributedTitleFrom_to<R = void, P0 = unknown, P1 = number, P2 = unknown, P3 = unknown>(__menuItem: P0, _atIndex: P1, _didChangeAttributedTitleFrom: P2, _to: P3): R;
    _menuDidChangeTitleFrom_to<R = void, P0 = unknown, P1 = unknown>(__menuDidChangeTitleFrom: P0, _to: P1): R;
    _menuItem_atIndex_didChangeTitleFrom_to<R = void, P0 = unknown, P1 = number, P2 = unknown, P3 = unknown>(__menuItem: P0, _atIndex: P1, _didChangeTitleFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeSubmenuFrom_to<R = void, P0 = unknown, P1 = number, P2 = unknown, P3 = unknown>(__menuItem: P0, _atIndex: P1, _didChangeSubmenuFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeSubmenuContentsWithSubmenu<R = void, P0 = unknown, P1 = number, P2 = unknown>(__menuItem: P0, _atIndex: P1, _didChangeSubmenuContentsWithSubmenu: P2): R;
    _menuItem_atIndex_didChangeNextItemIsAlternateFrom_to<R = void, P0 = unknown, P1 = number, P2 = boolean, P3 = boolean>(__menuItem: P0, _atIndex: P1, _didChangeNextItemIsAlternateFrom: P2, _to: P3): R;
    _menuItem_atIndex_didChangeEnabledStateFrom_to<R = void, P0 = unknown, P1 = number, P2 = boolean, P3 = boolean>(__menuItem: P0, _atIndex: P1, _didChangeEnabledStateFrom: P2, _to: P3): R;
    _updateEventHandlerClientCounts<R = void>(): R;
    _changeCustomViewClientCountBy<R = void, P0 = number>(__changeCustomViewClientCountBy: P0): R;
    _changeCustomTextDrawingCountBy_contentCountBy<R = void, P0 = number, P1 = number>(__changeCustomTextDrawingCountBy: P0, _contentCountBy: P1): R;
    _changeFlags_forItemAtCocoaIndex_isAddingFlags<R = void, P0 = number, P1 = number, P2 = boolean>(__changeFlags: P0, _forItemAtCocoaIndex: P1, _isAddingFlags: P2): R;
    _menuItemCommandID<R = number>(): R;
    _carbonMenuInsertItem_atCarbonIndex<R = void, P0 = unknown, P1 = number>(__carbonMenuInsertItem: P0, _atCarbonIndex: P1): R;
    _populatePrivatelyIfNecessary<R = boolean>(): R;
    _privatePopulateCarbonMenu<R = void>(): R;
    _instantiateCarbonMenu<R = void>(): R;
    _carbonMenuHasBeenInstantiatedAndPopulated<R = boolean>(): R;
    _setSupermenuHasMenuRef<R = void, P0 = boolean>(__setSupermenuHasMenuRef: P0): R;
    _destroyMenuRefIfNotCheckedOut<R = void>(): R;
    _destroyMenuRef<R = void>(): R;
    _createMenuRef<R = OpaqueMenuRef>(): R;
    _applyAccessibilityOverrides_toCarbonIndex<R = void, P0 = unknown, P1 = number>(__applyAccessibilityOverrides: P0, _toCarbonIndex: P1): R;
    _installCarbonMenuEventHandlers<R = void>(): R;
    _beginOrEndHandling_events_count<R = void, P0 = boolean, P1 = EventTypeSpec, P2 = number>(__beginOrEndHandling: P0, _events: P1, _count: P2): R;
    _endHandlingEvents_count<R = void, P0 = EventTypeSpec, P1 = number>(__endHandlingEvents: P0, _count: P1): R;
    _beginHandlingEvents_count<R = void, P0 = EventTypeSpec, P1 = number>(__beginHandlingEvents: P0, _count: P1): R;
    _menuRefAttributes<R = number>(): R;
    _carbonDrawItemTextEvent_handlerCallRef<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef>(__carbonDrawItemTextEvent: P0, _handlerCallRef: P1): R;
    _carbonDrawItemContentEvent_handlerCallRef<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef>(__carbonDrawItemContentEvent: P0, _handlerCallRef: P1): R;
    _carbonDrawAttributedTitleForMenuItem_withEvent<R = void, P0 = unknown, P1 = OpaqueEventRef>(__carbonDrawAttributedTitleForMenuItem: P0, _withEvent: P1): R;
    _carbonDrawStateImageForMenuItem_withEvent<R = void, P0 = unknown, P1 = OpaqueEventRef>(__carbonDrawStateImageForMenuItem: P0, _withEvent: P1): R;
    _carbonDrawLimitedViewForMenuItem_withEvent<R = void, P0 = unknown, P1 = OpaqueEventRef>(__carbonDrawLimitedViewForMenuItem: P0, _withEvent: P1): R;
    _carbonMeasureItemContentEvent_handlerCallRef_measuringHeight<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef, P2 = boolean>(__carbonMeasureItemContentEvent: P0, _handlerCallRef: P1, _measuringHeight: P2): R;
    _carbonMeasureItemTextEvent_handlerCallRef_measuringHeight<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef, P2 = boolean>(__carbonMeasureItemTextEvent: P0, _handlerCallRef: P1, _measuringHeight: P2): R;
    nsElementFromAXUIElement<R = unknown, P0 = __AXUIElement>(_nsElementFromAXUIElement: P0): R;
    _carbonIsAccessibleAttributeSettableEvent_handlerCallRef_axElement<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef, P2 = __AXUIElement>(__carbonIsAccessibleAttributeSettableEvent: P0, _handlerCallRef: P1, _axElement: P2): R;
    _carbonGetAccessibleAttributeEvent_handlerCallRef_axElement<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef, P2 = __AXUIElement>(__carbonGetAccessibleAttributeEvent: P0, _handlerCallRef: P1, _axElement: P2): R;
    _carbonGetAccessibleAttributeNamesEvent_handlerCallRef_axElement<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef, P2 = __AXUIElement>(__carbonGetAccessibleAttributeNamesEvent: P0, _handlerCallRef: P1, _axElement: P2): R;
    _carbonCommandProcessEvent_handlerCallRef<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef>(__carbonCommandProcessEvent: P0, _handlerCallRef: P1): R;
    _carbonMenuItemSelectedEvent_handlerCallRef<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef>(__carbonMenuItemSelectedEvent: P0, _handlerCallRef: P1): R;
    _carbonUpdateStatusEvent_handlerCallRef<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef>(__carbonUpdateStatusEvent: P0, _handlerCallRef: P1): R;
    _carbonTargetItemEvent_handlerCallRef<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef>(__carbonTargetItemEvent: P0, _handlerCallRef: P1): R;
    _informOwnerViewOfMenuState_withEvent<R = void, P0 = boolean, P1 = OpaqueEventRef>(__informOwnerViewOfMenuState: P0, _withEvent: P1): R;
    _carbonCloseEvent_handlerCallRef<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef>(__carbonCloseEvent: P0, _handlerCallRef: P1): R;
    _carbonOpenEvent_handlerCallRef<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef>(__carbonOpenEvent: P0, _handlerCallRef: P1): R;
    _carbonMatchKeyEvent_handlerCallRef<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef>(__carbonMatchKeyEvent: P0, _handlerCallRef: P1): R;
    _carbonPopulateEvent_handlerCallRef<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef>(__carbonPopulateEvent: P0, _handlerCallRef: P1): R;
    _menuItemFromCarbonEventViaParamMenuItemIndexRequiringNonNull<R = unknown, P0 = OpaqueEventRef>(__menuItemFromCarbonEventViaParamMenuItemIndexRequiringNonNull: P0): R;
    _menuItemFromCarbonEventViaParamMenuItemIndex<R = unknown, P0 = OpaqueEventRef>(__menuItemFromCarbonEventViaParamMenuItemIndex: P0): R;
    _isMainMenu<R = boolean>(): R;
    _carbonUpdateMenuItemKeyEquivalentForItem_atCarbonIndex_withVirtualKeyCode_keyEquivalent<R = void, P0 = unknown, P1 = number, P2 = number, P3 = unknown>(__carbonUpdateMenuItemKeyEquivalentForItem: P0, _atCarbonIndex: P1, _withVirtualKeyCode: P2, _keyEquivalent: P3): R;
    _carbonApplyImage_forItem_forCarbonIndex_withApplicationMask<R = void, P0 = unknown, P1 = unknown, P2 = number, P3 = number>(__carbonApplyImage: P0, _forItem: P1, _forCarbonIndex: P2, _withApplicationMask: P3): R;
    _carbonSetToolTip_forCarbonIndex<R = void, P0 = unknown, P1 = number>(__carbonSetToolTip: P0, _forCarbonIndex: P1): R;
    _dismissMenuBecauseWindowBecameMain<R = void, P0 = unknown>(__dismissMenuBecauseWindowBecameMain: P0): R;
    _popUpContextMenu_withEvent_forView<R = void, P0 = unknown, P1 = unknown, P2 = unknown>(__popUpContextMenu: P0, _withEvent: P1, _forView: P2): R;
    _popUpContextMenu_withEvent_forView_withFont<R = void, P0 = unknown, P1 = unknown, P2 = unknown, P3 = unknown>(__popUpContextMenu: P0, _withEvent: P1, _forView: P2, _withFont: P3): R;
    popUpMenu_atLocation_width_forView_withSelectedItem_withFont_withFlags_withOptions<R = void, P0 = unknown, P1 = CGPoint, P2 = number, P3 = unknown, P4 = number, P5 = unknown, P6 = number, P7 = unknown>(_popUpMenu: P0, _atLocation: P1, _width: P2, _forView: P3, _withSelectedItem: P4, _withFont: P5, _withFlags: P6, _withOptions: P7): R;
    popUpMenu_atLocation_width_forView_withSelectedItem_withFont<R = void, P0 = unknown, P1 = CGPoint, P2 = number, P3 = unknown, P4 = number, P5 = unknown>(_popUpMenu: P0, _atLocation: P1, _width: P2, _forView: P3, _withSelectedItem: P4, _withFont: P5): R;
    clearAsMainCarbonMenuBar<R = void>(): R;
    setAsMainCarbonMenuBar<R = void>(): R;
    setupCarbonMenuBar<R = void>(): R;
    performMenuAction_withTarget<R = void, P0 = string, P1 = unknown>(_performMenuAction: P0, _withTarget: P1): R;
    performActionWithHighlightingForItemAtIndex<R = void, P0 = number>(_performActionWithHighlightingForItemAtIndex: P0): R;
    _itemRemoved<R = void, P0 = number>(__itemRemoved: P0): R;
    _itemAdded<R = void, P0 = number>(__itemAdded: P0): R;
    _itemChanged<R = void, P0 = number>(__itemChanged: P0): R;
    menu<R = unknown>(): R;
    setMenu<R = void, P0 = unknown>(_setMenu: P0): R;
    setPopUpContext<R = void, P0 = SLMPopUpMenuContext_t>(_setPopUpContext: P0): R;
    popUpContext<R = SLMPopUpMenuContext_t>(): R;
    setMenuAppearance<R = void, P0 = unknown>(_setMenuAppearance: P0): R;
    menuAppearance<R = unknown>(): R;
    setCustomHandlerList<R = void, P0 = unknown>(_setCustomHandlerList: P0): R;
    customHandlerList<R = unknown>(): R;
    _createExtraVars<R = void>(): R;
    debugDescription<R = NSString>(): R;
    description<R = NSString>(): R;
    hash<R = number>(): R;
    superclass<R = unknown>(): R;
  }
  namespace NSCarbonMenuImpl {
    export interface CLASS<T0 = void, T1 = void, T2 = void> extends NSObject, NSMenuImplProtocol {
      alloc<R = NSCarbonMenuImpl>(): R;
      new: <R = NSCarbonMenuImpl>() => R;
      _menuItemWithKeyEquivalentMatchingEventRef_inMenu_includingDisabledItems<R = _NSCarbonMenuSearchReturn, P0 = OpaqueEventRef, P1 = unknown, P2 = boolean>(__menuItemWithKeyEquivalentMatchingEventRef: P0, _inMenu: P1, _includingDisabledItems: P2): R;
      _currentTrackingInfo<R = unknown>(): R;
      _didChangeHelpMenuFrom_to<R = void, P0 = unknown, P1 = unknown>(__didChangeHelpMenuFrom: P0, _to: P1): R;
      _globalCarbonCommandProcessEvent_handlerCallRef<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef>(__globalCarbonCommandProcessEvent: P0, _handlerCallRef: P1): R;
      _globalCarbonBeginOrEndTrackingEvent_handlerCallRef<R = number, P0 = OpaqueEventRef, P1 = OpaqueEventHandlerCallRef>(__globalCarbonBeginOrEndTrackingEvent: P0, _handlerCallRef: P1): R;
      isItemBeingDrawn_highlightState<R = boolean, P0 = unknown, P1 = string>(_isItemBeingDrawn: P0, _highlightState: P1): R;
      initialize<R = void>(): R;
      setupForNoMenuBar<R = void>(): R;
      prepareForCarbonMenuBar<R = void>(): R;
    }
  }
}

declare const NSCarbonMenuImpl: cocoa.NSCarbonMenuImpl.CLASS;
