/// <reference no-default-lib="true" />

declare namespace cocoa {
  export interface NSCollectionView<T0 = void, T1 = void, T2 = void> extends NSView, NSDraggingSourceProtocol, NSDraggingDestinationProtocol {
    _reuseSupplementaryView<R = void, P0 = unknown>(__reuseSupplementaryView: P0): R;
    collectionView_transitionLayoutForOldLayout_newLayout<R = unknown, P0 = unknown, P1 = unknown, P2 = unknown>(_collectionView: P0, _transitionLayoutForOldLayout: P1, _newLayout: P2): R;
    collectionView_didEndDisplayingSupplementaryView_forElementOfKind_atIndexPath<R = void, P0 = unknown, P1 = unknown, P2 = unknown, P3 = unknown>(_collectionView: P0, _didEndDisplayingSupplementaryView: P1, _forElementOfKind: P2, _atIndexPath: P3): R;
    collectionView_willDisplaySupplementaryView_forElementKind_atIndexPath<R = void, P0 = unknown, P1 = unknown, P2 = unknown, P3 = unknown>(_collectionView: P0, _willDisplaySupplementaryView: P1, _forElementKind: P2, _atIndexPath: P3): R;
    collectionView_didEndDisplayingItem_forRepresentedObjectAtIndexPath<R = void, P0 = unknown, P1 = unknown, P2 = unknown>(_collectionView: P0, _didEndDisplayingItem: P1, _forRepresentedObjectAtIndexPath: P2): R;
    collectionView_willDisplayItem_forRepresentedObjectAtIndexPath<R = void, P0 = unknown, P1 = unknown, P2 = unknown>(_collectionView: P0, _willDisplayItem: P1, _forRepresentedObjectAtIndexPath: P2): R;
    collectionView_didDeselectItemsAtIndexPaths<R = void, P0 = unknown, P1 = unknown>(_collectionView: P0, _didDeselectItemsAtIndexPaths: P1): R;
    collectionView_didSelectItemsAtIndexPaths<R = void, P0 = unknown, P1 = unknown>(_collectionView: P0, _didSelectItemsAtIndexPaths: P1): R;
    collectionView_shouldDeselectItemsAtIndexPaths<R = unknown, P0 = unknown, P1 = unknown>(_collectionView: P0, _shouldDeselectItemsAtIndexPaths: P1): R;
    collectionView_shouldSelectItemsAtIndexPaths<R = unknown, P0 = unknown, P1 = unknown>(_collectionView: P0, _shouldSelectItemsAtIndexPaths: P1): R;
    collectionView_didUnhighlightItemAtIndexPath<R = void, P0 = unknown, P1 = unknown>(_collectionView: P0, _didUnhighlightItemAtIndexPath: P1): R;
    collectionView_didHighlightItemAtIndexPath<R = void, P0 = unknown, P1 = unknown>(_collectionView: P0, _didHighlightItemAtIndexPath: P1): R;
    collectionView_shouldHighlightItemAtIndexPath<R = boolean, P0 = unknown, P1 = unknown>(_collectionView: P0, _shouldHighlightItemAtIndexPath: P1): R;
    _scrollSelectionToVisible<R = void>(): R;
    _scrollToVisibleItemAtIndex<R = void, P0 = number>(__scrollToVisibleItemAtIndex: P0): R;
    scrollToItemAtIndexPath_scrollPosition<R = void, P0 = unknown, P1 = number>(_scrollToItemAtIndexPath: P0, _scrollPosition: P1): R;
    scrollToItemsAtIndexPaths_scrollPosition<R = void, P0 = unknown, P1 = number>(_scrollToItemsAtIndexPaths: P0, _scrollPosition: P1): R;
    moveWordLeftAndModifySelection<R = void, P0 = unknown>(_moveWordLeftAndModifySelection: P0): R;
    moveWordRightAndModifySelection<R = void, P0 = unknown>(_moveWordRightAndModifySelection: P0): R;
    moveToEndOfParagraph<R = void, P0 = unknown>(_moveToEndOfParagraph: P0): R;
    moveToBeginningOfParagraph<R = void, P0 = unknown>(_moveToBeginningOfParagraph: P0): R;
    moveWordLeft<R = void, P0 = unknown>(_moveWordLeft: P0): R;
    moveWordRight<R = void, P0 = unknown>(_moveWordRight: P0): R;
    moveDownAndModifySelection<R = void, P0 = unknown>(_moveDownAndModifySelection: P0): R;
    moveUpAndModifySelection<R = void, P0 = unknown>(_moveUpAndModifySelection: P0): R;
    moveLeftAndModifySelection<R = void, P0 = unknown>(_moveLeftAndModifySelection: P0): R;
    moveRightAndModifySelection<R = void, P0 = unknown>(_moveRightAndModifySelection: P0): R;
    moveDown<R = void, P0 = unknown>(_moveDown: P0): R;
    moveUp<R = void, P0 = unknown>(_moveUp: P0): R;
    moveLeft<R = void, P0 = unknown>(_moveLeft: P0): R;
    moveRight<R = void, P0 = unknown>(_moveRight: P0): R;
    _keyboardSelectItemAtIndexPath_extendingSelection_startingIndexPath<R = void, P0 = unknown, P1 = boolean, P2 = unknown>(__keyboardSelectItemAtIndexPath: P0, _extendingSelection: P1, _startingIndexPath: P2): R;
    _itemIndexPathToRightOf<R = unknown, P0 = unknown>(__itemIndexPathToRightOf: P0): R;
    _itemIndexPathToLeftOf<R = unknown, P0 = unknown>(__itemIndexPathToLeftOf: P0): R;
    _itemIndexPathBelow<R = unknown, P0 = unknown>(__itemIndexPathBelow: P0): R;
    _itemIndexPathAbove<R = unknown, P0 = unknown>(__itemIndexPathAbove: P0): R;
    _startingIndexPathForMove<R = unknown, P0 = string>(__startingIndexPathForMove: P0): R;
    _lastSelectionIndexPath<R = unknown>(): R;
    _firstSelectionIndexPath<R = unknown>(): R;
    _setMostRecentSelectionIndexPath<R = void, P0 = unknown>(__setMostRecentSelectionIndexPath: P0): R;
    _mostRecentSelectionIndexPath<R = unknown>(): R;
    _indexForMoveDown<R = number>(): R;
    _indexForMoveUp<R = number>(): R;
    _indexForMoveLeft<R = number>(): R;
    _indexForMoveRight<R = number>(): R;
    _indexForIncrementMove<R = number, P0 = number>(__indexForIncrementMove: P0): R;
    _indexForDecrementMove<R = number, P0 = number>(__indexForDecrementMove: P0): R;
    deselectAll<R = void, P0 = unknown>(_deselectAll: P0): R;
    selectAll<R = void, P0 = unknown>(_selectAll: P0): R;
    _sectionAtIndexIsCollapsedToFirstItem<R = boolean, P0 = number>(__sectionAtIndexIsCollapsedToFirstItem: P0): R;
    _toggleSectionCollapse<R = void, P0 = unknown>(__toggleSectionCollapse: P0): R;
    toggleSectionCollapse<R = void, P0 = unknown>(_toggleSectionCollapse: P0): R;
    _selectFromIndex_toIndex_scrollIndexToVisible<R = void, P0 = number, P1 = number, P2 = number>(__selectFromIndex: P0, _toIndex: P1, _scrollIndexToVisible: P2): R;
    _selectIndex_scrollToVisible<R = void, P0 = number, P1 = boolean>(__selectIndex: P0, _scrollToVisible: P1): R;
    _selectObjectsAtIndexes_avoidsEmptySelection<R = void, P0 = unknown, P1 = boolean>(__selectObjectsAtIndexes: P0, _avoidsEmptySelection: P1): R;
    _selectionStateChanged<R = void, P0 = unknown>(__selectionStateChanged: P0): R;
    _applySelectionIndexes_toItems<R = void, P0 = unknown, P1 = unknown>(__applySelectionIndexes: P0, _toItems: P1): R;
    _setBackgroundNeedsDisplayInRect<R = void, P0 = CGRect>(__setBackgroundNeedsDisplayInRect: P0): R;
    setLayer<R = void, P0 = unknown>(_setLayer: P0): R;
    _setBackgroundNeedsDisplay<R = void>(): R;
    _needsLayerBackgrounds<R = boolean>(): R;
    _updateBackgroundLayers<R = void>(): R;
    _updateBackgroundView<R = void>(): R;
    _removeBackgroundLayers<R = void>(): R;
    _createGridBackgroundInRect_withSelector<R = number, P0 = CGRect, P1 = string>(__createGridBackgroundInRect: P0, _withSelector: P1): R;
    _createBackgroundLayerWithProperties<R = void, P0 = unknown>(__createBackgroundLayerWithProperties: P0): R;
    _drawBackgroundGridWithProperties<R = void, P0 = unknown>(__drawBackgroundGridWithProperties: P0): R;
    _needsCollectionViewDesktopTintedBackgroundWithMaterial<R = boolean, P0 = number>(__needsCollectionViewDesktopTintedBackgroundWithMaterial: P0): R;
    _hasDesktopTintedBackgroundColorWithMaterial<R = boolean, P0 = number>(__hasDesktopTintedBackgroundColorWithMaterial: P0): R;
    _contiguousRangeOfItemsForRect<R = _NSRange, P0 = CGRect>(__contiguousRangeOfItemsForRect: P0): R;
    _scheduleEndOfAnimationTimer<R = void, P0 = number>(__scheduleEndOfAnimationTimer: P0): R;
    _displayItems_withConfiguration_animate<R = void, P0 = unknown, P1 = unknown, P2 = boolean>(__displayItems: P0, _withConfiguration: P1, _animate: P2): R;
    _stopObservingViewDidScroll<R = void>(): R;
    _startObservingViewDidScroll<R = void>(): R;
    _stopObservingClipViewFrameChanged<R = void>(): R;
    _startObservingClipViewFrameChanged<R = void>(): R;
    _scrollViewDidChangeBounds<R = void, P0 = unknown>(__scrollViewDidChangeBounds: P0): R;
    _ensureVisibleItemsLoaded<R = void>(): R;
    _addItemViewAsSubview<R = void, P0 = unknown>(__addItemViewAsSubview: P0): R;
    awakeFromNib<R = void>(): R;
    _animationFromStartRect_crossesVisibleRectToEndRect<R = boolean, P0 = CGRect, P1 = CGRect>(__animationFromStartRect: P0, _crossesVisibleRectToEndRect: P1): R;
    _indexOfSectionAtPoint_usingPartialFramesBySectionIndex<R = number, P0 = CGPoint, P1 = unknown>(__indexOfSectionAtPoint: P0, _usingPartialFramesBySectionIndex: P1): R;
    _indexOfSectionAtPoint<R = number, P0 = CGPoint>(__indexOfSectionAtPoint: P0): R;
    _partialFramesOfVisibleSectionsBySectionIndex<R = unknown>(): R;
    _itemIsVisibleAtIndex<R = boolean, P0 = number>(__itemIsVisibleAtIndex: P0): R;
    _frameForItemAtIndex_withConfiguration_ignoreDropSpace<R = CGRect, P0 = number, P1 = unknown, P2 = boolean>(__frameForItemAtIndex: P0, _withConfiguration: P1, _ignoreDropSpace: P2): R;
    _getItemsToDisplay<R = unknown>(): R;
    _registerNeedsUpdateGrid<R = void>(): R;
    _updateGridWithCurrentItemsIfNecessary<R = void>(): R;
    _updateGridWithCurrentItems<R = void>(): R;
    _setGridSettingsNeedUpdate<R = void, P0 = boolean>(__setGridSettingsNeedUpdate: P0): R;
    _gridSettingsNeedUpdate<R = boolean>(): R;
    _configurationIsColumnMajorOrder<R = boolean, P0 = unknown>(__configurationIsColumnMajorOrder: P0): R;
    _itemIndexAtPoint<R = number, P0 = CGPoint>(__itemIndexAtPoint: P0): R;
    _updateGridSettingsWithPrototype<R = void>(): R;
    _filledViewShouldExtendVertically<R = boolean>(): R;
    _computeGridConfigurationWithSize<R = unknown, P0 = CGSize>(__computeGridConfigurationWithSize: P0): R;
    _computeGridConfigurationWithSize_count<R = unknown, P0 = CGSize, P1 = number>(__computeGridConfigurationWithSize: P0, _count: P1): R;
    _computeGridConfiguration<R = unknown>(): R;
    _computeGridConfigurationWithCount<R = unknown, P0 = number>(__computeGridConfigurationWithCount: P0): R;
    _currentGridConfiguration<R = unknown>(): R;
    _hoverAreaIsSameAsLast<R = boolean, P0 = unknown>(__hoverAreaIsSameAsLast: P0): R;
    _updateDragAndDropStateWithDraggingInfo_newDragOperation_newDropIndex_newDropOperation<R = void, P0 = unknown, P1 = number, P2 = number, P3 = number>(__updateDragAndDropStateWithDraggingInfo: P0, _newDragOperation: P1, _newDropIndex: P2, _newDropOperation: P3): R;
    _computeRowToShiftWithDropSpaceIndex_draggingInfo<R = number, P0 = number, P1 = unknown>(__computeRowToShiftWithDropSpaceIndex: P0, _draggingInfo: P1): R;
    _validateDragWithInfo_dropIndex_dropOperation<R = number, P0 = unknown, P1 = number, P2 = number>(__validateDragWithInfo: P0, _dropIndex: P1, _dropOperation: P2): R;
    _dropIndexForDraggingInfo_proposedDropOperation<R = number, P0 = unknown, P1 = number>(__dropIndexForDraggingInfo: P0, _proposedDropOperation: P1): R;
    _clearItemDraggingState<R = void>(): R;
    ignoreModifierKeysWhileDragging<R = boolean>(): R;
    draggedImage_endedAt_operation<R = void, P0 = unknown, P1 = CGPoint, P2 = number>(_draggedImage: P0, _endedAt: P1, _operation: P2): R;
    draggedImage_beganAt<R = void, P0 = unknown, P1 = CGPoint>(_draggedImage: P0, _beganAt: P1): R;
    _draggingImageForVisibleItems_boundingRect_offsetPoint<R = unknown, P0 = unknown, P1 = CGRect, P2 = CGPoint>(__draggingImageForVisibleItems: P0, _boundingRect: P1, _offsetPoint: P2): R;
    draggingImageForItemsAtIndexes_withEvent_offset<R = unknown, P0 = unknown, P1 = unknown, P2 = CGPoint>(_draggingImageForItemsAtIndexes: P0, _withEvent: P1, _offset: P2): R;
    draggingImageForItemsAtIndexPaths_withEvent_offset<R = unknown, P0 = unknown, P1 = unknown, P2 = CGPoint>(_draggingImageForItemsAtIndexPaths: P0, _withEvent: P1, _offset: P2): R;
    setDraggingSourceOperationMask_forLocal<R = void, P0 = number, P1 = boolean>(_setDraggingSourceOperationMask: P0, _forLocal: P1): R;
    _performDragFromMouseDown<R = boolean, P0 = unknown>(__performDragFromMouseDown: P0): R;
    _writeToPasteboardAndBeginDragForIndexPaths_event<R = boolean, P0 = unknown, P1 = unknown>(__writeToPasteboardAndBeginDragForIndexPaths: P0, _event: P1): R;
    _startDragWithItemsAtIndexes_event_pasteboard<R = void, P0 = unknown, P1 = unknown, P2 = unknown>(__startDragWithItemsAtIndexes: P0, _event: P1, _pasteboard: P2): R;
    _startDragWithItemsAtIndexPaths_event_pasteboard<R = void, P0 = unknown, P1 = unknown, P2 = unknown>(__startDragWithItemsAtIndexPaths: P0, _event: P1, _pasteboard: P2): R;
    _draggingImageForItemsAtIndexes_withEvent_offset<R = unknown, P0 = unknown, P1 = unknown, P2 = CGPoint>(__draggingImageForItemsAtIndexes: P0, _withEvent: P1, _offset: P2): R;
    _draggingImageForItemsAtIndexPaths_withEvent_offset<R = unknown, P0 = unknown, P1 = unknown, P2 = CGPoint>(__draggingImageForItemsAtIndexPaths: P0, _withEvent: P1, _offset: P2): R;
    _writeItemsAtIndexes_toPasteboard<R = boolean, P0 = unknown, P1 = unknown>(__writeItemsAtIndexes: P0, _toPasteboard: P1): R;
    _pasteboardWriterForItemAtIndexPath<R = unknown, P0 = unknown>(__pasteboardWriterForItemAtIndexPath: P0): R;
    _canGetPasteboardWritersFromDelegate<R = boolean>(): R;
    _canDragItemsAtIndexes_withEvent<R = boolean, P0 = unknown, P1 = unknown>(__canDragItemsAtIndexes: P0, _withEvent: P1): R;
    _canDragItemsAtIndexPaths_withEvent<R = boolean, P0 = unknown, P1 = unknown>(__canDragItemsAtIndexPaths: P0, _withEvent: P1): R;
    draggingSourceOperationMaskForLocal<R = number, P0 = boolean>(_draggingSourceOperationMaskForLocal: P0): R;
    draggingSession_namesOfPromisedFilesDroppedAtDestination<R = unknown, P0 = unknown, P1 = unknown>(_draggingSession: P0, _namesOfPromisedFilesDroppedAtDestination: P1): R;
    namesOfPromisedFilesDroppedAtDestination<R = unknown, P0 = unknown>(_namesOfPromisedFilesDroppedAtDestination: P0): R;
    _setProposedDropOperation<R = void, P0 = number>(__setProposedDropOperation: P0): R;
    _setDropTargetIndexPath<R = void, P0 = unknown>(__setDropTargetIndexPath: P0): R;
    _dropTargetIndexPath<R = unknown>(): R;
    _setDropReceiver<R = void, P0 = unknown>(__setDropReceiver: P0): R;
    _dropReceiver<R = unknown>(): R;
    _allowsDropOnBackground<R = boolean>(): R;
    _setOpensDropInsertionGaps<R = void, P0 = boolean>(__setOpensDropInsertionGaps: P0): R;
    _opensDropInsertionGaps<R = boolean>(): R;
    setAllowsSectionDrop<R = void, P0 = boolean>(_setAllowsSectionDrop: P0): R;
    allowsSectionDrop<R = boolean>(): R;
    validateUserInterfaceItem<R = boolean, P0 = unknown>(_validateUserInterfaceItem: P0): R;
    _indexesToSelectForEvent_initialSelectionIndexes_startingPoint_commandKey_shiftKey_rubberband<R = unknown, P0 = unknown, P1 = unknown, P2 = CGPoint, P3 = boolean, P4 = boolean, P5 = unknown>(__indexesToSelectForEvent: P0, _initialSelectionIndexes: P1, _startingPoint: P2, _commandKey: P3, _shiftKey: P4, _rubberband: P5): R;
    _hitItemAtPoint<R = unknown, P0 = CGPoint>(__hitItemAtPoint: P0): R;
    _pointWithinBounds<R = CGPoint, P0 = CGPoint>(__pointWithinBounds: P0): R;
    _setMouseSession<R = void, P0 = unknown>(__setMouseSession: P0): R;
    _mouseSession<R = unknown>(): R;
    _setFocusRingNeedsDisplayIfNecessary<R = void>(): R;
    _drawFocusRingAroundRect<R = void, P0 = CGRect>(__drawFocusRingAroundRect: P0): R;
    _shouldDrawFocus<R = boolean>(): R;
    insertBacktab<R = void, P0 = unknown>(_insertBacktab: P0): R;
    insertTab<R = void, P0 = unknown>(_insertTab: P0): R;
    observeValueForKeyPath_ofObject_change_context<R = void, P0 = unknown, P1 = unknown, P2 = unknown, P3 = void>(_observeValueForKeyPath: P0, _ofObject: P1, _change: P2, _context: P3): R;
    _unregisterFirstResponderObservance<R = void>(): R;
    _registerFirstResponderObservance<R = void>(): R;
    discardEditing<R = void>(): R;
    acceptsFirstResponder<R = boolean>(): R;
    _shouldResizeSubviewsImmediately<R = boolean>(): R;
    _clipViewFrameChanged<R = void, P0 = unknown>(__clipViewFrameChanged: P0): R;
    _updateFrame<R = void, P0 = unknown>(__updateFrame: P0): R;
    setAutoresizingMask<R = void, P0 = number>(_setAutoresizingMask: P0): R;
    _fixAutoresizingMaskForCollectionViewLayout<R = void>(): R;
    _contentSizeDidChange<R = void, P0 = CGSize>(__contentSizeDidChange: P0): R;
    _resizeToFitContentAndClipView<R = void>(): R;
    _autoConfigureScrollers<R = boolean>(): R;
    _storeCurrentFrameSize<R = void>(): R;
    needsPanelToBecomeKey<R = boolean>(): R;
    drawBackgroundOverhangInRect<R = void, P0 = CGRect>(_drawBackgroundOverhangInRect: P0): R;
    _drawBackgroundForRect<R = void, P0 = CGRect>(__drawBackgroundForRect: P0): R;
    _doSuperSetFrameSize<R = void, P0 = CGSize>(__doSuperSetFrameSize: P0): R;
    _shouldCopyConnections<R = boolean>(): R;
    instantiateWithObjectInstantiator<R = void, P0 = unknown>(_instantiateWithObjectInstantiator: P0): R;
    _cachedNibWithName_bundle<R = unknown, P0 = unknown, P1 = unknown>(__cachedNibWithName: P0, _bundle: P1): R;
    _animationDuration<R = number>(): R;
    _setAnimationDuration<R = void, P0 = number>(__setAnimationDuration: P0): R;
    indexPathsForVisibleSupplementaryElementsOfKind<R = unknown, P0 = unknown>(_indexPathsForVisibleSupplementaryElementsOfKind: P0): R;
    visibleSupplementaryViewsOfKind<R = unknown, P0 = unknown>(_visibleSupplementaryViewsOfKind: P0): R;
    visibleSupplementaryViews<R = unknown>(): R;
    supplementaryViewForElementKind_atIndexPath<R = unknown, P0 = unknown, P1 = unknown>(_supplementaryViewForElementKind: P0, _atIndexPath: P1): R;
    _indexOfSectionWithRepresentedObject<R = number, P0 = unknown>(__indexOfSectionWithRepresentedObject: P0): R;
    _indexPathOfItemWithRepresentedObject<R = unknown, P0 = unknown>(__indexPathOfItemWithRepresentedObject: P0): R;
    _representedObjectForSectionAtIndex<R = unknown, P0 = number>(__representedObjectForSectionAtIndex: P0): R;
    _indexPathForRepresentedObject<R = unknown, P0 = unknown>(__indexPathForRepresentedObject: P0): R;
    _representedObjectForItemAtIndexPath<R = unknown, P0 = unknown>(__representedObjectForItemAtIndexPath: P0): R;
    _representedObjectForSection<R = unknown, P0 = number>(__representedObjectForSection: P0): R;
    _representedObjectForIndexPath<R = unknown, P0 = unknown>(__representedObjectForIndexPath: P0): R;
    indexPathForItemAtPoint<R = unknown, P0 = CGPoint>(_indexPathForItemAtPoint: P0): R;
    indexPathForItem<R = unknown, P0 = unknown>(_indexPathForItem: P0): R;
    indexPathsForVisibleItems<R = unknown>(): R;
    visibleItems<R = unknown>(): R;
    frameForItemAtIndex<R = CGRect, P0 = number>(_frameForItemAtIndex: P0): R;
    frameForItemAtIndex_withNumberOfItems<R = CGRect, P0 = number, P1 = number>(_frameForItemAtIndex: P0, _withNumberOfItems: P1): R;
    layoutAttributesForSupplementaryElementOfKind_atIndexPath<R = unknown, P0 = unknown, P1 = unknown>(_layoutAttributesForSupplementaryElementOfKind: P0, _atIndexPath: P1): R;
    layoutAttributesForItemAtIndexPath<R = unknown, P0 = unknown>(_layoutAttributesForItemAtIndexPath: P0): R;
    itemAtIndexPath<R = unknown, P0 = unknown>(_itemAtIndexPath: P0): R;
    itemAtIndex<R = unknown, P0 = number>(_itemAtIndex: P0): R;
    newItemForRepresentedObject<R = unknown, P0 = unknown>(_newItemForRepresentedObject: P0): R;
    makeSupplementaryViewOfKind_withIdentifier_forIndexPath<R = unknown, P0 = unknown, P1 = unknown, P2 = unknown>(_makeSupplementaryViewOfKind: P0, _withIdentifier: P1, _forIndexPath: P2): R;
    dequeueReusableSupplementaryViewOfKind_withReuseIdentifier_forIndexPath<R = unknown, P0 = unknown, P1 = unknown, P2 = unknown>(_dequeueReusableSupplementaryViewOfKind: P0, _withReuseIdentifier: P1, _forIndexPath: P2): R;
    makeItemWithIdentifier_forIndexPath<R = unknown, P0 = unknown, P1 = unknown>(_makeItemWithIdentifier: P0, _forIndexPath: P1): R;
    dequeueReusableItemWithReuseIdentifier_forIndexPath<R = unknown, P0 = unknown, P1 = unknown>(_dequeueReusableItemWithReuseIdentifier: P0, _forIndexPath: P1): R;
    _registeredCellNibsByReuseIdentifier<R = unknown>(): R;
    _registeredCellClassesByReuseIdentifier<R = unknown>(): R;
    registerNib_forSupplementaryViewOfKind_withIdentifier<R = void, P0 = unknown, P1 = unknown, P2 = unknown>(_registerNib: P0, _forSupplementaryViewOfKind: P1, _withIdentifier: P2): R;
    registerClass_forSupplementaryViewOfKind_withIdentifier<R = void, P0 = unknown, P1 = unknown, P2 = unknown>(_registerClass: P0, _forSupplementaryViewOfKind: P1, _withIdentifier: P2): R;
    registerNib_forItemWithIdentifier<R = void, P0 = unknown, P1 = unknown>(_registerNib: P0, _forItemWithIdentifier: P1): R;
    registerClass_forItemWithIdentifier<R = void, P0 = unknown, P1 = unknown>(_registerClass: P0, _forItemWithIdentifier: P1): R;
    registerNib_forSupplementaryViewOfKind_withReuseIdentifier<R = void, P0 = unknown, P1 = unknown, P2 = unknown>(_registerNib: P0, _forSupplementaryViewOfKind: P1, _withReuseIdentifier: P2): R;
    registerClass_forSupplementaryViewOfKind_withReuseIdentifier<R = void, P0 = unknown, P1 = unknown, P2 = unknown>(_registerClass: P0, _forSupplementaryViewOfKind: P1, _withReuseIdentifier: P2): R;
    registerNib_forItemWithReuseIdentifier<R = void, P0 = unknown, P1 = unknown>(_registerNib: P0, _forItemWithReuseIdentifier: P1): R;
    registerClass_forItemWithReuseIdentifier<R = void, P0 = unknown, P1 = unknown>(_registerClass: P0, _forItemWithReuseIdentifier: P1): R;
    isOpaque<R = boolean>(): R;
    _backgroundColorFillView<R = unknown>(): R;
    _setBackgroundColorFillView<R = void, P0 = unknown>(__setBackgroundColorFillView: P0): R;
    _didChangeItemsAtIndexPaths_toHighlightState<R = void, P0 = unknown, P1 = number>(__didChangeItemsAtIndexPaths: P0, _toHighlightState: P1): R;
    _shouldChangeItemsAtIndexPaths_toHighlightState<R = unknown, P0 = unknown, P1 = number>(__shouldChangeItemsAtIndexPaths: P0, _toHighlightState: P1): R;
    deselectItemsAtIndexPaths<R = void, P0 = unknown>(_deselectItemsAtIndexPaths: P0): R;
    _deselectItemsAtIndexPaths_thenSelectItemsAtIndexPaths_scrollPosition_notifyDelegate<R = void, P0 = unknown, P1 = unknown, P2 = number, P3 = boolean>(__deselectItemsAtIndexPaths: P0, _thenSelectItemsAtIndexPaths: P1, _scrollPosition: P2, _notifyDelegate: P3): R;
    _deselectItemsAtIndexPaths_notifyDelegate<R = unknown, P0 = unknown, P1 = boolean>(__deselectItemsAtIndexPaths: P0, _notifyDelegate: P1): R;
    deselectItemAtIndexPath<R = void, P0 = unknown>(_deselectItemAtIndexPath: P0): R;
    selectItemsAtIndexPaths_scrollPosition<R = void, P0 = unknown, P1 = number>(_selectItemsAtIndexPaths: P0, _scrollPosition: P1): R;
    _selectItemsAtIndexPaths_scrollPosition_notifyDelegate<R = unknown, P0 = unknown, P1 = number, P2 = boolean>(__selectItemsAtIndexPaths: P0, _scrollPosition: P1, _notifyDelegate: P2): R;
    selectItemAtIndexPath_scrollPosition<R = void, P0 = unknown, P1 = number>(_selectItemAtIndexPath: P0, _scrollPosition: P1): R;
    avoidsEmptySelection<R = boolean>(): R;
    setAvoidsEmptySelection<R = void, P0 = boolean>(_setAvoidsEmptySelection: P0): R;
    maxNumberOfColumns<R = number>(): R;
    setMaxNumberOfColumns<R = void, P0 = number>(_setMaxNumberOfColumns: P0): R;
    maxNumberOfRows<R = number>(): R;
    setMaxNumberOfRows<R = void, P0 = number>(_setMaxNumberOfRows: P0): R;
    maxItemSize<R = CGSize>(): R;
    setMaxItemSize<R = void, P0 = CGSize>(_setMaxItemSize: P0): R;
    minItemSize<R = CGSize>(): R;
    setMinItemSize<R = void, P0 = CGSize>(_setMinItemSize: P0): R;
    _setCollectionViewLayout_animate<R = void, P0 = unknown, P1 = boolean>(__setCollectionViewLayout: P0, _animate: P1): R;
    itemPrototype<R = unknown>(): R;
    setItemPrototype<R = void, P0 = unknown>(_setItemPrototype: P0): R;
    reloadItemsAtIndexes_inSectionObject<R = void, P0 = unknown, P1 = unknown>(_reloadItemsAtIndexes: P0, _inSectionObject: P1): R;
    deleteItemsAtIndexes_inSectionObject<R = void, P0 = unknown, P1 = unknown>(_deleteItemsAtIndexes: P0, _inSectionObject: P1): R;
    insertItemsAtIndexes_inSectionObject<R = void, P0 = unknown, P1 = unknown>(_insertItemsAtIndexes: P0, _inSectionObject: P1): R;
    _indexPathsFromItemIndexes_inSectionObject<R = unknown, P0 = unknown, P1 = unknown>(__indexPathsFromItemIndexes: P0, _inSectionObject: P1): R;
    performBatchUpdates_completion<R = void, P0 = CDUnknownBlockType, P1 = CDUnknownBlockType>(_performBatchUpdates: P0, _completion: P1): R;
    _setFinishesBatchUpdateBeforeInvokingCompletionHandler<R = void, P0 = boolean>(__setFinishesBatchUpdateBeforeInvokingCompletionHandler: P0): R;
    _finishesBatchUpdateBeforeInvokingCompletionHandler<R = boolean>(): R;
    performBatchUpdates_completionHandler<R = void, P0 = CDUnknownBlockType, P1 = CDUnknownBlockType>(_performBatchUpdates: P0, _completionHandler: P1): R;
    moveItemAtIndexPath_toIndexPath<R = void, P0 = unknown, P1 = unknown>(_moveItemAtIndexPath: P0, _toIndexPath: P1): R;
    reloadItemsAtIndexPaths<R = void, P0 = unknown>(_reloadItemsAtIndexPaths: P0): R;
    deleteItemsAtIndexPaths<R = void, P0 = unknown>(_deleteItemsAtIndexPaths: P0): R;
    insertItemsAtIndexPaths<R = void, P0 = unknown>(_insertItemsAtIndexPaths: P0): R;
    moveSection_toSection<R = void, P0 = number, P1 = number>(_moveSection: P0, _toSection: P1): R;
    reloadSections<R = void, P0 = unknown>(_reloadSections: P0): R;
    deleteSections<R = void, P0 = unknown>(_deleteSections: P0): R;
    insertSections<R = void, P0 = unknown>(_insertSections: P0): R;
    _insertSections_representedObjects<R = void, P0 = unknown, P1 = unknown>(__insertSections: P0, _representedObjects: P1): R;
    _hasAnyItems<R = boolean>(): R;
    _indexPathsInclusiveFrom_to<R = unknown, P0 = unknown, P1 = unknown>(__indexPathsInclusiveFrom: P0, _to: P1): R;
    _indexPathsForAllItemsInAllSections<R = unknown>(): R;
    _indexPathsForAllItemsInSection<R = unknown, P0 = number>(__indexPathsForAllItemsInSection: P0): R;
    numberOfItemsInSection<R = number, P0 = number>(_numberOfItemsInSection: P0): R;
    _delegate<R = unknown>(): R;
    _representedObjectForCurrentDataSourceInvocation<R = unknown>(): R;
    _dataSourceAdapter<R = unknown>(): R;
    _itemForRepresentedObjectAtIndexPath<R = unknown, P0 = unknown>(__itemForRepresentedObjectAtIndexPath: P0): R;
    _createDataSourceAdapterForDataSource<R = void, P0 = unknown>(__createDataSourceAdapterForDataSource: P0): R;
    reloadData<R = void>(): R;
    _restoreFrameBeforeRestoringScrollPosition<R = void, P0 = CGRect>(__restoreFrameBeforeRestoringScrollPosition: P0): R;
    _discardCore<R = void>(): R;
    _allocCoreWithLayout_duringInit<R = void, P0 = unknown, P1 = boolean>(__allocCoreWithLayout: P0, _duringInit: P1): R;
    _makeDefaultGridLayout<R = unknown>(): R;
    _commonInitCore<R = void>(): R;
    _commonInit<R = void>(): R;
    _gridLayout<R = unknown>(): R;
    _setDebugModeEnabled<R = void, P0 = boolean>(__setDebugModeEnabled: P0): R;
    _debugModeEnabled<R = boolean>(): R;
    _collectionViewSupports10_11Features<R = boolean>(): R;
    _lastIndexPathInSection<R = unknown, P0 = number>(__lastIndexPathInSection: P0): R;
    _firstIndexPathInSection<R = unknown, P0 = number>(__firstIndexPathInSection: P0): R;
    _lastIndexPathOfPreviousSectionFromIndexPath<R = unknown, P0 = unknown>(__lastIndexPathOfPreviousSectionFromIndexPath: P0): R;
    _firstIndexPathOfNextSectionFromIndexPath<R = unknown, P0 = unknown>(__firstIndexPathOfNextSectionFromIndexPath: P0): R;
    accessibilityOrderedByRowAttribute<R = unknown>(): R;
    _accessibilityNumberOfChildren<R = number>(): R;
    _accessibilityChildrenAtIndexes<R = unknown, P0 = unknown>(__accessibilityChildrenAtIndexes: P0): R;
    accessibilityIsSelectedChildrenAttributeSettable<R = boolean>(): R;
    accessibilityIsVisibleChildrenAttributeSettable<R = boolean>(): R;
    accessibilityIsRowCountAttributeSettable<R = boolean>(): R;
    accessibilityIsOrientationAttributeSettable<R = boolean>(): R;
    accessibilityIsOrderedByRowAttributeSettable<R = boolean>(): R;
    accessibilityIsColumnCountAttributeSettable<R = boolean>(): R;
    accessibilitySelectItemsAtIndexPaths<R = void, P0 = unknown>(_accessibilitySelectItemsAtIndexPaths: P0): R;
    accessibilityArrayAttributeValues_index_maxCount<R = unknown, P0 = unknown, P1 = number, P2 = number>(_accessibilityArrayAttributeValues: P0, _index: P1, _maxCount: P2): R;
    accessibilityArrayAttributeCount<R = number, P0 = unknown>(_accessibilityArrayAttributeCount: P0): R;
    accessibilityIndexOfChild<R = number, P0 = unknown>(_accessibilityIndexOfChild: P0): R;
    accessibilityOrientationAttribute<R = unknown>(): R;
    accessibilityVisibleChildrenAttribute<R = unknown>(): R;
    accessibilitySetSelectedChildrenAttribute<R = void, P0 = unknown>(_accessibilitySetSelectedChildrenAttribute: P0): R;
    accessibilitySelectedChildrenAttribute<R = unknown>(): R;
    accessibilityColumnCountAttribute<R = unknown>(): R;
    accessibilityRowCountAttribute<R = unknown>(): R;
    accessibilityEnabledAttribute<R = unknown>(): R;
    accessibilitySubroleAttribute<R = unknown>(): R;
    _accessibilityAttributeNames1010<R = unknown>(): R;
    _accessibilityAttributeNames1011<R = unknown>(): R;
    accessibilityItemAtIndexPath<R = unknown, P0 = unknown>(_accessibilityItemAtIndexPath: P0): R;
    resetCollectionViewAccessibility<R = void>(): R;
    collectionViewAccessibilityIfLoaded<R = unknown>(): R;
    collectionViewAccessibility<R = unknown>(): R;
    _itemForRepresentedObject<R = unknown, P0 = unknown>(__itemForRepresentedObject: P0): R;
    firstResponder<R = boolean>(): R;
    backgroundViewScrollsWithContent<R = boolean>(): R;
    setBackgroundViewScrollsWithContent<R = void, P0 = boolean>(_v: P0): R;
    backgroundView<R = NSView>(): R;
    setBackgroundView<R = void, P0 = NSView>(_v: P0): R;
    backgroundColors<R = NSArray>(): R;
    setBackgroundColors<R = void, P0 = NSArray>(_v: P0): R;
    selectionIndexes<R = NSIndexSet>(): R;
    setSelectionIndexes<R = void, P0 = NSIndexSet>(_v: P0): R;
    selectionIndexPaths<R = NSSet>(): R;
    setSelectionIndexPaths<R = void, P0 = NSSet>(_v: P0): R;
    allowsEmptySelection<R = boolean>(): R;
    setAllowsEmptySelection<R = void, P0 = boolean>(_v: P0): R;
    allowsMultipleSelection<R = boolean>(): R;
    setAllowsMultipleSelection<R = void, P0 = boolean>(_v: P0): R;
    selectable<R = boolean>(): R;
    setSelectable<R = void, P0 = boolean>(_v: P0): R;
    collectionViewLayout<R = NSCollectionViewLayout>(): R;
    setCollectionViewLayout<R = void, P0 = NSCollectionViewLayout>(_v: P0): R;
    numberOfSections<R = number>(): R;
    content<R = NSArray>(): R;
    setContent<R = void, P0 = NSArray>(_v: P0): R;
    delegate<R = NSCollectionViewDelegate>(): R;
    setDelegate<R = void, P0 = NSCollectionViewDelegate>(_v: P0): R;
    prefetchDataSource<R = NSCollectionViewPrefetching>(): R;
    setPrefetchDataSource<R = void, P0 = NSCollectionViewPrefetching>(_v: P0): R;
    dataSource<R = NSCollectionViewDataSource>(): R;
    setDataSource<R = void, P0 = NSCollectionViewDataSource>(_v: P0): R;
    debugDescription<R = NSString>(): R;
    description<R = NSString>(): R;
    hash<R = number>(): R;
    superclass<R = unknown>(): R;
  }
  namespace NSCollectionView {
    export interface CLASS<T0 = void, T1 = void, T2 = void> extends NSView, NSDraggingSourceProtocol, NSDraggingDestinationProtocol {
      alloc<R = NSCollectionView>(): R;
      new: <R = NSCollectionView>() => R;
      _dropHighlightWidthForSections<R = number>(): R;
      _dropHighlightColorForSections<R = unknown>(): R;
    }
  }
}

declare const NSCollectionView: cocoa.NSCollectionView.CLASS;
