/// <reference no-default-lib="true" />

declare namespace cocoa {
  export interface NSResponder<T0 = void, T1 = void, T2 = void> extends NSObject, NSTouchBarProviderContainerProtocol, NSUIActivityProviderProtocol, NSTouchBarProviderProtocol, _NSQuickActionItemSourceProtocol, NSCodingProtocol {
    _ignoreBadFirstResponders<R = boolean>(): R;
    accessibilityPerformShowMenu<R = boolean>(): R;
    accessibilityPerformShowDefaultUI<R = boolean>(): R;
    accessibilityPerformShowAlternateUI<R = boolean>(): R;
    accessibilityPerformRaise<R = boolean>(): R;
    accessibilityPerformPress<R = boolean>(): R;
    accessibilityPerformPick<R = boolean>(): R;
    accessibilityPerformIncrement<R = boolean>(): R;
    accessibilityPerformDelete<R = boolean>(): R;
    accessibilityPerformDecrement<R = boolean>(): R;
    accessibilityPerformConfirm<R = boolean>(): R;
    accessibilityPerformCancel<R = boolean>(): R;
    setAccessibilityContentSiblingBelow<R = void, P0 = unknown>(_setAccessibilityContentSiblingBelow: P0): R;
    accessibilityContentSiblingBelow<R = unknown>(): R;
    setAccessibilityContentSiblingAbove<R = void, P0 = unknown>(_setAccessibilityContentSiblingAbove: P0): R;
    accessibilityContentSiblingAbove<R = unknown>(): R;
    setNextContentSibling<R = void, P0 = unknown>(_setNextContentSibling: P0): R;
    accessibilityNextContentSibling<R = unknown>(): R;
    setPreviousContentSibling<R = void, P0 = unknown>(_setPreviousContentSibling: P0): R;
    accessibilityPreviousContentSibling<R = unknown>(): R;
    setAccessibilityZoomButton<R = void, P0 = unknown>(_setAccessibilityZoomButton: P0): R;
    accessibilityZoomButton<R = unknown>(): R;
    setAccessibilityWindows<R = void, P0 = unknown>(_setAccessibilityWindows: P0): R;
    accessibilityWindows<R = unknown>(): R;
    setAccessibilityWindow<R = void, P0 = unknown>(_setAccessibilityWindow: P0): R;
    accessibilityWindow<R = unknown>(): R;
    setAccessibilityWarningValue<R = void, P0 = unknown>(_setAccessibilityWarningValue: P0): R;
    accessibilityWarningValue<R = unknown>(): R;
    setAccessibilityVisibleRows<R = void, P0 = unknown>(_setAccessibilityVisibleRows: P0): R;
    accessibilityVisibleRows<R = unknown>(): R;
    setAccessibilityVisibleColumns<R = void, P0 = unknown>(_setAccessibilityVisibleColumns: P0): R;
    accessibilityVisibleColumns<R = unknown>(): R;
    setAccessibilityVisibleChildren<R = void, P0 = unknown>(_setAccessibilityVisibleChildren: P0): R;
    accessibilityVisibleChildren<R = unknown>(): R;
    setAccessibilityVisibleCharacterRange<R = void, P0 = _NSRange>(_setAccessibilityVisibleCharacterRange: P0): R;
    accessibilityVisibleCharacterRange<R = _NSRange>(): R;
    setAccessibilityVisibleCells<R = void, P0 = unknown>(_setAccessibilityVisibleCells: P0): R;
    accessibilityVisibleCells<R = unknown>(): R;
    setAccessibilityVerticalUnits<R = void, P0 = number>(_setAccessibilityVerticalUnits: P0): R;
    accessibilityVerticalUnits<R = number>(): R;
    setAccessibilityVerticalUnitDescription<R = void, P0 = unknown>(_setAccessibilityVerticalUnitDescription: P0): R;
    accessibilityVerticalUnitDescription<R = unknown>(): R;
    setAccessibilityVerticalScrollBar<R = void, P0 = unknown>(_setAccessibilityVerticalScrollBar: P0): R;
    accessibilityVerticalScrollBar<R = unknown>(): R;
    setAccessibilityValueDescription<R = void, P0 = unknown>(_setAccessibilityValueDescription: P0): R;
    accessibilityValueDescription<R = unknown>(): R;
    setAccessibilityValue<R = void, P0 = unknown>(_setAccessibilityValue: P0): R;
    accessibilityValue<R = unknown>(): R;
    setAccessibilityUnits<R = void, P0 = number>(_setAccessibilityUnits: P0): R;
    accessibilityUnits<R = number>(): R;
    setAccessibilityUnitDescription<R = void, P0 = unknown>(_setAccessibilityUnitDescription: P0): R;
    accessibilityUnitDescription<R = unknown>(): R;
    setAccessibilityURL<R = void, P0 = unknown>(_setAccessibilityURL: P0): R;
    accessibilityURL<R = unknown>(): R;
    setAccessibilityTopLevelUIElement<R = void, P0 = unknown>(_setAccessibilityTopLevelUIElement: P0): R;
    accessibilityTopLevelUIElement<R = unknown>(): R;
    setAccessibilityToolbarButton<R = void, P0 = unknown>(_setAccessibilityToolbarButton: P0): R;
    accessibilityToolbarButton<R = unknown>(): R;
    setAccessibilityTitleUIElement<R = void, P0 = unknown>(_setAccessibilityTitleUIElement: P0): R;
    accessibilityTitleUIElement<R = unknown>(): R;
    setAccessibilityTitle<R = void, P0 = unknown>(_setAccessibilityTitle: P0): R;
    accessibilityTitle<R = unknown>(): R;
    setAccessibilityTabs<R = void, P0 = unknown>(_setAccessibilityTabs: P0): R;
    accessibilityTabs<R = unknown>(): R;
    setAccessibilitySubrole<R = void, P0 = unknown>(_setAccessibilitySubrole: P0): R;
    accessibilitySubrole<R = unknown>(): R;
    setAccessibilitySplitters<R = void, P0 = unknown>(_setAccessibilitySplitters: P0): R;
    accessibilitySplitters<R = unknown>(): R;
    setAccessibilitySortDirection<R = void, P0 = number>(_setAccessibilitySortDirection: P0): R;
    accessibilitySortDirection<R = number>(): R;
    setAccessibilityFrameInParentSpace<R = void, P0 = CGRect>(_setAccessibilityFrameInParentSpace: P0): R;
    accessibilityFrameInParentSpace<R = CGRect>(): R;
    setAccessibilityFrame<R = void, P0 = CGRect>(_setAccessibilityFrame: P0): R;
    accessibilityFrame<R = CGRect>(): R;
    setAccessibilityShownMenu<R = void, P0 = unknown>(_setAccessibilityShownMenu: P0): R;
    accessibilityShownMenu<R = unknown>(): R;
    setAccessibilitySharedTextUIElements<R = void, P0 = unknown>(_setAccessibilitySharedTextUIElements: P0): R;
    accessibilitySharedTextUIElements<R = unknown>(): R;
    setAccessibilitySharedFocusElements<R = void, P0 = unknown>(_setAccessibilitySharedFocusElements: P0): R;
    accessibilitySharedFocusElements<R = unknown>(): R;
    setAccessibilitySharedCharacterRange<R = void, P0 = _NSRange>(_setAccessibilitySharedCharacterRange: P0): R;
    accessibilitySharedCharacterRange<R = _NSRange>(): R;
    setAccessibilityServesAsTitleForUIElements<R = void, P0 = unknown>(_setAccessibilityServesAsTitleForUIElements: P0): R;
    accessibilityServesAsTitleForUIElements<R = unknown>(): R;
    setAccessibilitySelectedTextRanges<R = void, P0 = unknown>(_setAccessibilitySelectedTextRanges: P0): R;
    accessibilitySelectedTextRanges<R = unknown>(): R;
    setAccessibilitySelectedTextRange<R = void, P0 = _NSRange>(_setAccessibilitySelectedTextRange: P0): R;
    accessibilitySelectedTextRange<R = _NSRange>(): R;
    setAccessibilitySelectedText<R = void, P0 = unknown>(_setAccessibilitySelectedText: P0): R;
    accessibilitySelectedText<R = unknown>(): R;
    setAccessibilitySelectedRows<R = void, P0 = unknown>(_setAccessibilitySelectedRows: P0): R;
    accessibilitySelectedRows<R = unknown>(): R;
    setAccessibilityHeaderGroup<R = void, P0 = unknown>(_setAccessibilityHeaderGroup: P0): R;
    accessibilityHeaderGroup<R = unknown>(): R;
    setAccessibilitySelectedColumns<R = void, P0 = unknown>(_setAccessibilitySelectedColumns: P0): R;
    accessibilitySelectedColumns<R = unknown>(): R;
    setAccessibilitySelectedChildren<R = void, P0 = unknown>(_setAccessibilitySelectedChildren: P0): R;
    accessibilitySelectedChildren<R = unknown>(): R;
    setAccessibilitySelectedCells<R = void, P0 = unknown>(_setAccessibilitySelectedCells: P0): R;
    accessibilitySelectedCells<R = unknown>(): R;
    setAccessibilitySelected<R = void, P0 = boolean>(_setAccessibilitySelected: P0): R;
    isAccessibilitySelected<R = boolean>(): R;
    setAccessibilitySections<R = void, P0 = unknown>(_setAccessibilitySections: P0): R;
    accessibilitySections<R = unknown>(): R;
    setAccessibilitySearchMenu<R = void, P0 = unknown>(_setAccessibilitySearchMenu: P0): R;
    accessibilitySearchMenu<R = unknown>(): R;
    setAccessibilitySearchButton<R = void, P0 = unknown>(_setAccessibilitySearchButton: P0): R;
    accessibilitySearchButton<R = unknown>(): R;
    setAccessibilityRows<R = void, P0 = unknown>(_setAccessibilityRows: P0): R;
    accessibilityRows<R = unknown>(): R;
    setAccessibilityRowIndexRange<R = void, P0 = _NSRange>(_setAccessibilityRowIndexRange: P0): R;
    accessibilityRowIndexRange<R = _NSRange>(): R;
    setAccessibilityRowHeaderUIElements<R = void, P0 = unknown>(_setAccessibilityRowHeaderUIElements: P0): R;
    accessibilityRowHeaderUIElements<R = unknown>(): R;
    setAccessibilityRowCount<R = void, P0 = number>(_setAccessibilityRowCount: P0): R;
    accessibilityRowCount<R = number>(): R;
    setAccessibilityRoleDescription<R = void, P0 = unknown>(_setAccessibilityRoleDescription: P0): R;
    accessibilityRoleDescription<R = unknown>(): R;
    setAccessibilityRole<R = void, P0 = unknown>(_setAccessibilityRole: P0): R;
    accessibilityRole<R = unknown>(): R;
    setAccessibilityRequired<R = void, P0 = boolean>(_setAccessibilityRequired: P0): R;
    isAccessibilityRequired<R = boolean>(): R;
    setAccessibilityProxy<R = void, P0 = unknown>(_setAccessibilityProxy: P0): R;
    accessibilityProxy<R = unknown>(): R;
    setAccessibilityPreviousContents<R = void, P0 = unknown>(_setAccessibilityPreviousContents: P0): R;
    accessibilityPreviousContents<R = unknown>(): R;
    setAccessibilityPlaceholderValue<R = void, P0 = unknown>(_setAccessibilityPlaceholderValue: P0): R;
    accessibilityPlaceholderValue<R = unknown>(): R;
    setAccessibilityParent<R = void, P0 = unknown>(_setAccessibilityParent: P0): R;
    accessibilityParent<R = unknown>(): R;
    setAccessibilityOverflowButton<R = void, P0 = unknown>(_setAccessibilityOverflowButton: P0): R;
    accessibilityOverflowButton<R = unknown>(): R;
    setAccessibilityOrientation<R = void, P0 = number>(_setAccessibilityOrientation: P0): R;
    accessibilityOrientation<R = number>(): R;
    setAccessibilityOrderedByRow<R = void, P0 = boolean>(_setAccessibilityOrderedByRow: P0): R;
    isAccessibilityOrderedByRow<R = boolean>(): R;
    setAccessibilityNumberOfCharacters<R = void, P0 = number>(_setAccessibilityNumberOfCharacters: P0): R;
    accessibilityNumberOfCharacters<R = number>(): R;
    setAccessibilityNextContents<R = void, P0 = unknown>(_setAccessibilityNextContents: P0): R;
    accessibilityNextContents<R = unknown>(): R;
    setAccessibilityModal<R = void, P0 = boolean>(_setAccessibilityModal: P0): R;
    isAccessibilityModal<R = boolean>(): R;
    setAccessibilityMinimized<R = void, P0 = boolean>(_setAccessibilityMinimized: P0): R;
    isAccessibilityMinimized<R = boolean>(): R;
    setAccessibilityMinimizeButton<R = void, P0 = unknown>(_setAccessibilityMinimizeButton: P0): R;
    accessibilityMinimizeButton<R = unknown>(): R;
    setAccessibilityMinValue<R = void, P0 = unknown>(_setAccessibilityMinValue: P0): R;
    accessibilityMinValue<R = unknown>(): R;
    setAccessibilityMimicNativeView<R = void, P0 = boolean>(_setAccessibilityMimicNativeView: P0): R;
    isAccessibilityMimicNativeView<R = boolean>(): R;
    setAccessibilityMenuBar<R = void, P0 = unknown>(_setAccessibilityMenuBar: P0): R;
    accessibilityMenuBar<R = unknown>(): R;
    setAccessibilityMaxValue<R = void, P0 = unknown>(_setAccessibilityMaxValue: P0): R;
    accessibilityMaxValue<R = unknown>(): R;
    setAccessibilityMarkerValues<R = void, P0 = unknown>(_setAccessibilityMarkerValues: P0): R;
    accessibilityMarkerValues<R = unknown>(): R;
    setAccessibilityMarkerUIElements<R = void, P0 = unknown>(_setAccessibilityMarkerUIElements: P0): R;
    accessibilityMarkerUIElements<R = unknown>(): R;
    setAccessibilityMarkerTypeDescription<R = void, P0 = unknown>(_setAccessibilityMarkerTypeDescription: P0): R;
    accessibilityMarkerTypeDescription<R = unknown>(): R;
    setAccessibilityRulerMarkerType<R = void, P0 = number>(_setAccessibilityRulerMarkerType: P0): R;
    accessibilityRulerMarkerType<R = number>(): R;
    setAccessibilityMarkerGroupUIElement<R = void, P0 = unknown>(_setAccessibilityMarkerGroupUIElement: P0): R;
    accessibilityMarkerGroupUIElement<R = unknown>(): R;
    setAccessibilityMainWindow<R = void, P0 = unknown>(_setAccessibilityMainWindow: P0): R;
    accessibilityMainWindow<R = unknown>(): R;
    setAccessibilityMain<R = void, P0 = boolean>(_setAccessibilityMain: P0): R;
    isAccessibilityMain<R = boolean>(): R;
    setAccessibilityLinkedUIElements<R = void, P0 = unknown>(_setAccessibilityLinkedUIElements: P0): R;
    accessibilityLinkedUIElements<R = unknown>(): R;
    setAccessibilityLabelValue<R = void, P0 = number>(_setAccessibilityLabelValue: P0): R;
    accessibilityLabelValue<R = number>(): R;
    setAccessibilityLabelUIElements<R = void, P0 = unknown>(_setAccessibilityLabelUIElements: P0): R;
    accessibilityLabelUIElements<R = unknown>(): R;
    setAccessibilityInsertionPointLineNumber<R = void, P0 = number>(_setAccessibilityInsertionPointLineNumber: P0): R;
    accessibilityInsertionPointLineNumber<R = number>(): R;
    setAccessibilityIndex<R = void, P0 = number>(_setAccessibilityIndex: P0): R;
    accessibilityIndex<R = number>(): R;
    setAccessibilityIncrementButton<R = void, P0 = unknown>(_setAccessibilityIncrementButton: P0): R;
    accessibilityIncrementButton<R = unknown>(): R;
    setAccessibilityIdentifier<R = void, P0 = unknown>(_setAccessibilityIdentifier: P0): R;
    accessibilityIdentifier<R = unknown>(): R;
    setAccessibilityHorizontalUnits<R = void, P0 = number>(_setAccessibilityHorizontalUnits: P0): R;
    accessibilityHorizontalUnits<R = number>(): R;
    setAccessibilityHorizontalUnitDescription<R = void, P0 = unknown>(_setAccessibilityHorizontalUnitDescription: P0): R;
    accessibilityHorizontalUnitDescription<R = unknown>(): R;
    setAccessibilityHorizontalScrollBar<R = void, P0 = unknown>(_setAccessibilityHorizontalScrollBar: P0): R;
    accessibilityHorizontalScrollBar<R = unknown>(): R;
    setAccessibilityHidden<R = void, P0 = boolean>(_setAccessibilityHidden: P0): R;
    isAccessibilityHidden<R = boolean>(): R;
    setAccessibilityHelp<R = void, P0 = unknown>(_setAccessibilityHelp: P0): R;
    accessibilityHelp<R = unknown>(): R;
    setAccessibilityHeader<R = void, P0 = unknown>(_setAccessibilityHeader: P0): R;
    accessibilityHeader<R = unknown>(): R;
    setAccessibilityHandles<R = void, P0 = unknown>(_setAccessibilityHandles: P0): R;
    accessibilityHandles<R = unknown>(): R;
    setAccessibilityGrowArea<R = void, P0 = unknown>(_setAccessibilityGrowArea: P0): R;
    accessibilityGrowArea<R = unknown>(): R;
    setAccessibilityFunctionRowTopLevelElements<R = void, P0 = unknown>(_setAccessibilityFunctionRowTopLevelElements: P0): R;
    accessibilityFunctionRowTopLevelElements<R = unknown>(): R;
    setAccessibilityFullScreenButton<R = void, P0 = unknown>(_setAccessibilityFullScreenButton: P0): R;
    accessibilityFullScreenButton<R = unknown>(): R;
    setAccessibilityFrontmost<R = void, P0 = boolean>(_setAccessibilityFrontmost: P0): R;
    isAccessibilityFrontmost<R = boolean>(): R;
    setAccessibilityFocusedWindow<R = void, P0 = unknown>(_setAccessibilityFocusedWindow: P0): R;
    accessibilityFocusedWindow<R = unknown>(): R;
    setAccessibilityApplicationFocusedUIElement<R = void, P0 = unknown>(_setAccessibilityApplicationFocusedUIElement: P0): R;
    accessibilityApplicationFocusedUIElement<R = unknown>(): R;
    setAccessibilityFocused<R = void, P0 = boolean>(_setAccessibilityFocused: P0): R;
    isAccessibilityFocused<R = boolean>(): R;
    setAccessibilityFilename<R = void, P0 = unknown>(_setAccessibilityFilename: P0): R;
    accessibilityFilename<R = unknown>(): R;
    setAccessibilityExtrasMenuBar<R = void, P0 = unknown>(_setAccessibilityExtrasMenuBar: P0): R;
    accessibilityExtrasMenuBar<R = unknown>(): R;
    setAccessibilityExpanded<R = void, P0 = boolean>(_setAccessibilityExpanded: P0): R;
    isAccessibilityExpanded<R = boolean>(): R;
    setAccessibilityEnhancedUserInterface<R = void, P0 = boolean>(_setAccessibilityEnhancedUserInterface: P0): R;
    isAccessibilityEnhancedUserInterface<R = boolean>(): R;
    setAccessibilityEnabled<R = void, P0 = boolean>(_setAccessibilityEnabled: P0): R;
    isAccessibilityEnabled<R = boolean>(): R;
    setAccessibilityEdited<R = void, P0 = boolean>(_setAccessibilityEdited: P0): R;
    isAccessibilityEdited<R = boolean>(): R;
    setAccessibilityDocument<R = void, P0 = unknown>(_setAccessibilityDocument: P0): R;
    accessibilityDocument<R = unknown>(): R;
    setAccessibilityDisclosureLevel<R = void, P0 = number>(_setAccessibilityDisclosureLevel: P0): R;
    accessibilityDisclosureLevel<R = number>(): R;
    setAccessibilityDisclosed<R = void, P0 = boolean>(_setAccessibilityDisclosed: P0): R;
    isAccessibilityDisclosed<R = boolean>(): R;
    setAccessibilityDisclosedRows<R = void, P0 = unknown>(_setAccessibilityDisclosedRows: P0): R;
    accessibilityDisclosedRows<R = unknown>(): R;
    setAccessibilityDisclosedByRow<R = void, P0 = unknown>(_setAccessibilityDisclosedByRow: P0): R;
    accessibilityDisclosedByRow<R = unknown>(): R;
    accessibilityLabel<R = unknown>(): R;
    setAccessibilityLabel<R = void, P0 = unknown>(_setAccessibilityLabel: P0): R;
    _accessibilityLabel<R = unknown>(): R;
    setAccessibilityDefaultButton<R = void, P0 = unknown>(_setAccessibilityDefaultButton: P0): R;
    accessibilityDefaultButton<R = unknown>(): R;
    setAccessibilityDecrementButton<R = void, P0 = unknown>(_setAccessibilityDecrementButton: P0): R;
    accessibilityDecrementButton<R = unknown>(): R;
    setAccessibilityCustomRotors<R = void, P0 = unknown>(_setAccessibilityCustomRotors: P0): R;
    accessibilityCustomRotors<R = unknown>(): R;
    setAccessibilityCustomChoosers<R = void, P0 = unknown>(_setAccessibilityCustomChoosers: P0): R;
    accessibilityCustomChoosers<R = unknown>(): R;
    setAccessibilityCustomActions<R = void, P0 = unknown>(_setAccessibilityCustomActions: P0): R;
    accessibilityCustomActions<R = unknown>(): R;
    setAccessibilityCriticalValue<R = void, P0 = unknown>(_setAccessibilityCriticalValue: P0): R;
    accessibilityCriticalValue<R = unknown>(): R;
    setAccessibilityContents<R = void, P0 = unknown>(_setAccessibilityContents: P0): R;
    accessibilityContents<R = unknown>(): R;
    setAccessibilityProtectedContent<R = void, P0 = boolean>(_setAccessibilityProtectedContent: P0): R;
    isAccessibilityProtectedContent<R = boolean>(): R;
    setAccessibilityColumns<R = void, P0 = unknown>(_setAccessibilityColumns: P0): R;
    accessibilityColumns<R = unknown>(): R;
    setAccessibilityColumnTitles<R = void, P0 = unknown>(_setAccessibilityColumnTitles: P0): R;
    accessibilityColumnTitles<R = unknown>(): R;
    setAccessibilityColumnIndexRange<R = void, P0 = _NSRange>(_setAccessibilityColumnIndexRange: P0): R;
    accessibilityColumnIndexRange<R = _NSRange>(): R;
    setAccessibilityColumnHeaderUIElements<R = void, P0 = unknown>(_setAccessibilityColumnHeaderUIElements: P0): R;
    accessibilityColumnHeaderUIElements<R = unknown>(): R;
    setAccessibilityColumnCount<R = void, P0 = number>(_setAccessibilityColumnCount: P0): R;
    accessibilityColumnCount<R = number>(): R;
    setAccessibilityCloseButton<R = void, P0 = unknown>(_setAccessibilityCloseButton: P0): R;
    accessibilityCloseButton<R = unknown>(): R;
    setAccessibilityClearButton<R = void, P0 = unknown>(_setAccessibilityClearButton: P0): R;
    accessibilityClearButton<R = unknown>(): R;
    setAccessibilityChildrenInNavigationOrder<R = void, P0 = unknown>(_setAccessibilityChildrenInNavigationOrder: P0): R;
    accessibilityChildrenInNavigationOrder<R = unknown>(): R;
    setAccessibilityChildren<R = void, P0 = unknown>(_setAccessibilityChildren: P0): R;
    accessibilityChildren<R = unknown>(): R;
    setAccessibilityCancelButton<R = void, P0 = unknown>(_setAccessibilityCancelButton: P0): R;
    accessibilityCancelButton<R = unknown>(): R;
    setAccessibilityAuditIssues<R = void, P0 = unknown>(_setAccessibilityAuditIssues: P0): R;
    accessibilityAuditIssues<R = unknown>(): R;
    setAccessibilityAlternateUIVisible<R = void, P0 = boolean>(_setAccessibilityAlternateUIVisible: P0): R;
    isAccessibilityAlternateUIVisible<R = boolean>(): R;
    setAccessibilityAllowedValues<R = void, P0 = unknown>(_setAccessibilityAllowedValues: P0): R;
    accessibilityAllowedValues<R = unknown>(): R;
    setAccessibilityActivationPoint<R = void, P0 = CGPoint>(_setAccessibilityActivationPoint: P0): R;
    accessibilityActivationPoint<R = CGPoint>(): R;
    setAccessibilityElement<R = void, P0 = boolean>(_setAccessibilityElement: P0): R;
    isAccessibilityElement<R = boolean>(): R;
    accessibilityAttributedStringForRange<R = unknown, P0 = _NSRange>(_accessibilityAttributedStringForRange: P0): R;
    accessibilityStringForRange<R = unknown, P0 = _NSRange>(_accessibilityStringForRange: P0): R;
    accessibilityRTFForRange<R = unknown, P0 = _NSRange>(_accessibilityRTFForRange: P0): R;
    accessibilityStyleRangeForIndex<R = _NSRange, P0 = number>(_accessibilityStyleRangeForIndex: P0): R;
    accessibilityScreenSizeForLayoutSize<R = CGSize, P0 = CGSize>(_accessibilityScreenSizeForLayoutSize: P0): R;
    accessibilityScreenPointForLayoutPoint<R = CGPoint, P0 = CGPoint>(_accessibilityScreenPointForLayoutPoint: P0): R;
    accessibilityResultsForSearchPredicate<R = unknown, P0 = unknown>(_accessibilityResultsForSearchPredicate: P0): R;
    accessibilityRangeForPosition<R = _NSRange, P0 = CGPoint>(_accessibilityRangeForPosition: P0): R;
    accessibilityRangeForLine<R = _NSRange, P0 = number>(_accessibilityRangeForLine: P0): R;
    accessibilityRangeForIndex<R = _NSRange, P0 = number>(_accessibilityRangeForIndex: P0): R;
    accessibilityLineForIndex<R = number, P0 = number>(_accessibilityLineForIndex: P0): R;
    accessibilityLayoutSizeForScreenSize<R = CGSize, P0 = CGSize>(_accessibilityLayoutSizeForScreenSize: P0): R;
    accessibilityLayoutPointForScreenPoint<R = CGPoint, P0 = CGPoint>(_accessibilityLayoutPointForScreenPoint: P0): R;
    accessibilityFrameForRange<R = CGRect, P0 = _NSRange>(_accessibilityFrameForRange: P0): R;
    accessibilityCellForColumn_row<R = unknown, P0 = number, P1 = number>(_accessibilityCellForColumn: P0, _row: P1): R;
    isAccessibilitySelectorAllowed<R = boolean, P0 = string>(_isAccessibilitySelectorAllowed: P0): R;
    validateProposedFirstResponder_forEvent<R = boolean, P0 = unknown, P1 = unknown>(_validateProposedFirstResponder: P0, _forEvent: P1): R;
    willPresentError<R = unknown, P0 = unknown>(_willPresentError: P0): R;
    presentError<R = boolean, P0 = unknown>(_presentError: P0): R;
    presentError_modalForWindow_delegate_didPresentSelector_contextInfo<R = void, P0 = unknown, P1 = unknown, P2 = unknown, P3 = string, P4 = void>(_presentError: P0, _modalForWindow: P1, _delegate: P2, _didPresentSelector: P3, _contextInfo: P4): R;
    _wantsKeyDownForEvent<R = boolean, P0 = unknown>(__wantsKeyDownForEvent: P0): R;
    _postEventNotification_fromCell<R = void, P0 = unknown, P1 = unknown>(__postEventNotification: P0, _fromCell: P1): R;
    _postEventNotification<R = void, P0 = unknown>(__postEventNotification: P0): R;
    _setShouldPostEventNotifications<R = void, P0 = boolean>(__setShouldPostEventNotifications: P0): R;
    _shouldPostEventNotifications<R = boolean>(): R;
    _noResponderFor_duringForwardingOfEvent<R = void, P0 = string, P1 = unknown>(__noResponderFor: P0, _duringForwardingOfEvent: P1): R;
    doCommandBySelector<R = void, P0 = string>(_doCommandBySelector: P0): R;
    insertText<R = void, P0 = unknown>(_insertText: P0): R;
    showContextHelp<R = void, P0 = unknown>(_showContextHelp: P0): R;
    helpRequested<R = void, P0 = unknown>(_helpRequested: P0): R;
    dealloc<R = void>(): R;
    undoManager<R = unknown>(): R;
    flushBufferedKeyEvents<R = void>(): R;
    interpretKeyEvents<R = void, P0 = unknown>(_interpretKeyEvents: P0): R;
    supplementalTargetForAction_sender<R = unknown, P0 = string, P1 = unknown>(_supplementalTargetForAction: P0, _sender: P1): R;
    _recursiveResponderThatWantsForwardedScrollEventsForAxis_intendedForSwipe<R = unknown, P0 = number, P1 = string>(__recursiveResponderThatWantsForwardedScrollEventsForAxis: P0, _intendedForSwipe: P1): R;
    _recursiveWantsForwardedScrollEventsForAxis<R = boolean, P0 = number>(__recursiveWantsForwardedScrollEventsForAxis: P0): R;
    wantsForwardedScrollEventsForAxis<R = boolean, P0 = number>(_wantsForwardedScrollEventsForAxis: P0): R;
    wantsScrollEventsForSwipeTrackingOnAxis<R = boolean, P0 = number>(_wantsScrollEventsForSwipeTrackingOnAxis: P0): R;
    wantsForwardedScrollEvents<R = boolean>(): R;
    shouldBeTreatedAsInkEvent<R = boolean, P0 = unknown>(_shouldBeTreatedAsInkEvent: P0): R;
    didResignActiveFirstResponder<R = void>(): R;
    didBecomeActiveFirstResponder<R = void>(): R;
    resignFirstResponder<R = boolean>(): R;
    becomeFirstResponder<R = boolean>(): R;
    setGestureEventMask<R = void, P0 = number>(_setGestureEventMask: P0): R;
    gestureEventMask<R = number>(): R;
    noResponderFor<R = void, P0 = string>(_noResponderFor: P0): R;
    pressureChangeWithEvent<R = void, P0 = unknown>(_pressureChangeWithEvent: P0): R;
    navigateWithEvent<R = void, P0 = unknown>(_navigateWithEvent: P0): R;
    quickLookPreviewItemsAtWindowLocation<R = void, P0 = CGPoint>(_quickLookPreviewItemsAtWindowLocation: P0): R;
    quickLookWithEvent<R = void, P0 = unknown>(_quickLookWithEvent: P0): R;
    touchesCancelledWithEvent<R = void, P0 = unknown>(_touchesCancelledWithEvent: P0): R;
    touchesEndedWithEvent<R = void, P0 = unknown>(_touchesEndedWithEvent: P0): R;
    touchesMovedWithEvent<R = void, P0 = unknown>(_touchesMovedWithEvent: P0): R;
    touchesBeganWithEvent<R = void, P0 = unknown>(_touchesBeganWithEvent: P0): R;
    _touchesCancelledWithEvent<R = void, P0 = unknown>(__touchesCancelledWithEvent: P0): R;
    _touchesEndedWithEvent<R = void, P0 = unknown>(__touchesEndedWithEvent: P0): R;
    _touchesMovedWithEvent<R = void, P0 = unknown>(__touchesMovedWithEvent: P0): R;
    _touchesBeganWithEvent<R = void, P0 = unknown>(__touchesBeganWithEvent: P0): R;
    _wantsTouchesForEvent<R = boolean, P0 = unknown>(__wantsTouchesForEvent: P0): R;
    endGestureWithEvent<R = void, P0 = unknown>(_endGestureWithEvent: P0): R;
    beginGestureWithEvent<R = void, P0 = unknown>(_beginGestureWithEvent: P0): R;
    swipeWithEvent<R = void, P0 = unknown>(_swipeWithEvent: P0): R;
    translateWithEvent<R = void, P0 = unknown>(_translateWithEvent: P0): R;
    rotateWithEvent<R = void, P0 = unknown>(_rotateWithEvent: P0): R;
    smartMagnifyWithEvent<R = void, P0 = unknown>(_smartMagnifyWithEvent: P0): R;
    magnifyWithEvent<R = void, P0 = unknown>(_magnifyWithEvent: P0): R;
    cursorUpdate<R = void, P0 = unknown>(_cursorUpdate: P0): R;
    tabletProximity<R = void, P0 = unknown>(_tabletProximity: P0): R;
    tabletPoint<R = void, P0 = unknown>(_tabletPoint: P0): R;
    flagsChanged<R = void, P0 = unknown>(_flagsChanged: P0): R;
    keyUp<R = void, P0 = unknown>(_keyUp: P0): R;
    keyDown<R = void, P0 = unknown>(_keyDown: P0): R;
    mouseExited<R = void, P0 = unknown>(_mouseExited: P0): R;
    mouseEntered<R = void, P0 = unknown>(_mouseEntered: P0): R;
    otherMouseDragged<R = void, P0 = unknown>(_otherMouseDragged: P0): R;
    rightMouseDragged<R = void, P0 = unknown>(_rightMouseDragged: P0): R;
    scrollWheel<R = void, P0 = unknown>(_scrollWheel: P0): R;
    mouseDragged<R = void, P0 = unknown>(_mouseDragged: P0): R;
    mouseMoved<R = void, P0 = unknown>(_mouseMoved: P0): R;
    otherMouseUp<R = void, P0 = unknown>(_otherMouseUp: P0): R;
    rightMouseUp<R = void, P0 = unknown>(_rightMouseUp: P0): R;
    mouseUp<R = void, P0 = unknown>(_mouseUp: P0): R;
    otherMouseDown<R = void, P0 = unknown>(_otherMouseDown: P0): R;
    rightMouseDown<R = void, P0 = unknown>(_rightMouseDown: P0): R;
    mouseDown<R = void, P0 = unknown>(_mouseDown: P0): R;
    performMnemonic<R = boolean, P0 = unknown>(_performMnemonic: P0): R;
    performKeyEquivalent<R = boolean, P0 = unknown>(_performKeyEquivalent: P0): R;
    invalidateRequestor<R = void>(): R;
    tryToPerform_with<R = boolean, P0 = string, P1 = unknown>(_tryToPerform: P0, _with: P1): R;
    _nextResponderForEvent<R = unknown, P0 = unknown>(__nextResponderForEvent: P0): R;
    colorFactory<R = unknown>(): R;
    setInterfaceStyle<R = void, P0 = number>(_setInterfaceStyle: P0): R;
    interfaceStyle<R = number>(): R;
    _eventResponderChainDescription<R = unknown>(): R;
    presentationWindowForError_originatedInWindow<R = unknown, P0 = unknown, P1 = unknown>(_presentationWindowForError: P0, _originatedInWindow: P1): R;
    _persistentUIEncodedReference<R = unknown>(): R;
    _changePersistentKeyPathObservationTo<R = void, P0 = boolean>(__changePersistentKeyPathObservationTo: P0): R;
    _recursivelyReinvalidateRestorableStateIfNecessary<R = void>(): R;
    invalidateRestorableState<R = void>(): R;
    _restorePersistentState<R = void, P0 = unknown>(__restorePersistentState: P0): R;
    _encodeObjectIntoRestorableState_forKey<R = void, P0 = unknown, P1 = unknown>(__encodeObjectIntoRestorableState: P0, _forKey: P1): R;
    restoreStateWithCoder<R = void, P0 = unknown>(_restoreStateWithCoder: P0): R;
    encodeRestorableStateWithCoder_backgroundQueue<R = void, P0 = unknown, P1 = unknown>(_encodeRestorableStateWithCoder: P0, _backgroundQueue: P1): R;
    encodeRestorableStateWithCoder<R = void, P0 = unknown>(_encodeRestorableStateWithCoder: P0): R;
    _markAsEverHavingInvalidRestorableState<R = void>(): R;
    _hasEverHadInvalidRestorableState<R = boolean>(): R;
    _hasInvalidRestorableState<R = boolean>(): R;
    _setHasInvalidRestorableState<R = void, P0 = boolean>(__setHasInvalidRestorableState: P0): R;
    _persistentUIIdentifier<R = unknown>(): R;
    _persistentUIWindowID<R = number>(): R;
    _persistentUIWindow<R = unknown>(): R;
    _copyPersistentUIChildren<R = unknown>(): R;
    makeTouchBar<R = unknown>(): R;
    ns_widgetType<R = unknown>(): R;
    menu<R = NSMenu>(): R;
    setMenu<R = void, P0 = NSMenu>(_v: P0): R;
    acceptsFirstResponder<R = boolean>(): R;
    nextResponder<R = NSResponder>(): R;
    setNextResponder<R = void, P0 = NSResponder>(_v: P0): R;
    _responderDebugDescription<R = NSString>(): R;
    userActivity<R = NSUserActivity>(): R;
    setUserActivity<R = void, P0 = NSUserActivity>(_v: P0): R;
    touchBar<R = NSTouchBar>(): R;
    setTouchBar<R = void, P0 = NSTouchBar>(_v: P0): R;
    servicesRequestor<R = NSServicesRequestor>(): R;
    additionalQuickActionItemSource<R = _NSQuickActionItemSource>(): R;
    debugDescription<R = NSString>(): R;
    description<R = NSString>(): R;
    hash<R = number>(): R;
    superclass<R = unknown>(): R;
    // + NSResponder(Chocolat): 
    followsResponder<R = boolean, P0 = unknown>(_followsResponder: P0): R;
    // + NSResponder(Chocolat):
    supportsTouchBar<R = boolean>(): R;
  }
  namespace NSResponder {
    export interface CLASS<T0 = void, T1 = void, T2 = void> extends NSObject, NSTouchBarProviderContainerProtocol, NSUIActivityProviderProtocol, NSTouchBarProviderProtocol, _NSQuickActionItemSourceProtocol, NSCodingProtocol {
      alloc<R = NSResponder>(): R;
      new: <R = NSResponder>() => R;
      initialize<R = void>(): R;
      restorableStateKeyPaths<R = unknown>(): R;
      automaticallyNotifiesObserversOfTouchBar<R = boolean>(): R;
      automaticallyNotifiesObserversOfServicesRequestor<R = boolean>(): R;
      // + NSResponder(Chocolat): 
      supportsTouchBar<R = boolean>(): R;
    }
  }
}

declare const NSResponder: cocoa.NSResponder.CLASS;
