/// <reference no-default-lib="true" />

declare namespace cocoa {
  export interface NSTextView<T0 = void, T1 = void, T2 = void> extends NSText, NSColorChangingProtocol, NSMenuItemValidationProtocol, NSUserInterfaceValidationsProtocol, NSTextInputClientProtocol, NSTextLayoutOrientationProviderProtocol, NSDraggingSourceProtocol, NSStandardKeyBindingRespondingProtocol, NSTextInputProtocol, NSAccessibilityNavigableStaticTextProtocol {
    changeLayoutOrientation<R = void, P0 = unknown>(_changeLayoutOrientation: P0): R;
    setLayoutOrientation<R = void, P0 = number>(_setLayoutOrientation: P0): R;
    visibleCharacterRanges<R = unknown>(): R;
    drawCharactersInRange_forContentView<R = void, P0 = _NSRange, P1 = unknown>(_drawCharactersInRange: P0, _forContentView: P1): R;
    rectsForCharacterRange<R = unknown, P0 = _NSRange>(_rectsForCharacterRange: P0): R;
    contentViewAtIndex_effectiveCharacterRange<R = unknown, P0 = number, P1 = _NSRange>(_contentViewAtIndex: P0, _effectiveCharacterRange: P1): R;
    allowsMultipleSelection<R = boolean>(): R;
    didReplaceCharacters<R = void>(): R;
    shouldReplaceCharactersInRanges_withStrings<R = boolean, P0 = unknown, P1 = unknown>(_shouldReplaceCharactersInRanges: P0, _withStrings: P1): R;
    firstSelectedRange<R = _NSRange>(): R;
    performTextFinderAction<R = void, P0 = unknown>(_performTextFinderAction: P0): R;
    _cancelFindIndicator<R = void>(): R;
    _textViewFinder<R = unknown>(): R;
    _updateTextFinder<R = void>(): R;
    _informTextFinderStringWillChange<R = void>(): R;
    performFindPanelAction<R = void, P0 = unknown>(_performFindPanelAction: P0): R;
    _changeToWritingDirectionAttribute<R = void, P0 = unknown>(__changeToWritingDirectionAttribute: P0): R;
    _changeToBidiControlCharacters<R = void, P0 = unknown>(__changeToBidiControlCharacters: P0): R;
    orderFrontSubstitutionsPanel<R = void, P0 = unknown>(_orderFrontSubstitutionsPanel: P0): R;
    orderFrontTablePanel<R = void, P0 = unknown>(_orderFrontTablePanel: P0): R;
    orderFrontListPanel<R = void, P0 = unknown>(_orderFrontListPanel: P0): R;
    orderFrontSpacingPanel<R = void, P0 = unknown>(_orderFrontSpacingPanel: P0): R;
    orderFrontLinkPanel<R = void, P0 = unknown>(_orderFrontLinkPanel: P0): R;
    characterIndexForInsertionAtPoint<R = number, P0 = CGPoint>(_characterIndexForInsertionAtPoint: P0): R;
    stopSpeaking<R = void, P0 = unknown>(_stopSpeaking: P0): R;
    startSpeaking<R = void, P0 = unknown>(_startSpeaking: P0): R;
    _getUndoManager<R = unknown, P0 = boolean>(__getUndoManager: P0): R;
    _characterRangeByTrimmingWhitespaceFromRange<R = _NSRange, P0 = _NSRange>(__characterRangeByTrimmingWhitespaceFromRange: P0): R;
    getMarkedText_selectedRange<R = void, P0 = unknown, P1 = _NSRange>(_getMarkedText: P0, _selectedRange: P1): R;
    unlockDocument<R = void>(): R;
    lockDocument<R = void>(): R;
    _consumeMouseEventsUntilMouseUpStartingWithEvent<R = void, P0 = unknown>(__consumeMouseEventsUntilMouseUpStartingWithEvent: P0): R;
    _characterRangeBetweenIndexes<R = _NSRange, P0 = _NSRange>(__characterRangeBetweenIndexes: P0): R;
    _shouldHavePeriodicEventsForPoint<R = boolean, P0 = CGPoint>(__shouldHavePeriodicEventsForPoint: P0): R;
    _selectedRangesByTogglingRanges_withRanges_initialCharacterIndex_granularity<R = unknown, P0 = unknown, P1 = unknown, P2 = number, P3 = number>(__selectedRangesByTogglingRanges: P0, _withRanges: P1, _initialCharacterIndex: P2, _granularity: P3): R;
    _distForGlyphLocation<R = number, P0 = number>(__distForGlyphLocation: P0): R;
    _rectangularCharacterRangesForGlyphRange_from_to_granularity<R = unknown, P0 = _NSRange, P1 = number, P2 = number, P3 = number>(__rectangularCharacterRangesForGlyphRange: P0, _from: P1, _to: P2, _granularity: P3): R;
    _resizeTable_level_range_row_heightDelta<R = void, P0 = unknown, P1 = number, P2 = _NSRange, P3 = number, P4 = number>(__resizeTable: P0, _level: P1, _range: P2, _row: P3, _heightDelta: P4): R;
    _resizeTable_level_range_column_widthDelta<R = void, P0 = unknown, P1 = number, P2 = _NSRange, P3 = number, P4 = number>(__resizeTable: P0, _level: P1, _range: P2, _column: P3, _widthDelta: P4): R;
    mouseCancelled<R = void, P0 = unknown>(_mouseCancelled: P0): R;
    __performDataDetectorViewEvent_isRightDown<R = boolean, P0 = unknown, P1 = boolean>(___performDataDetectorViewEvent: P0, _isRightDown: P1): R;
    _conditionallyRemoveDataDetectionIndicator<R = void, P0 = unknown>(__conditionallyRemoveDataDetectionIndicator: P0): R;
    _mouseExitedDataDetectionIndicator<R = void>(): R;
    _mouseInside<R = void, P0 = unknown>(__mouseInside: P0): R;
    _cellForPoint_characterIndex_level_row_column_range<R = unknown, P0 = CGPoint, P1 = number, P2 = number, P3 = number, P4 = number, P5 = _NSRange>(__cellForPoint: P0, _characterIndex: P1, _level: P2, _row: P3, _column: P4, _range: P5): R;
    _contentRectForTextBlock_glyphRange<R = CGRect, P0 = unknown, P1 = _NSRange>(__contentRectForTextBlock: P0, _glyphRange: P1): R;
    _toolTipTimer<R = void>(): R;
    _showToolTip<R = void, P0 = unknown>(__showToolTip: P0): R;
    _toolTipOwnerResignKey<R = void, P0 = unknown>(__toolTipOwnerResignKey: P0): R;
    _copyFromDataDetectionIndicator<R = void, P0 = unknown>(__copyFromDataDetectionIndicator: P0): R;
    _showDataDetectionIndicatorForRange_dataResult_windowPoint<R = void, P0 = _NSRange, P1 = unknown, P2 = CGPoint>(__showDataDetectionIndicatorForRange: P0, _dataResult: P1, _windowPoint: P2): R;
    mouseDownCanMoveWindow<R = boolean>(): R;
    clickedOnLink_atIndex<R = void, P0 = unknown, P1 = number>(_clickedOnLink: P0, _atIndex: P1): R;
    acceptsFirstResponder<R = boolean>(): R;
    _attachmentAtGlyphIndex_containsWindowPoint<R = boolean, P0 = number, P1 = CGPoint>(__attachmentAtGlyphIndex: P0, _containsWindowPoint: P1): R;
    setLayer<R = void, P0 = unknown>(_setLayer: P0): R;
    _renderingColorForDocumentColor<R = unknown, P0 = unknown>(__renderingColorForDocumentColor: P0): R;
    documentColorForRenderingColor<R = unknown, P0 = unknown>(_documentColorForRenderingColor: P0): R;
    renderingColorForDocumentColor<R = unknown, P0 = unknown>(_renderingColorForDocumentColor: P0): R;
    _updateDarkEffectiveAppearanceFlagWithAppearance<R = void, P0 = unknown>(__updateDarkEffectiveAppearanceFlagWithAppearance: P0): R;
    drawBackgroundOverhangInRect<R = void, P0 = CGRect>(_drawBackgroundOverhangInRect: P0): R;
    drawViewBackgroundInRect<R = void, P0 = CGRect>(_drawViewBackgroundInRect: P0): R;
    _showParagraphDirectionalityForGlyphRange_atPoint<R = void, P0 = _NSRange, P1 = CGPoint>(__showParagraphDirectionalityForGlyphRange: P0, _atPoint: P1): R;
    _showAllInsertionPointsForGlyphRange_atPoint<R = void, P0 = _NSRange, P1 = CGPoint>(__showAllInsertionPointsForGlyphRange: P0, _atPoint: P1): R;
    _extendedGlyphRangeForRange_maxGlyphIndex_drawingToScreen<R = _NSRange, P0 = _NSRange, P1 = number, P2 = boolean>(__extendedGlyphRangeForRange: P0, _maxGlyphIndex: P1, _drawingToScreen: P2): R;
    _checkRotatedOrScaledFromBase<R = void>(): R;
    _createTrackingArea<R = void>(): R;
    isOpaque<R = boolean>(): R;
    isFlipped<R = boolean>(): R;
    _lookUpIndefiniteRangeInDictionaryFromMenu<R = void, P0 = unknown>(__lookUpIndefiniteRangeInDictionaryFromMenu: P0): R;
    _lookUpDefiniteRangeInDictionaryFromMenu<R = void, P0 = unknown>(__lookUpDefiniteRangeInDictionaryFromMenu: P0): R;
    _definitionAnimationControllerForAttributedString_range_options_baselineOriginProvider<R = unknown, P0 = unknown, P1 = _NSRange, P2 = unknown, P3 = CDUnknownBlockType>(__definitionAnimationControllerForAttributedString: P0, _range: P1, _options: P2, _baselineOriginProvider: P3): R;
    _showDefinitionForAttributedString_characterIndex_range_options_baselineOriginProvider<R = void, P0 = unknown, P1 = number, P2 = _NSRange, P3 = unknown, P4 = CDUnknownBlockType>(__showDefinitionForAttributedString: P0, _characterIndex: P1, _range: P2, _options: P3, _baselineOriginProvider: P4): R;
    _lookUpClose<R = void, P0 = unknown>(__lookUpClose: P0): R;
    _dataDetectionResultForCharacterIndex_inRange<R = unknown, P0 = number, P1 = _NSRange>(__dataDetectionResultForCharacterIndex: P0, _inRange: P1): R;
    _searchWithGoogleFromMenu<R = void, P0 = unknown>(__searchWithGoogleFromMenu: P0): R;
    _restoreReplacedString<R = void, P0 = unknown>(__restoreReplacedString: P0): R;
    _makeLinkFromMenu<R = void, P0 = unknown>(__makeLinkFromMenu: P0): R;
    _removeLinkFromMenu<R = void, P0 = unknown>(__removeLinkFromMenu: P0): R;
    _openLinkFromMenu<R = void, P0 = unknown>(__openLinkFromMenu: P0): R;
    spellCheckerDidChangeDashSubstitution<R = void, P0 = unknown>(_spellCheckerDidChangeDashSubstitution: P0): R;
    spellCheckerDidChangeQuoteSubstitution<R = void, P0 = unknown>(_spellCheckerDidChangeQuoteSubstitution: P0): R;
    spellCheckerDidChangeReplacement<R = void, P0 = unknown>(_spellCheckerDidChangeReplacement: P0): R;
    spellCheckerDidChangeCorrection<R = void, P0 = unknown>(_spellCheckerDidChangeCorrection: P0): R;
    spellCheckerDidChangeLanguage<R = void, P0 = unknown>(_spellCheckerDidChangeLanguage: P0): R;
    spellCheckerDidUnlearnWord<R = void, P0 = unknown>(_spellCheckerDidUnlearnWord: P0): R;
    spellCheckerDidLearnWord<R = void, P0 = unknown>(_spellCheckerDidLearnWord: P0): R;
    _turnOnTextReplacementFromMenu<R = void, P0 = unknown>(__turnOnTextReplacementFromMenu: P0): R;
    _replaceTextFromMenu<R = void, P0 = unknown>(__replaceTextFromMenu: P0): R;
    _turnOnSpellingCorrectionFromMenu<R = void, P0 = unknown>(__turnOnSpellingCorrectionFromMenu: P0): R;
    _forgetSpellingFromMenu<R = void, P0 = unknown>(__forgetSpellingFromMenu: P0): R;
    _unlearnSpellingFromMenu<R = void, P0 = unknown>(__unlearnSpellingFromMenu: P0): R;
    _learnSpellingFromMenu<R = void, P0 = unknown>(__learnSpellingFromMenu: P0): R;
    _ignoreGrammarFromMenu<R = void, P0 = unknown>(__ignoreGrammarFromMenu: P0): R;
    _ignoreSpellingFromMenu<R = void, P0 = unknown>(__ignoreSpellingFromMenu: P0): R;
    _changeAlternativesFromMenu<R = void, P0 = unknown>(__changeAlternativesFromMenu: P0): R;
    _changeSpellingFromMenu<R = void, P0 = unknown>(__changeSpellingFromMenu: P0): R;
    _changeSpellingToWord<R = void, P0 = unknown>(__changeSpellingToWord: P0): R;
    _checkSpelling<R = void, P0 = boolean>(__checkSpelling: P0): R;
    _checkGrammarStartingAt_detailRange_detail<R = _NSRange, P0 = number, P1 = _NSRange, P2 = unknown>(__checkGrammarStartingAt: P0, _detailRange: P1, _detail: P2): R;
    _modifiedGrammarRangeForRange_details<R = _NSRange, P0 = _NSRange, P1 = unknown>(__modifiedGrammarRangeForRange: P0, _details: P1): R;
    outline<R = void, P0 = unknown>(_outline: P0): R;
    changeBaseWritingDirection<R = void, P0 = unknown>(_changeBaseWritingDirection: P0): R;
    toggleBaseWritingDirection<R = void, P0 = unknown>(_toggleBaseWritingDirection: P0): R;
    alignJustified<R = void, P0 = unknown>(_alignJustified: P0): R;
    changeDocumentBackgroundColor<R = void, P0 = unknown>(_changeDocumentBackgroundColor: P0): R;
    changeAttributes<R = void, P0 = unknown>(_changeAttributes: P0): R;
    _convertAttributesByMappingRenderingColor_converter<R = unknown, P0 = unknown, P1 = CDUnknownBlockType>(__convertAttributesByMappingRenderingColor: P0, _converter: P1): R;
    setVerticallyResizable<R = void, P0 = boolean>(_setVerticallyResizable: P0): R;
    isVerticallyResizable<R = boolean>(): R;
    setHorizontallyResizable<R = void, P0 = boolean>(_setHorizontallyResizable: P0): R;
    isHorizontallyResizable<R = boolean>(): R;
    setMinSize<R = void, P0 = CGSize>(_setMinSize: P0): R;
    minSize<R = CGSize>(): R;
    setMaxSize<R = void, P0 = CGSize>(_setMaxSize: P0): R;
    maxSize<R = CGSize>(): R;
    setBaseWritingDirection<R = void, P0 = number>(_setBaseWritingDirection: P0): R;
    baseWritingDirection<R = number>(): R;
    alignment<R = number>(): R;
    setAlignment<R = void, P0 = number>(_setAlignment: P0): R;
    textColor<R = unknown>(): R;
    setTextColor<R = void, P0 = unknown>(_setTextColor: P0): R;
    font<R = unknown>(): R;
    setFont<R = void, P0 = unknown>(_setFont: P0): R;
    performValidatedReplacementInRange_withAttributedString<R = boolean, P0 = _NSRange, P1 = unknown>(_performValidatedReplacementInRange: P0, _withAttributedString: P1): R;
    setString<R = void, P0 = unknown>(_setString: P0): R;
    string<R = unknown>(): R;
    selectionRangeForProposedRange_granularity<R = _NSRange, P0 = _NSRange, P1 = number>(_selectionRangeForProposedRange: P0, _granularity: P1): R;
    _requestUpdateOfDragTypeRegistration<R = void>(): R;
    updateDragTypeRegistration<R = void>(): R;
    updateSpellingPanel<R = void>(): R;
    updateInspectorBar<R = void>(): R;
    _currentEditingColor<R = unknown>(): R;
    updateFontPanel<R = void>(): R;
    _renderingAttributesForDocumentAttributes<R = unknown, P0 = unknown>(__renderingAttributesForDocumentAttributes: P0): R;
    updateRuler<R = void>(): R;
    drawInsertionPointInRect_color_turnedOn<R = void, P0 = CGRect, P1 = unknown, P2 = boolean>(_drawInsertionPointInRect: P0, _color: P1, _turnedOn: P2): R;
    _drawInsertionPointInRect_color<R = void, P0 = CGRect, P1 = unknown>(__drawInsertionPointInRect: P0, _color: P1): R;
    setNeedsDisplayInRect_avoidAdditionalLayout<R = void, P0 = CGRect, P1 = boolean>(_setNeedsDisplayInRect: P0, _avoidAdditionalLayout: P1): R;
    inspectorBarItemIdentifiers<R = unknown>(): R;
    rulerView_pointForLocation<R = CGPoint, P0 = unknown, P1 = number>(_rulerView: P0, _pointForLocation: P1): R;
    rulerView_locationForPoint<R = number, P0 = unknown, P1 = CGPoint>(_rulerView: P0, _locationForPoint: P1): R;
    rulerView_willSetClientView<R = void, P0 = unknown, P1 = unknown>(_rulerView: P0, _willSetClientView: P1): R;
    rulerView_handleMouseDown<R = void, P0 = unknown, P1 = unknown>(_rulerView: P0, _handleMouseDown: P1): R;
    rulerView_handleMouseDown_forMarker<R = boolean, P0 = unknown, P1 = unknown, P2 = unknown>(_rulerView: P0, _handleMouseDown: P1, _forMarker: P2): R;
    rulerView_willAddMarker_atLocation<R = number, P0 = unknown, P1 = unknown, P2 = number>(_rulerView: P0, _willAddMarker: P1, _atLocation: P2): R;
    rulerView_willMoveMarker_toLocation<R = number, P0 = unknown, P1 = unknown, P2 = number>(_rulerView: P0, _willMoveMarker: P1, _toLocation: P2): R;
    rulerView_shouldAddMarker<R = boolean, P0 = unknown, P1 = unknown>(_rulerView: P0, _shouldAddMarker: P1): R;
    rulerView_shouldRemoveMarker<R = boolean, P0 = unknown, P1 = unknown>(_rulerView: P0, _shouldRemoveMarker: P1): R;
    rulerView_shouldMoveMarker<R = boolean, P0 = unknown, P1 = unknown>(_rulerView: P0, _shouldMoveMarker: P1): R;
    rulerView_didAddMarker<R = void, P0 = unknown, P1 = unknown>(_rulerView: P0, _didAddMarker: P1): R;
    rulerView_didRemoveMarker<R = void, P0 = unknown, P1 = unknown>(_rulerView: P0, _didRemoveMarker: P1): R;
    rulerView_didMoveMarker<R = void, P0 = unknown, P1 = unknown>(_rulerView: P0, _didMoveMarker: P1): R;
    toggleTraditionalCharacterShape<R = void, P0 = unknown>(_toggleTraditionalCharacterShape: P0): R;
    lowerBaseline<R = void, P0 = unknown>(_lowerBaseline: P0): R;
    raiseBaseline<R = void, P0 = unknown>(_raiseBaseline: P0): R;
    useAllLigatures<R = void, P0 = unknown>(_useAllLigatures: P0): R;
    useStandardLigatures<R = void, P0 = unknown>(_useStandardLigatures: P0): R;
    turnOffLigatures<R = void, P0 = unknown>(_turnOffLigatures: P0): R;
    useStandardKerning<R = void, P0 = unknown>(_useStandardKerning: P0): R;
    loosenKerning<R = void, P0 = unknown>(_loosenKerning: P0): R;
    tightenKerning<R = void, P0 = unknown>(_tightenKerning: P0): R;
    turnOffKerning<R = void, P0 = unknown>(_turnOffKerning: P0): R;
    removeAccents<R = void, P0 = unknown>(_removeAccents: P0): R;
    transliterateToLatin<R = void, P0 = unknown>(_transliterateToLatin: P0): R;
    setBaseWritingDirection_range<R = void, P0 = number, P1 = _NSRange>(_setBaseWritingDirection: P0, _range: P1): R;
    setAlignment_range<R = void, P0 = number, P1 = _NSRange>(_setAlignment: P0, _range: P1): R;
    setConstrainedFrameSize<R = void, P0 = CGSize>(_setConstrainedFrameSize: P0): R;
    _writingDirectionAttributeForPeriodBeforeInsertText_replacementRange<R = unknown, P0 = unknown, P1 = _NSRange>(__writingDirectionAttributeForPeriodBeforeInsertText: P0, _replacementRange: P1): R;
    _writingDirectionAttributeForInsertText_replacementRange<R = unknown, P0 = unknown, P1 = _NSRange>(__writingDirectionAttributeForInsertText: P0, _replacementRange: P1): R;
    inputContext<R = unknown>(): R;
    handleTextCheckingResults_forRange_types_options_orthography_wordCount<R = void, P0 = unknown, P1 = _NSRange, P2 = number, P3 = unknown, P4 = unknown, P5 = number>(_handleTextCheckingResults: P0, _forRange: P1, _types: P2, _options: P3, _orthography: P4, _wordCount: P5): R;
    _noteUndoOfCorrections<R = void, P0 = unknown>(__noteUndoOfCorrections: P0): R;
    _handleTextCheckingResults_sequenceNumber_forRange_types_options_orthography_wordCount_applyNow_checkSynchronously<R = void, P0 = unknown, P1 = number, P2 = _NSRange, P3 = number, P4 = unknown, P5 = unknown, P6 = number, P7 = boolean, P8 = boolean>(__handleTextCheckingResults: P0, _sequenceNumber: P1, _forRange: P2, _types: P3, _options: P4, _orthography: P5, _wordCount: P6, _applyNow: P7, _checkSynchronously: P8): R;
    checkTextInDocument<R = void, P0 = unknown>(_checkTextInDocument: P0): R;
    checkTextInSelection<R = void, P0 = unknown>(_checkTextInSelection: P0): R;
    replaceTextInSelection<R = void, P0 = unknown>(_replaceTextInSelection: P0): R;
    addLinksInSelection<R = void, P0 = unknown>(_addLinksInSelection: P0): R;
    replaceDashesInSelection<R = void, P0 = unknown>(_replaceDashesInSelection: P0): R;
    replaceQuotesInSelection<R = void, P0 = unknown>(_replaceQuotesInSelection: P0): R;
    checkTextInDocumentUsingTypes_options_restrictToSelection<R = void, P0 = number, P1 = unknown, P2 = boolean>(_checkTextInDocumentUsingTypes: P0, _options: P1, _restrictToSelection: P2): R;
    checkTextInRange_types_options<R = void, P0 = _NSRange, P1 = number, P2 = unknown>(_checkTextInRange: P0, _types: P1, _options: P2): R;
    substituteQuotesForRange<R = void, P0 = _NSRange>(_substituteQuotesForRange: P0): R;
    _checkLinksAfterChange<R = void>(): R;
    _checkLinksForRange_excludingRange<R = void, P0 = _NSRange, P1 = _NSRange>(__checkLinksForRange: P0, _excludingRange: P1): R;
    _deferConsiderationOfTextCheckingForRange<R = void, P0 = _NSRange>(__deferConsiderationOfTextCheckingForRange: P0): R;
    _considerDeferredTextChecking<R = void>(): R;
    _considerTextCheckingForRange<R = void, P0 = _NSRange>(__considerTextCheckingForRange: P0): R;
    _scheduleTextCheckingForRange<R = void, P0 = _NSRange>(__scheduleTextCheckingForRange: P0): R;
    _performScheduledTextChecking<R = void, P0 = boolean>(__performScheduledTextChecking: P0): R;
    _markAllForTextChecking<R = void>(): R;
    _markForTextCheckingAfterChange<R = void>(): R;
    _markTextEditedForRange<R = void, P0 = _NSRange>(__markTextEditedForRange: P0): R;
    _unmarkTextEditedForRange<R = void, P0 = _NSRange>(__unmarkTextEditedForRange: P0): R;
    _checkSpellingForRange_excludingRange<R = void, P0 = _NSRange, P1 = _NSRange>(__checkSpellingForRange: P0, _excludingRange: P1): R;
    _verifyQuotesAndParenthesesForRange<R = void, P0 = _NSRange>(__verifyQuotesAndParenthesesForRange: P0): R;
    _clearSpellingForRange<R = void, P0 = _NSRange>(__clearSpellingForRange: P0): R;
    _useTextChecking<R = boolean>(): R;
    _rangeByTrimmingWhitespaceFromRange<R = _NSRange, P0 = _NSRange>(__rangeByTrimmingWhitespaceFromRange: P0): R;
    _spellingSelectionRangeForProposedRange<R = _NSRange, P0 = _NSRange>(__spellingSelectionRangeForProposedRange: P0): R;
    _doubleClickAtIndex_limitedRangeOK<R = _NSRange, P0 = number, P1 = boolean>(__doubleClickAtIndex: P0, _limitedRangeOK: P1): R;
    _spellingGuessesForWord_range<R = unknown, P0 = unknown, P1 = _NSRange>(__spellingGuessesForWord: P0, _range: P1): R;
    _spellingGuessesForRange<R = unknown, P0 = _NSRange>(__spellingGuessesForRange: P0): R;
    _spellingGuessesForRange_canCorrect<R = unknown, P0 = _NSRange, P1 = string>(__spellingGuessesForRange: P0, _canCorrect: P1): R;
    _canUnlearnSpellingForRange<R = boolean, P0 = _NSRange>(__canUnlearnSpellingForRange: P0): R;
    _mightHaveSpellingAttributes<R = boolean>(): R;
    _removeGrammarAttributeForRange<R = void, P0 = _NSRange>(__removeGrammarAttributeForRange: P0): R;
    _removeGrammarAttributeForRange_includeAccessibility<R = void, P0 = _NSRange, P1 = boolean>(__removeGrammarAttributeForRange: P0, _includeAccessibility: P1): R;
    _removeSpellingAttributeForRange<R = void, P0 = _NSRange>(__removeSpellingAttributeForRange: P0): R;
    _removeSpellingAttributeForRange_includeAccessibility<R = void, P0 = _NSRange, P1 = boolean>(__removeSpellingAttributeForRange: P0, _includeAccessibility: P1): R;
    _addGrammarAttributesForRange_details<R = void, P0 = _NSRange, P1 = unknown>(__addGrammarAttributesForRange: P0, _details: P1): R;
    _addGrammarAttributesForRange_detailRange_detail<R = void, P0 = _NSRange, P1 = _NSRange, P2 = unknown>(__addGrammarAttributesForRange: P0, _detailRange: P1, _detail: P2): R;
    _addSpellingAttributeForRange<R = void, P0 = _NSRange>(__addSpellingAttributeForRange: P0): R;
    invalidateTextContainerOrigin<R = void>(): R;
    replaceTextContainer<R = void, P0 = unknown>(_replaceTextContainer: P0): R;
    _selectedRangesAsIndexSet<R = unknown>(): R;
    _removeAutiliaryUserInterfaceItems<R = void>(): R;
    _removeSelectionRolloverTimer<R = void>(): R;
    _removeDataDetectionIndicator<R = void>(): R;
    _removeToolTipAndTimer<R = void>(): R;
    _isDeallocating<R = boolean>(): R;
    _tryRetain<R = boolean>(): R;
    initWithFrame_textContainer<R = unknown, P0 = CGRect, P1 = unknown>(_initWithFrame: P0, _textContainer: P1): R;
    _isAccessibilityContentSectionCandidate<R = boolean>(): R;
    accessibilityIsTextInputMarkedRangeAttributeSettable<R = boolean>(): R;
    accessibilityTextInputMarkedRangeAttribute<R = unknown>(): R;
    accessibilityPerformShowMenuOfChild<R = boolean, P0 = unknown>(_accessibilityPerformShowMenuOfChild: P0): R;
    accessibilitySizeOfChild<R = unknown, P0 = unknown>(_accessibilitySizeOfChild: P0): R;
    accessibilityPositionOfChild<R = unknown, P0 = unknown>(_accessibilityPositionOfChild: P0): R;
    _accessibilityBoundsOfChild<R = CGRect, P0 = unknown>(__accessibilityBoundsOfChild: P0): R;
    _accessibilityCharacterRangeOfChild<R = _NSRange, P0 = unknown>(__accessibilityCharacterRangeOfChild: P0): R;
    _accessibilityAttachmentCellForChild<R = unknown, P0 = unknown>(__accessibilityAttachmentCellForChild: P0): R;
    accessibilityFocusRingBoundsForBounds<R = CGRect, P0 = CGRect>(_accessibilityFocusRingBoundsForBounds: P0): R;
    accessibilitySetFocus_forChild<R = void, P0 = unknown, P1 = unknown>(_accessibilitySetFocus: P0, _forChild: P1): R;
    accessibilityIsChildFocusable<R = boolean, P0 = unknown>(_accessibilityIsChildFocusable: P0): R;
    accessibilityHelpStringForChild<R = unknown, P0 = unknown>(_accessibilityHelpStringForChild: P0): R;
    accessibilityStyleRangeForIndexAttributeForParameter<R = unknown, P0 = unknown>(_accessibilityStyleRangeForIndexAttributeForParameter: P0): R;
    accessibilityAttributedStringForRangeAttributeForParameter<R = unknown, P0 = unknown>(_accessibilityAttributedStringForRangeAttributeForParameter: P0): R;
    accessibilitySharedTextElementForIndexAttributeForParameter<R = unknown, P0 = unknown>(_accessibilitySharedTextElementForIndexAttributeForParameter: P0): R;
    accessibilityRTFForRangeAttributeForParameter<R = unknown, P0 = unknown>(_accessibilityRTFForRangeAttributeForParameter: P0): R;
    accessibilityBoundsForRangeAttributeForParameter<R = unknown, P0 = unknown>(_accessibilityBoundsForRangeAttributeForParameter: P0): R;
    accessibilityRangeForIndexAttributeForParameter<R = unknown, P0 = unknown>(_accessibilityRangeForIndexAttributeForParameter: P0): R;
    accessibilityRangeForPositionAttributeForParameter<R = unknown, P0 = unknown>(_accessibilityRangeForPositionAttributeForParameter: P0): R;
    accessibilityStringForRangeAttributeForParameter<R = unknown, P0 = unknown>(_accessibilityStringForRangeAttributeForParameter: P0): R;
    accessibilityRangeForLineAttributeForParameter<R = unknown, P0 = unknown>(_accessibilityRangeForLineAttributeForParameter: P0): R;
    accessibilityLineForIndexAttributeForParameter<R = unknown, P0 = unknown>(_accessibilityLineForIndexAttributeForParameter: P0): R;
    accessibilityIsInsertionPointLineNumberAttributeSettable<R = boolean>(): R;
    accessibilityInsertionPointLineNumberAttribute<R = unknown>(): R;
    accessibilityIsSharedCharacterRangeAttributeSettable<R = boolean>(): R;
    accessibilitySharedCharacterRangeAttribute<R = unknown>(): R;
    accessibilityIsSharedTextUIElementsAttributeSettable<R = boolean>(): R;
    accessibilitySharedTextUIElementsAttribute<R = unknown>(): R;
    accessibilitySetVisibleCharacterRangeAttribute<R = void, P0 = unknown>(_accessibilitySetVisibleCharacterRangeAttribute: P0): R;
    accessibilityIsVisibleCharacterRangeAttributeSettable<R = boolean>(): R;
    accessibilityVisibleCharacterRangeAttribute<R = unknown>(): R;
    accessibilityIsNumberOfCharactersAttributeSettable<R = boolean>(): R;
    accessibilityNumberOfCharactersAttribute<R = unknown>(): R;
    accessibilitySetSelectedTextRangesAttribute<R = void, P0 = unknown>(_accessibilitySetSelectedTextRangesAttribute: P0): R;
    accessibilityIsSelectedTextRangesAttributeSettable<R = boolean>(): R;
    accessibilitySelectedTextRangesAttribute<R = unknown>(): R;
    accessibilitySetSelectedTextRangeAttribute<R = void, P0 = unknown>(_accessibilitySetSelectedTextRangeAttribute: P0): R;
    accessibilityIsSelectedTextRangeAttributeSettable<R = boolean>(): R;
    accessibilitySelectedTextRangeAttribute<R = unknown>(): R;
    accessibilitySetSelectedTextAttribute<R = void, P0 = unknown>(_accessibilitySetSelectedTextAttribute: P0): R;
    accessibilityIsSelectedTextAttributeSettable<R = boolean>(): R;
    accessibilitySelectedTextAttribute<R = unknown>(): R;
    accessibilitySetValueAttribute<R = void, P0 = unknown>(_accessibilitySetValueAttribute: P0): R;
    accessibilityIsValueAttributeSettable<R = boolean>(): R;
    accessibilityParameterizedAttributeNames<R = unknown>(): R;
    accessibilityElementForAttachment<R = unknown, P0 = unknown>(_accessibilityElementForAttachment: P0): R;
    draggedImage_endedAt_operation<R = void, P0 = unknown, P1 = CGPoint, P2 = number>(_draggedImage: P0, _endedAt: P1, _operation: P2): R;
    _draggingSession_endedAtPoint_operation<R = void, P0 = unknown, P1 = CGPoint, P2 = number>(__draggingSession: P0, _endedAtPoint: P1, _operation: P2): R;
    dragSelectionWithEvent_offset_slideBack<R = boolean, P0 = unknown, P1 = CGSize, P2 = boolean>(_dragSelectionWithEvent: P0, _offset: P1, _slideBack: P2): R;
    dragImageForSelectionWithEvent_origin<R = unknown, P0 = unknown, P1 = CGPoint>(_dragImageForSelectionWithEvent: P0, _origin: P1): R;
    draggingSourceOperationMaskForLocal<R = number, P0 = boolean>(_draggingSourceOperationMaskForLocal: P0): R;
    dragOperationForDraggingInfo_type<R = number, P0 = unknown, P1 = unknown>(_dragOperationForDraggingInfo: P0, _type: P1): R;
    _fixDragAndDropCharRangesForChangeInRanges_replacementStrings<R = void, P0 = unknown, P1 = unknown>(__fixDragAndDropCharRangesForChangeInRanges: P0, _replacementStrings: P1): R;
    _setDragAndDropCharRanges<R = void, P0 = unknown>(__setDragAndDropCharRanges: P0): R;
    _setDragAndDropCharRange<R = void, P0 = _NSRange>(__setDragAndDropCharRange: P0): R;
    _forceRedrawDragInsertionIndicator<R = void>(): R;
    cleanUpAfterDragOperation<R = void>(): R;
    _pointForTopOfBeginningOfCharRange<R = CGPoint, P0 = _NSRange>(__pointForTopOfBeginningOfCharRange: P0): R;
    _updateDragInsertionIndicatorWith<R = void, P0 = CGRect>(__updateDragInsertionIndicatorWith: P0): R;
    drawDragInsertionIndicatorWithRect<R = void, P0 = CGRect>(_drawDragInsertionIndicatorWithRect: P0): R;
    _insertionGlyphIndexForDrag<R = number, P0 = unknown>(__insertionGlyphIndexForDrag: P0): R;
    _insertionCharacterIndexForDrag<R = number, P0 = unknown>(__insertionCharacterIndexForDrag: P0): R;
    insertTable<R = void, P0 = unknown>(_insertTable: P0): R;
    yankAndSelect<R = void, P0 = unknown>(_yankAndSelect: P0): R;
    _moveDownAndModifySelection<R = void, P0 = number>(__moveDownAndModifySelection: P0): R;
    _moveUpAndModifySelection<R = void, P0 = number>(__moveUpAndModifySelection: P0): R;
    _characterRangesBetweenIndex_andIndex<R = unknown, P0 = number, P1 = number>(__characterRangesBetweenIndex: P0, _andIndex: P1): R;
    spotlight<R = void, P0 = unknown>(_spotlight: P0): R;
    insertCompletion_forPartialWordRange_movement_isFinal<R = void, P0 = unknown, P1 = _NSRange, P2 = number, P3 = boolean>(_insertCompletion: P0, _forPartialWordRange: P1, _movement: P2, _isFinal: P3): R;
    completionsForPartialWordRange_indexOfSelectedItem<R = unknown, P0 = _NSRange, P1 = number>(_completionsForPartialWordRange: P0, _indexOfSelectedItem: P1): R;
    _completionsFromDocumentForPartialWordRange<R = unknown, P0 = _NSRange>(__completionsFromDocumentForPartialWordRange: P0): R;
    _completionsFromDocumentForPartialWordRange_language<R = unknown, P0 = _NSRange, P1 = unknown>(__completionsFromDocumentForPartialWordRange: P0, _language: P1): R;
    rangeForUserCompletion<R = _NSRange>(): R;
    convertToHalfWidth<R = void, P0 = unknown>(_convertToHalfWidth: P0): R;
    convertToFullWidth<R = void, P0 = unknown>(_convertToFullWidth: P0): R;
    convertToTraditionalChinese<R = void, P0 = unknown>(_convertToTraditionalChinese: P0): R;
    convertToSimplifiedChinese<R = void, P0 = unknown>(_convertToSimplifiedChinese: P0): R;
    insertRightToLeftSlash<R = void, P0 = unknown>(_insertRightToLeftSlash: P0): R;
    insertPageBreak<R = void, P0 = unknown>(_insertPageBreak: P0): R;
    insertLineSeparator<R = void, P0 = unknown>(_insertLineSeparator: P0): R;
    _moveToPreviousBlock<R = void>(): R;
    _moveToNextBlock<R = void>(): R;
    _unnestListAtIndex_markerRange<R = void, P0 = number, P1 = _NSRange>(__unnestListAtIndex: P0, _markerRange: P1): R;
    _nestListAtIndex<R = void, P0 = number>(__nestListAtIndex: P0): R;
    _reformListAtIndex<R = void, P0 = number>(__reformListAtIndex: P0): R;
    _checkInList_listStart_markerRange_emptyItem_atEnd_inBlock_blockStart<R = void, P0 = string, P1 = string, P2 = _NSRange, P3 = string, P4 = string, P5 = string, P6 = string>(__checkInList: P0, _listStart: P1, _markerRange: P2, _emptyItem: P3, _atEnd: P4, _inBlock: P5, _blockStart: P6): R;
    _checkInList_listStart_markerRange_emptyItem_atEnd_inBlock_blockStart_forCharacterRange<R = void, P0 = string, P1 = string, P2 = _NSRange, P3 = string, P4 = string, P5 = string, P6 = string, P7 = _NSRange>(__checkInList: P0, _listStart: P1, _markerRange: P2, _emptyItem: P3, _atEnd: P4, _inBlock: P5, _blockStart: P6, _forCharacterRange: P7): R;
    _moveDown<R = void, P0 = number>(__moveDown: P0): R;
    _moveUp<R = void, P0 = number>(__moveUp: P0): R;
    _characterIndexForMoveLeftFromSelectedRanges<R = number, P0 = unknown>(__characterIndexForMoveLeftFromSelectedRanges: P0): R;
    _characterIndexForMoveRightFromSelectedRanges<R = number, P0 = unknown>(__characterIndexForMoveRightFromSelectedRanges: P0): R;
    _characterIndexForMoveBackwardFromSelectedRanges<R = number, P0 = unknown>(__characterIndexForMoveBackwardFromSelectedRanges: P0): R;
    _characterIndexForMoveForwardFromSelectedRanges<R = number, P0 = unknown>(__characterIndexForMoveForwardFromSelectedRanges: P0): R;
    _characterIndexForMoveWordLeftFromCharacterIndex<R = number, P0 = number>(__characterIndexForMoveWordLeftFromCharacterIndex: P0): R;
    _characterIndexForMoveWordRightFromCharacterIndex<R = number, P0 = number>(__characterIndexForMoveWordRightFromCharacterIndex: P0): R;
    _characterIndexForMoveLeftFromCharacterIndex<R = number, P0 = number>(__characterIndexForMoveLeftFromCharacterIndex: P0): R;
    _characterIndexForMoveRightFromCharacterIndex<R = number, P0 = number>(__characterIndexForMoveRightFromCharacterIndex: P0): R;
    _characterIndexForMoveBackwardFromCharacterIndex<R = number, P0 = number>(__characterIndexForMoveBackwardFromCharacterIndex: P0): R;
    _characterIndexForMoveForwardFromCharacterIndex<R = number, P0 = number>(__characterIndexForMoveForwardFromCharacterIndex: P0): R;
    _scrollDown<R = void, P0 = number>(__scrollDown: P0): R;
    _scrollUp<R = void, P0 = number>(__scrollUp: P0): R;
    _rangeForMoveDownFromRange_verticalDistance_desiredDistanceIntoContainer_selectionAffinity<R = _NSRange, P0 = _NSRange, P1 = number, P2 = number, P3 = number>(__rangeForMoveDownFromRange: P0, _verticalDistance: P1, _desiredDistanceIntoContainer: P2, _selectionAffinity: P3): R;
    _rangeForMoveUpFromRange_verticalDistance_desiredDistanceIntoContainer_selectionAffinity<R = _NSRange, P0 = _NSRange, P1 = number, P2 = number, P3 = number>(__rangeForMoveUpFromRange: P0, _verticalDistance: P1, _desiredDistanceIntoContainer: P2, _selectionAffinity: P3): R;
    _verticalDistanceForLineScroll<R = number>(): R;
    _verticalDistanceForPageScroll<R = number>(): R;
    _accessibilityTextViewCompletionWindow<R = unknown>(): R;
    pasteAsRichText<R = void, P0 = unknown>(_pasteAsRichText: P0): R;
    pasteAsPlainText<R = void, P0 = unknown>(_pasteAsPlainText: P0): R;
    copyLink<R = void, P0 = unknown>(_copyLink: P0): R;
    readSelectionFromPasteboard<R = boolean, P0 = unknown>(_readSelectionFromPasteboard: P0): R;
    _readSelectionFromPasteboard_types<R = boolean, P0 = unknown, P1 = unknown>(__readSelectionFromPasteboard: P0, _types: P1): R;
    _wantsPastedURL_allowFileURLs<R = boolean, P0 = unknown, P1 = boolean>(__wantsPastedURL: P0, _allowFileURLs: P1): R;
    _wantsPastedFiles<R = boolean, P0 = unknown>(__wantsPastedFiles: P0): R;
    _wantsPastedFile<R = boolean, P0 = unknown>(__wantsPastedFile: P0): R;
    readSelectionFromPasteboard_type<R = boolean, P0 = unknown, P1 = unknown>(_readSelectionFromPasteboard: P0, _type: P1): R;
    _readMovieIntoRange_fromPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__readMovieIntoRange: P0, _fromPasteboard: P1): R;
    _readImageIntoRange_fromPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__readImageIntoRange: P0, _fromPasteboard: P1): R;
    _readURLStringsWithNamesIntoRange_fromPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__readURLStringsWithNamesIntoRange: P0, _fromPasteboard: P1): R;
    _readURLStringIntoRange_fromPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__readURLStringIntoRange: P0, _fromPasteboard: P1): R;
    _readURLIntoRange_fromPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__readURLIntoRange: P0, _fromPasteboard: P1): R;
    _readRulerIntoRange_fromPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__readRulerIntoRange: P0, _fromPasteboard: P1): R;
    _readRulerIntoRanges_fromPasteboard<R = boolean, P0 = unknown, P1 = unknown>(__readRulerIntoRanges: P0, _fromPasteboard: P1): R;
    _readFontIntoRange_fromPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__readFontIntoRange: P0, _fromPasteboard: P1): R;
    _readFontIntoRanges_fromPasteboard<R = boolean, P0 = unknown, P1 = unknown>(__readFontIntoRanges: P0, _fromPasteboard: P1): R;
    _readFilenamesIntoRange_fromPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__readFilenamesIntoRange: P0, _fromPasteboard: P1): R;
    _readFilenameStringsIntoRange_fromPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__readFilenameStringsIntoRange: P0, _fromPasteboard: P1): R;
    _readColorIntoRange_fromPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__readColorIntoRange: P0, _fromPasteboard: P1): R;
    _readColorIntoRanges_fromPasteboard<R = boolean, P0 = unknown, P1 = unknown>(__readColorIntoRanges: P0, _fromPasteboard: P1): R;
    _readAttributedStringIntoRanges_fromPasteboard_stripAttachments<R = boolean, P0 = unknown, P1 = unknown, P2 = boolean>(__readAttributedStringIntoRanges: P0, _fromPasteboard: P1, _stripAttachments: P2): R;
    _replaceCharactersInRange_withPastedAttributedString<R = boolean, P0 = _NSRange, P1 = unknown>(__replaceCharactersInRange: P0, _withPastedAttributedString: P1): R;
    _readStringWithLinksIntoRanges_fromPasteboard<R = boolean, P0 = unknown, P1 = unknown>(__readStringWithLinksIntoRanges: P0, _fromPasteboard: P1): R;
    _readStringIntoRange_fromPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__readStringIntoRange: P0, _fromPasteboard: P1): R;
    _readStringIntoRanges_fromPasteboard<R = boolean, P0 = unknown, P1 = unknown>(__readStringIntoRanges: P0, _fromPasteboard: P1): R;
    _rangesForMultipleTextSelectionPasteAtIndex_fromPasteboard<R = unknown, P0 = number, P1 = unknown>(__rangesForMultipleTextSelectionPasteAtIndex: P0, _fromPasteboard: P1): R;
    _readMultipleTextSelectionRangesForString_fromPasteboard<R = unknown, P0 = unknown, P1 = unknown>(__readMultipleTextSelectionRangesForString: P0, _fromPasteboard: P1): R;
    preferredPasteboardTypeFromArray_restrictedToTypesFromArray<R = unknown, P0 = unknown, P1 = unknown>(_preferredPasteboardTypeFromArray: P0, _restrictedToTypesFromArray: P1): R;
    writeSelectionToPasteboard_types<R = boolean, P0 = unknown, P1 = unknown>(_writeSelectionToPasteboard: P0, _types: P1): R;
    writeSelectionToPasteboard_type<R = boolean, P0 = unknown, P1 = unknown>(_writeSelectionToPasteboard: P0, _type: P1): R;
    _writeMultipleTextSelectionRanges_toPasteboard<R = boolean, P0 = unknown, P1 = unknown>(__writeMultipleTextSelectionRanges: P0, _toPasteboard: P1): R;
    _writeLinkStringInRange_toPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__writeLinkStringInRange: P0, _toPasteboard: P1): R;
    _writeURLStringsWithNamesInRange_toPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__writeURLStringsWithNamesInRange: P0, _toPasteboard: P1): R;
    _writeURLNameInRange_toPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__writeURLNameInRange: P0, _toPasteboard: P1): R;
    _writeURLStringInRange_toPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__writeURLStringInRange: P0, _toPasteboard: P1): R;
    _writeURLInRange_toPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__writeURLInRange: P0, _toPasteboard: P1): R;
    _writeRulerInRange_toPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__writeRulerInRange: P0, _toPasteboard: P1): R;
    _writeFontInRange_toPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__writeFontInRange: P0, _toPasteboard: P1): R;
    _writeRTFDInRange_toPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__writeRTFDInRange: P0, _toPasteboard: P1): R;
    _writeRTFDInRanges_toPasteboard<R = boolean, P0 = unknown, P1 = unknown>(__writeRTFDInRanges: P0, _toPasteboard: P1): R;
    _writeRTFInRange_toPasteboard<R = boolean, P0 = _NSRange, P1 = unknown>(__writeRTFInRange: P0, _toPasteboard: P1): R;
    _writeRTFInRanges_toPasteboard<R = boolean, P0 = unknown, P1 = unknown>(__writeRTFInRanges: P0, _toPasteboard: P1): R;
    _old_writeStringInRanges_toPasteboard<R = boolean, P0 = unknown, P1 = unknown>(__old_writeStringInRanges: P0, _toPasteboard: P1): R;
    _writeStringInRanges_toPasteboard<R = boolean, P0 = unknown, P1 = unknown>(__writeStringInRanges: P0, _toPasteboard: P1): R;
    _writeAttributedStringInRanges_toPasteboard<R = boolean, P0 = unknown, P1 = unknown>(__writeAttributedStringInRanges: P0, _toPasteboard: P1): R;
    _attributedSubstringForCopyingFromRange<R = unknown, P0 = _NSRange>(__attributedSubstringForCopyingFromRange: P0): R;
    _attachmentCellForSelection<R = unknown>(): R;
    _appearanceForExporting<R = unknown>(): R;
    _caretScreenRectForSelectionChangeFromRange_toRange<R = CGRect, P0 = _NSRange, P1 = _NSRange>(__caretScreenRectForSelectionChangeFromRange: P0, _toRange: P1): R;
    _sendZoomFocusChangedNotificationForSelectionChange<R = void>(): R;
    _setDeletesForGenericDragging<R = void, P0 = boolean>(__setDeletesForGenericDragging: P0): R;
    _deletesForGenericDragging<R = boolean>(): R;
    _hasScaledBacking<R = boolean>(): R;
    tokenizingCharacterSet<R = unknown>(): R;
    _changeBaseWritingDirection<R = void, P0 = number>(__changeBaseWritingDirection: P0): R;
    _changeTextWritingDirection<R = void, P0 = number>(__changeTextWritingDirection: P0): R;
    _clearMarkedRange<R = void>(): R;
    placeholderAttributedString<R = unknown>(): R;
    placeholderString<R = unknown>(): R;
    setPlaceholderAttributedString<R = void, P0 = unknown>(_setPlaceholderAttributedString: P0): R;
    setPlaceholderString<R = void, P0 = unknown>(_setPlaceholderString: P0): R;
    _finishedImmediateScroll<R = void>(): R;
    _finishedAnimatingScroll<R = void>(): R;
    _scrollToEnd<R = void, P0 = unknown>(__scrollToEnd: P0): R;
    _setScrollingToEnd<R = void, P0 = boolean>(__setScrollingToEnd: P0): R;
    _isScrollingToEnd<R = boolean>(): R;
    _immediateActionMenuItemForTextCheckingResult_range_location<R = unknown, P0 = unknown, P1 = _NSRange, P2 = CGPoint>(__immediateActionMenuItemForTextCheckingResult: P0, _range: P1, _location: P2): R;
    menuItemsForTextCheckingResult_range_contextual_event<R = unknown, P0 = unknown, P1 = _NSRange, P2 = boolean, P3 = unknown>(_menuItemsForTextCheckingResult: P0, _range: P1, _contextual: P2, _event: P3): R;
    _menuItemsForTextCheckingResult_range_contextual_immediate_location<R = unknown, P0 = unknown, P1 = _NSRange, P2 = boolean, P3 = boolean, P4 = CGPoint>(__menuItemsForTextCheckingResult: P0, _range: P1, _contextual: P2, _immediate: P3, _location: P4): R;
    highlightBoundingRectForCharacterRange_highlightStyle<R = CGRect, P0 = _NSRange, P1 = number>(_highlightBoundingRectForCharacterRange: P0, _highlightStyle: P1): R;
    highlightRectsForCharacterRange_highlightStyle<R = unknown, P0 = _NSRange, P1 = number>(_highlightRectsForCharacterRange: P0, _highlightStyle: P1): R;
    hideHighlight<R = void>(): R;
    showHighlightWithCharacterRange_highlightStyle<R = void, P0 = _NSRange, P1 = number>(_showHighlightWithCharacterRange: P0, _highlightStyle: P1): R;
    _showFindIndicatorWithCharRange<R = void, P0 = _NSRange>(__showFindIndicatorWithCharRange: P0): R;
    _showFindIndicatorWithCharRange_fade<R = void, P0 = _NSRange, P1 = boolean>(__showFindIndicatorWithCharRange: P0, _fade: P1): R;
    _hasVisisbleGlyphsInCharRange<R = boolean, P0 = _NSRange>(__hasVisisbleGlyphsInCharRange: P0): R;
    _createRectArrayForFindIndicatorForGlyphRange_rectCount<R = CGRect, P0 = _NSRange, P1 = number>(__createRectArrayForFindIndicatorForGlyphRange: P0, _rectCount: P1): R;
    _isInsertingText<R = boolean>(): R;
    _isUnmarking<R = boolean>(): R;
    wantsNotificationForMarkedText<R = boolean>(): R;
    setWantsNotificationForMarkedText<R = void, P0 = boolean>(_setWantsNotificationForMarkedText: P0): R;
    attributedSubstringForMarkedRange<R = unknown>(): R;
    _performUndoCoalescingAction<R = void, P0 = CDUnknownBlockType>(__performUndoCoalescingAction: P0): R;
    _fieldEditorUndoManager<R = unknown>(): R;
    _setFieldEditorUndoManager<R = unknown, P0 = unknown>(__setFieldEditorUndoManager: P0): R;
    _clearUndoRegistrations<R = void>(): R;
    _undoRedoInProgress<R = boolean>(): R;
    _setUndoRedoInProgress<R = void, P0 = boolean>(__setUndoRedoInProgress: P0): R;
    setUndoActionName<R = void, P0 = unknown>(_setUndoActionName: P0): R;
    _userDeleteRange<R = void, P0 = _NSRange>(__userDeleteRange: P0): R;
    _userReplaceRange_withString<R = void, P0 = _NSRange, P1 = unknown>(__userReplaceRange: P0, _withString: P1): R;
    _ivars<R = unknown>(): R;
    _sharedData<R = unknown>(): R;
    _blockRowRectForCharRange_rect<R = CGRect, P0 = _NSRange, P1 = CGRect>(__blockRowRectForCharRange: P0, _rect: P1): R;
    _calculateTotalScaleForPrintingWithOperation<R = void, P0 = unknown>(__calculateTotalScaleForPrintingWithOperation: P0): R;
    _calculatePageRectsWithOperation_pageSize_layoutAssuredComplete<R = void, P0 = unknown, P1 = CGSize, P2 = boolean>(__calculatePageRectsWithOperation: P0, _pageSize: P1, _layoutAssuredComplete: P2): R;
    _scrollRangeToVisible_forceCenter<R = void, P0 = _NSRange, P1 = boolean>(__scrollRangeToVisible: P0, _forceCenter: P1): R;
    _centeredScrollRectToVisible_forceCenter<R = void, P0 = CGRect, P1 = boolean>(__centeredScrollRectToVisible: P0, _forceCenter: P1): R;
    _adjustedCenteredScrollRectToVisible_forceCenter<R = void, P0 = CGRect, P1 = boolean>(__adjustedCenteredScrollRectToVisible: P0, _forceCenter: P1): R;
    _setFrameSize_forceScroll<R = void, P0 = CGSize, P1 = boolean>(__setFrameSize: P0, _forceScroll: P1): R;
    _ensureLayoutCompleteForVisibleRectWithExtension<R = boolean, P0 = boolean>(__ensureLayoutCompleteForVisibleRectWithExtension: P0): R;
    _ensureLayoutCompleteForVisibleRectWithExtensionFactor_minimumExtensionDistance_repetitions<R = boolean, P0 = number, P1 = number, P2 = number>(__ensureLayoutCompleteForVisibleRectWithExtensionFactor: P0, _minimumExtensionDistance: P1, _repetitions: P2): R;
    _ensureLayoutCompleteForPreparingContentInRect<R = CGRect, P0 = CGRect>(__ensureLayoutCompleteForPreparingContentInRect: P0): R;
    _ensureLayoutCompleteForRect_withExtensionFactor_minimumExtensionDistance_repetitions_preparedContentRect<R = boolean, P0 = CGRect, P1 = number, P2 = number, P3 = number, P4 = CGRect>(__ensureLayoutCompleteForRect: P0, _withExtensionFactor: P1, _minimumExtensionDistance: P2, _repetitions: P3, _preparedContentRect: P4): R;
    _ensureLayoutCompleteToEndOfCharacterRange<R = void, P0 = _NSRange>(__ensureLayoutCompleteToEndOfCharacterRange: P0): R;
    _setDistanceForVerticalArrowKeyMovement<R = void, P0 = number>(__setDistanceForVerticalArrowKeyMovement: P0): R;
    _distanceForVerticalArrowKeyMovement<R = number>(): R;
    _couldHaveBlinkTimer<R = boolean>(): R;
    _shouldHaveBlinkTimer<R = boolean>(): R;
    _invalidateBlinkTimer<R = void, P0 = unknown>(__invalidateBlinkTimer: P0): R;
    _updateCaretDisplayWithSharedData_textView<R = void, P0 = unknown, P1 = unknown>(__updateCaretDisplayWithSharedData: P0, _textView: P1): R;
    _animateBlinkUpdate<R = void, P0 = unknown>(__animateBlinkUpdate: P0): R;
    _updateCaretViewWithSharedData_textView_animated<R = void, P0 = unknown, P1 = unknown, P2 = boolean>(__updateCaretViewWithSharedData: P0, _textView: P1, _animated: P2): R;
    switchBlinkTimersIfNecessaryWithSharedData<R = boolean, P0 = unknown>(_switchBlinkTimersIfNecessaryWithSharedData: P0): R;
    _blinkCaret_animated<R = void, P0 = unknown, P1 = boolean>(__blinkCaret: P0, _animated: P1): R;
    _blinkCaret<R = void, P0 = unknown>(__blinkCaret: P0): R;
    _useUpdateBlinkRate<R = boolean>(): R;
    _caretMustDraw<R = boolean>(): R;
    _applyMarkerSettingsFromParagraphStyle<R = void, P0 = unknown>(__applyMarkerSettingsFromParagraphStyle: P0): R;
    _canChangeRulerMarkers<R = boolean>(): R;
    _installRulerAccViewForParagraphStyle_ruler_enabled<R = void, P0 = unknown, P1 = unknown, P2 = boolean>(__installRulerAccViewForParagraphStyle: P0, _ruler: P1, _enabled: P2): R;
    _fixSharedData<R = void>(): R;
    _giveUpFirstResponder<R = void, P0 = number>(__giveUpFirstResponder: P0): R;
    _outlineIsOn<R = boolean>(): R;
    _underlineIsOn<R = boolean>(): R;
    _remove_andAddMultipleToTypingAttributes<R = void, P0 = unknown, P1 = unknown>(__remove: P0, _andAddMultipleToTypingAttributes: P1): R;
    _addMultipleToTypingAttributes<R = void, P0 = unknown>(__addMultipleToTypingAttributes: P0): R;
    _addToTypingAttributes_value<R = void, P0 = unknown, P1 = unknown>(__addToTypingAttributes: P0, _value: P1): R;
    _canImportGraphics<R = boolean>(): R;
    _canAcceptRichText<R = boolean>(): R;
    _attributedSubstringForRanges_substringProvider<R = unknown, P0 = unknown, P1 = CDUnknownBlockType>(__attributedSubstringForRanges: P0, _substringProvider: P1): R;
    _attributedSubstringForRanges<R = unknown, P0 = unknown>(__attributedSubstringForRanges: P0): R;
    _setAttributes_newValues_range<R = void, P0 = unknown, P1 = unknown, P2 = _NSRange>(__setAttributes: P0, _newValues: P1, _range: P2): R;
    _stripAttachmentCharactersAndParagraphStylesFromAttributedString<R = unknown, P0 = unknown>(__stripAttachmentCharactersAndParagraphStylesFromAttributedString: P0): R;
    _stripAttachmentCharactersFromAttributedString<R = unknown, P0 = unknown>(__stripAttachmentCharactersFromAttributedString: P0): R;
    _stripAttachmentCharactersFromString<R = unknown, P0 = unknown>(__stripAttachmentCharactersFromString: P0): R;
    _ensureMinAndMaxSizesConsistentWithBounds<R = void>(): R;
    _fastHighlightGlyphRange_withinSelectedGlyphRange<R = void, P0 = _NSRange, P1 = _NSRange>(__fastHighlightGlyphRange: P0, _withinSelectedGlyphRange: P1): R;
    _optimizeHighlightForCharRange_charRange_fullSelectionCharRange_oldSelectionFullCharRange<R = void, P0 = _NSRange, P1 = _NSRange, P2 = _NSRange, P3 = _NSRange>(__optimizeHighlightForCharRange: P0, _charRange: P1, _fullSelectionCharRange: P2, _oldSelectionFullCharRange: P3): R;
    _charRangeIsHighlightOptimizable_fromOldCharRange<R = boolean, P0 = _NSRange, P1 = _NSRange>(__charRangeIsHighlightOptimizable: P0, _fromOldCharRange: P1): R;
    observeValueForKeyPath_ofObject_change_context<R = void, P0 = unknown, P1 = unknown, P2 = unknown, P3 = void>(_observeValueForKeyPath: P0, _ofObject: P1, _change: P2, _context: P3): R;
    _superviewClipViewFrameChangedWithNotification<R = void, P0 = unknown>(__superviewClipViewFrameChangedWithNotification: P0): R;
    _superviewClipViewFrameChanged<R = void, P0 = unknown>(__superviewClipViewFrameChanged: P0): R;
    _setWatchingSuperviewClipView<R = void, P0 = boolean>(__setWatchingSuperviewClipView: P0): R;
    _forceResizingForClipViewInsetBounds<R = void, P0 = CGRect>(__forceResizingForClipViewInsetBounds: P0): R;
    _sizeDownIfPossible<R = void>(): R;
    _range_containsPoint<R = boolean, P0 = _NSRange, P1 = CGPoint>(__range: P0, _containsPoint: P1): R;
    _clickedCharIndex<R = number>(): R;
    _trackAttachmentClick_characterIndex_glyphIndex_attachmentCell<R = boolean, P0 = unknown, P1 = number, P2 = number, P3 = unknown>(__trackAttachmentClick: P0, _characterIndex: P1, _glyphIndex: P2, _attachmentCell: P3): R;
    _getGlyphIndex_forWindowPoint_pinnedPoint_preferredTextView_partialFraction<R = unknown, P0 = number, P1 = CGPoint, P2 = CGPoint, P3 = unknown, P4 = number>(__getGlyphIndex: P0, _forWindowPoint: P1, _pinnedPoint: P2, _preferredTextView: P3, _partialFraction: P4): R;
    _getGlyphIndex_characterIndex_forWindowPoint_pinnedPoint_preferredTextView_partialFraction<R = unknown, P0 = number, P1 = number, P2 = CGPoint, P3 = CGPoint, P4 = unknown, P5 = number>(__getGlyphIndex: P0, _characterIndex: P1, _forWindowPoint: P2, _pinnedPoint: P3, _preferredTextView: P4, _partialFraction: P5): R;
    _getGlyphIndex_forWindowPoint_pinnedPoint_anchorPoint_useAnchorPoint_preferredTextView_partialFraction<R = unknown, P0 = number, P1 = CGPoint, P2 = CGPoint, P3 = CGPoint, P4 = boolean, P5 = unknown, P6 = number>(__getGlyphIndex: P0, _forWindowPoint: P1, _pinnedPoint: P2, _anchorPoint: P3, _useAnchorPoint: P4, _preferredTextView: P5, _partialFraction: P6): R;
    _getGlyphIndex_characterIndex_forWindowPoint_pinnedPoint_anchorPoint_useAnchorPoint_preferredTextView_partialFraction<R = unknown, P0 = number, P1 = number, P2 = CGPoint, P3 = CGPoint, P4 = CGPoint, P5 = boolean, P6 = unknown, P7 = number>(__getGlyphIndex: P0, _characterIndex: P1, _forWindowPoint: P2, _pinnedPoint: P3, _anchorPoint: P4, _useAnchorPoint: P5, _preferredTextView: P6, _partialFraction: P7): R;
    _drawViewBackgroundInRect<R = void, P0 = CGRect>(__drawViewBackgroundInRect: P0): R;
    _cuiSourceListBackgroundOptions<R = unknown>(): R;
    replacementObjectForArchiver<R = unknown, P0 = unknown>(_replacementObjectForArchiver: P0): R;
    replacementObjectForKeyedArchiver<R = unknown, P0 = unknown>(_replacementObjectForKeyedArchiver: P0): R;
    _textViewOwnsTextStorage<R = boolean>(): R;
    _commonInitState<R = void>(): R;
    _commonInitIvarBlock<R = void>(): R;
    characterRangeForRect<R = _NSRange, P0 = CGRect>(_characterRangeForRect: P0): R;
    layoutManager_effectiveCUICatalogForTextEffect<R = unknown, P0 = unknown, P1 = unknown>(_layoutManager: P0, _effectiveCUICatalogForTextEffect: P1): R;
    setEnabledTextCheckingTypes<R = void, P0 = number>(_setEnabledTextCheckingTypes: P0): R;
    enabledTextCheckingTypes<R = number>(): R;
    toggleAutomaticTextCompletion<R = void, P0 = unknown>(_toggleAutomaticTextCompletion: P0): R;
    isAutomaticTextCompletionEnabled<R = boolean>(): R;
    setAutomaticTextCompletionEnabled<R = void, P0 = boolean>(_setAutomaticTextCompletionEnabled: P0): R;
    toggleAutomaticSpellingCorrection<R = void, P0 = unknown>(_toggleAutomaticSpellingCorrection: P0): R;
    isAutomaticSpellingCorrectionEnabled<R = boolean>(): R;
    setAutomaticSpellingCorrectionEnabled<R = void, P0 = boolean>(_setAutomaticSpellingCorrectionEnabled: P0): R;
    toggleAutomaticTextReplacement<R = void, P0 = unknown>(_toggleAutomaticTextReplacement: P0): R;
    isAutomaticTextReplacementEnabled<R = boolean>(): R;
    setAutomaticTextReplacementEnabled<R = void, P0 = boolean>(_setAutomaticTextReplacementEnabled: P0): R;
    toggleAutomaticDashSubstitution<R = void, P0 = unknown>(_toggleAutomaticDashSubstitution: P0): R;
    isAutomaticDashSubstitutionEnabled<R = boolean>(): R;
    setAutomaticDashSubstitutionEnabled<R = void, P0 = boolean>(_setAutomaticDashSubstitutionEnabled: P0): R;
    toggleAutomaticDataDetection<R = void, P0 = unknown>(_toggleAutomaticDataDetection: P0): R;
    isAutomaticDataDetectionEnabled<R = boolean>(): R;
    setAutomaticDataDetectionEnabled<R = void, P0 = boolean>(_setAutomaticDataDetectionEnabled: P0): R;
    toggleAutomaticLanguageIdentification<R = void, P0 = unknown>(_toggleAutomaticLanguageIdentification: P0): R;
    isAutomaticLanguageIdentificationEnabled<R = boolean>(): R;
    setAutomaticLanguageIdentificationEnabled<R = void, P0 = boolean>(_setAutomaticLanguageIdentificationEnabled: P0): R;
    toggleAutomaticLinkDetection<R = void, P0 = unknown>(_toggleAutomaticLinkDetection: P0): R;
    isAutomaticLinkDetectionEnabled<R = boolean>(): R;
    setAutomaticLinkDetectionEnabled<R = void, P0 = boolean>(_setAutomaticLinkDetectionEnabled: P0): R;
    toggleAutomaticQuoteSubstitution<R = void, P0 = unknown>(_toggleAutomaticQuoteSubstitution: P0): R;
    isAutomaticQuoteSubstitutionEnabled<R = boolean>(): R;
    setAutomaticQuoteSubstitutionEnabled<R = void, P0 = boolean>(_setAutomaticQuoteSubstitutionEnabled: P0): R;
    smartInsertForString_replacingRange_beforeString_afterString<R = void, P0 = unknown, P1 = _NSRange, P2 = unknown, P3 = unknown>(_smartInsertForString: P0, _replacingRange: P1, _beforeString: P2, _afterString: P3): R;
    smartInsertAfterStringForString_replacingRange<R = unknown, P0 = unknown, P1 = _NSRange>(_smartInsertAfterStringForString: P0, _replacingRange: P1): R;
    smartInsertBeforeStringForString_replacingRange<R = unknown, P0 = unknown, P1 = _NSRange>(_smartInsertBeforeStringForString: P0, _replacingRange: P1): R;
    smartDeleteRangeForProposedRange<R = _NSRange, P0 = _NSRange>(_smartDeleteRangeForProposedRange: P0): R;
    toggleSmartInsertDelete<R = void, P0 = unknown>(_toggleSmartInsertDelete: P0): R;
    setSmartInsertDeleteEnabled<R = void, P0 = boolean>(_setSmartInsertDeleteEnabled: P0): R;
    smartInsertDeleteEnabled<R = boolean>(): R;
    resignKeyWindow<R = void>(): R;
    resignKeyFocus<R = void>(): R;
    becomeMainWindow<R = void>(): R;
    becomeKeyWindow<R = void>(): R;
    acquireKeyFocus<R = void>(): R;
    performPendingTextChecking<R = void>(): R;
    _performPendingTextChecking<R = void>(): R;
    _validateAndCommitTokens<R = boolean>(): R;
    _invalidateDisplayForMarkedOrSelectedRange<R = void>(): R;
    showFindIndicatorForRange<R = void, P0 = _NSRange>(_showFindIndicatorForRange: P0): R;
    showFindIndicatorForRange_fade<R = void, P0 = _NSRange, P1 = boolean>(_showFindIndicatorForRange: P0, _fade: P1): R;
    setSelectedRange<R = void, P0 = _NSRange>(_setSelectedRange: P0): R;
    toggleUsesAdaptiveColorMappingForDarkAppearance<R = void, P0 = unknown>(_toggleUsesAdaptiveColorMappingForDarkAppearance: P0): R;
    usesColorsWithInvertedLightness<R = boolean>(): R;
    setUsesColorsWithInvertedLightness<R = void, P0 = boolean>(_setUsesColorsWithInvertedLightness: P0): R;
    usesAdaptiveColorMappingForDarkAppearance<R = boolean>(): R;
    setUsesAdaptiveColorMappingForDarkAppearance<R = void, P0 = boolean>(_setUsesAdaptiveColorMappingForDarkAppearance: P0): R;
    setIncrementalSearchingEnabled<R = void, P0 = boolean>(_setIncrementalSearchingEnabled: P0): R;
    isIncrementalSearchingEnabled<R = boolean>(): R;
    setUsesFindBar<R = void, P0 = boolean>(_setUsesFindBar: P0): R;
    usesFindBar<R = boolean>(): R;
    setUsesFindPanel<R = void, P0 = boolean>(_setUsesFindPanel: P0): R;
    usesFindPanel<R = boolean>(): R;
    setPreferredTextFinderStyle<R = void, P0 = number>(_setPreferredTextFinderStyle: P0): R;
    preferredTextFinderStyle<R = number>(): R;
    breakUndoCoalescing<R = void>(): R;
    _rangesForUserTextWritingDirectionChange<R = unknown>(): R;
    _rangeForUserTextWritingDirectionChange<R = _NSRange>(): R;
    _rangesForUserBaseWritingDirectionChange<R = unknown>(): R;
    _rangeForUserBaseWritingDirectionChange<R = _NSRange>(): R;
    _blockSafeRangesForRange<R = unknown, P0 = _NSRange>(__blockSafeRangesForRange: P0): R;
    didChangeText<R = void>(): R;
    shouldChangeTextInRanges_replacementStrings<R = boolean, P0 = unknown, P1 = unknown>(_shouldChangeTextInRanges: P0, _replacementStrings: P1): R;
    shouldChangeTextInRange_replacementString<R = boolean, P0 = _NSRange, P1 = unknown>(_shouldChangeTextInRange: P0, _replacementString: P1): R;
    setAllowsCharacterPickerTouchBarItem<R = void, P0 = boolean>(_setAllowsCharacterPickerTouchBarItem: P0): R;
    allowsCharacterPickerTouchBarItem<R = boolean>(): R;
    setSpellingState_range<R = void, P0 = number, P1 = _NSRange>(_setSpellingState: P0, _range: P1): R;
    toggleGrammarChecking<R = void, P0 = unknown>(_toggleGrammarChecking: P0): R;
    toggleContinuousSpellChecking<R = void, P0 = unknown>(_toggleContinuousSpellChecking: P0): R;
    _preflightSpellChecker<R = void, P0 = unknown>(__preflightSpellChecker: P0): R;
    _continuousCheckingAllowed<R = boolean>(): R;
    _allowsMultipleTextSelectionByMouse<R = boolean>(): R;
    _restartBlinkDrawTimer<R = void>(): R;
    _restartBlinkTimer<R = void>(): R;
    _restartBlinkTimersWithSharedData<R = void, P0 = unknown>(__restartBlinkTimersWithSharedData: P0): R;
    _updateBlinkTimersWithSharedData_restartFlag_forceBlink<R = void, P0 = unknown, P1 = boolean, P2 = boolean>(__updateBlinkTimersWithSharedData: P0, _restartFlag: P1, _forceBlink: P2): R;
    updateInsertionPointStateAndRestartTimer<R = void, P0 = boolean>(_updateInsertionPointStateAndRestartTimer: P0): R;
    _usesSplitCursor<R = boolean>(): R;
    centersOnScroll<R = boolean>(): R;
    setCentersOnScroll<R = void, P0 = boolean>(_setCentersOnScroll: P0): R;
    setSelectedRanges_affinity_stillSelecting<R = void, P0 = unknown, P1 = number, P2 = boolean>(_setSelectedRanges: P0, _affinity: P1, _stillSelecting: P2): R;
    setSelectedRange_affinity_stillSelecting<R = void, P0 = _NSRange, P1 = number, P2 = boolean>(_setSelectedRange: P0, _affinity: P1, _stillSelecting: P2): R;
    _alternativesTimer<R = void>(): R;
    _guessesTimer<R = void>(): R;
    _reversionTimer<R = void>(): R;
    _selectedRanges<R = unknown>(): R;
    _fixedSelectionRangesForRanges_affinity<R = unknown, P0 = unknown, P1 = number>(__fixedSelectionRangesForRanges: P0, _affinity: P1): R;
    _fixedSelectionRangeForRange_affinity<R = _NSRange, P0 = _NSRange, P1 = number>(__fixedSelectionRangeForRange: P0, _affinity: P1): R;
    _invalidateDisplayForChangeOfSelectionFromRange_toRange<R = void, P0 = _NSRange, P1 = _NSRange>(__invalidateDisplayForChangeOfSelectionFromRange: P0, _toRange: P1): R;
    immediateActionRecognizerDidCompleteAnimation<R = void, P0 = unknown>(_immediateActionRecognizerDidCompleteAnimation: P0): R;
    immediateActionRecognizerDidCancelAnimation<R = void, P0 = unknown>(_immediateActionRecognizerDidCancelAnimation: P0): R;
    immediateActionRecognizerDidUpdateAnimation<R = void, P0 = unknown>(_immediateActionRecognizerDidUpdateAnimation: P0): R;
    immediateActionRecognizerWillBeginAnimation<R = void, P0 = unknown>(_immediateActionRecognizerWillBeginAnimation: P0): R;
    immediateActionRecognizerWillPrepare<R = void, P0 = unknown>(_immediateActionRecognizerWillPrepare: P0): R;
    _immediateActionAnimationControllerForCharacterAtIndex_withRecognizer<R = unknown, P0 = number, P1 = unknown>(__immediateActionAnimationControllerForCharacterAtIndex: P0, _withRecognizer: P1): R;
    _markUpAction<R = void, P0 = unknown>(__markUpAction: P0): R;
    showDefinitionFromMenu<R = void, P0 = unknown>(_showDefinitionFromMenu: P0): R;
    applyActionForRanges_block<R = void, P0 = unknown, P1 = CDUnknownBlockType>(_applyActionForRanges: P0, _block: P1): R;
    invokeImmediateActionMenuItem<R = void, P0 = unknown>(_invokeImmediateActionMenuItem: P0): R;
    _selectionDragTimerFire<R = void, P0 = unknown>(__selectionDragTimerFire: P0): R;
    candidateListTouchBarItem_changedCandidateListVisibility<R = void, P0 = unknown, P1 = boolean>(_candidateListTouchBarItem: P0, _changedCandidateListVisibility: P1): R;
    updateCandidates<R = void>(): R;
    handleCandidates_sequenceNumber<R = void, P0 = unknown, P1 = number>(_handleCandidates: P0, _sequenceNumber: P1): R;
    candidateListTouchBarItem_endSelectingCandidateAtIndex<R = void, P0 = unknown, P1 = number>(_candidateListTouchBarItem: P0, _endSelectingCandidateAtIndex: P1): R;
    insertCandidateTextCheckingResult<R = void, P0 = unknown>(_insertCandidateTextCheckingResult: P0): R;
    insertCandidateString_replacementRange_fromTextCheckingResult<R = void, P0 = unknown, P1 = _NSRange, P2 = boolean>(_insertCandidateString: P0, _replacementRange: P1, _fromTextCheckingResult: P2): R;
    _restoreSelectedRangeAfterUndoOfCandidateSelection<R = void>(): R;
    _rangeForUserCompletion<R = _NSRange>(): R;
    functionBar_makeItemForIdentifier<R = unknown, P0 = unknown, P1 = unknown>(_functionBar: P0, _makeItemForIdentifier: P1): R;
    touchBar_makeItemForIdentifier<R = unknown, P0 = unknown, P1 = unknown>(_touchBar: P0, _makeItemForIdentifier: P1): R;
    updateTextTouchBarItems<R = void>(): R;
    changeAttributesWithModifier<R = void, P0 = CDUnknownBlockType>(_changeAttributesWithModifier: P0): R;
    candidateListTouchBarItem<R = unknown>(): R;
    _setupCandidateListTouchBarItem<R = void>(): R;
    touchBarItemController<R = unknown>(): R;
    _touchBarItemController<R = unknown>(): R;
    setTouchBar<R = void, P0 = unknown>(_setTouchBar: P0): R;
    updateTouchBarItemIdentifiers<R = void>(): R;
    _configureTouchBar_withIdentifiers<R = void, P0 = unknown, P1 = unknown>(__configureTouchBar: P0, _withIdentifiers: P1): R;
    _updateAllowsCollapsingWithTouchBar<R = void, P0 = unknown>(__updateAllowsCollapsingWithTouchBar: P0): R;
    _touchBarItemIdentifiers<R = unknown>(): R;
    previewPanel_transitionImageForPreviewItem_contentRect<R = unknown, P0 = unknown, P1 = unknown, P2 = CGRect>(_previewPanel: P0, _transitionImageForPreviewItem: P1, _contentRect: P2): R;
    previewPanel_sourceFrameOnScreenForPreviewItem<R = CGRect, P0 = unknown, P1 = unknown>(_previewPanel: P0, _sourceFrameOnScreenForPreviewItem: P1): R;
    previewPanel_previewItemAtIndex<R = unknown, P0 = unknown, P1 = number>(_previewPanel: P0, _previewItemAtIndex: P1): R;
    numberOfPreviewItemsInPreviewPanel<R = number, P0 = unknown>(_numberOfPreviewItemsInPreviewPanel: P0): R;
    endPreviewPanelControl<R = void, P0 = unknown>(_endPreviewPanelControl: P0): R;
    beginPreviewPanelControl<R = void, P0 = unknown>(_beginPreviewPanelControl: P0): R;
    acceptsPreviewPanelControl<R = boolean, P0 = unknown>(_acceptsPreviewPanelControl: P0): R;
    _quickLookPreviewItemsInRange<R = boolean, P0 = _NSRange>(__quickLookPreviewItemsInRange: P0): R;
    toggleQuickLookPreviewPanel<R = void, P0 = unknown>(_toggleQuickLookPreviewPanel: P0): R;
    updateQuickLookPreviewPanel<R = void>(): R;
    quickLookPreviewableItemsInRanges<R = unknown, P0 = unknown>(_quickLookPreviewableItemsInRanges: P0): R;
    _closeQuickLookPreviewPanelWithSpace<R = boolean>(): R;
    _validateMenuItemForPreviewAction<R = void, P0 = unknown>(__validateMenuItemForPreviewAction: P0): R;
    _shouldIncludePreviewActionInContextMenu<R = boolean>(): R;
    _characterIndexForPreviewItem<R = number, P0 = unknown>(__characterIndexForPreviewItem: P0): R;
    _rangesForPreview<R = unknown>(): R;
    _hasJapaneseInPreferredLanguages<R = boolean>(): R;
    shouldRemoveTransformationAction<R = boolean, P0 = string>(_shouldRemoveTransformationAction: P0): R;
    shouldRemoveCaseTransformations<R = boolean>(): R;
    _sharingServiceItemsInRanges<R = unknown, P0 = unknown>(__sharingServiceItemsInRanges: P0): R;
    readSelectionFromItems<R = void, P0 = unknown>(_readSelectionFromItems: P0): R;
    canReadSelectionFromItems<R = boolean>(): R;
    selectionItems<R = unknown>(): R;
    invokeExtensionService<R = void, P0 = unknown>(_invokeExtensionService: P0): R;
    _configureSharingServicesMenuItemInRange<R = unknown, P0 = _NSRange>(__configureSharingServicesMenuItemInRange: P0): R;
    _invokeSharingService<R = void, P0 = unknown>(__invokeSharingService: P0): R;
    sharingServicePicker_delegateForSharingService<R = unknown, P0 = unknown, P1 = unknown>(_sharingServicePicker: P0, _delegateForSharingService: P1): R;
    sharingServicePicker_sharingServicesForItems_mask_proposedSharingServices<R = unknown, P0 = unknown, P1 = unknown, P2 = number, P3 = unknown>(_sharingServicePicker: P0, _sharingServicesForItems: P1, _mask: P2, _proposedSharingServices: P3): R;
    sharingService_didShareItems<R = void, P0 = unknown, P1 = unknown>(_sharingService: P0, _didShareItems: P1): R;
    _replaceSelectionWithSharingServiceItems<R = void, P0 = unknown>(__replaceSelectionWithSharingServiceItems: P0): R;
    sharingService_sourceWindowForShareItems_sharingContentScope<R = unknown, P0 = unknown, P1 = unknown, P2 = number>(_sharingService: P0, _sourceWindowForShareItems: P1, _sharingContentScope: P2): R;
    sharingService_transitionImageForShareItem_contentRect<R = unknown, P0 = unknown, P1 = unknown, P2 = CGRect>(_sharingService: P0, _transitionImageForShareItem: P1, _contentRect: P2): R;
    sharingService_containerFrameOnScreenForShareItem<R = CGRect, P0 = unknown, P1 = unknown>(_sharingService: P0, _containerFrameOnScreenForShareItem: P1): R;
    sharingService_sourceFrameOnScreenForShareItem<R = CGRect, P0 = unknown, P1 = unknown>(_sharingService: P0, _sourceFrameOnScreenForShareItem: P1): R;
    itemsForSharingServiceInRanges<R = unknown, P0 = unknown>(_itemsForSharingServiceInRanges: P0): R;
    _sharingItemForAttachment_atIndex<R = unknown, P0 = unknown, P1 = number>(__sharingItemForAttachment: P0, _atIndex: P1): R;
    orderFrontSharingServicePicker<R = void, P0 = unknown>(_orderFrontSharingServicePicker: P0): R;
    _menuItemsForDataResult<R = unknown, P0 = unknown>(__menuItemsForDataResult: P0): R;
    displayTextLayer<R = void, P0 = unknown>(_displayTextLayer: P0): R;
    _isDrawingLayer<R = boolean>(): R;
    _setIsDrawingLayer<R = void, P0 = boolean>(__setIsDrawingLayer: P0): R;
    layoutOrientation<R = number>(): R;
    description<R = NSString>(): R;
    shouldDrawInsertionPoint<R = boolean>(): R;
    textStorage<R = NSTextStorage>(): R;
    layoutManager<R = NSLayoutManager>(): R;
    textContainerOrigin<R = CGPoint>(): R;
    textContainerInset<R = CGSize>(): R;
    setTextContainerInset<R = void, P0 = CGSize>(_v: P0): R;
    textContainer<R = NSTextContainer>(): R;
    setTextContainer<R = void, P0 = NSTextContainer>(_v: P0): R;
    acceptableDragTypes<R = NSArray>(): R;
    readablePasteboardTypes<R = NSArray>(): R;
    writablePasteboardTypes<R = NSArray>(): R;
    allowedInputSourceLocales<R = NSArray>(): R;
    setAllowedInputSourceLocales<R = void, P0 = NSArray>(_v: P0): R;
    allowsDocumentBackgroundColorChange<R = boolean>(): R;
    setAllowsDocumentBackgroundColorChange<R = void, P0 = boolean>(_v: P0): R;
    selectedRanges<R = NSArray>(): R;
    setSelectedRanges<R = void, P0 = NSArray>(_v: P0): R;
    drawsBackground<R = boolean>(): R;
    setDrawsBackground<R = void, P0 = boolean>(_v: P0): R;
    backgroundColor<R = NSColor>(): R;
    setBackgroundColor<R = void, P0 = NSColor>(_v: P0): R;
    rulerVisible<R = boolean>(): R;
    setRulerVisible<R = void, P0 = boolean>(_v: P0): R;
    usesFontPanel<R = boolean>(): R;
    setUsesFontPanel<R = void, P0 = boolean>(_v: P0): R;
    fieldEditor<R = boolean>(): R;
    setFieldEditor<R = void, P0 = boolean>(_v: P0): R;
    delegate<R = NSTextViewDelegate>(): R;
    setDelegate<R = void, P0 = NSTextViewDelegate>(_v: P0): R;
    importsGraphics<R = boolean>(): R;
    setImportsGraphics<R = void, P0 = boolean>(_v: P0): R;
    richText<R = boolean>(): R;
    setRichText<R = void, P0 = boolean>(_v: P0): R;
    allowsImageEditing<R = boolean>(): R;
    setAllowsImageEditing<R = void, P0 = boolean>(_v: P0): R;
    coalescingUndo<R = boolean>(): R;
    allowsUndo<R = boolean>(): R;
    setAllowsUndo<R = void, P0 = boolean>(_v: P0): R;
    editable<R = boolean>(): R;
    setEditable<R = void, P0 = boolean>(_v: P0): R;
    selectable<R = boolean>(): R;
    setSelectable<R = void, P0 = boolean>(_v: P0): R;
    rangesForUserParagraphAttributeChange<R = NSArray>(): R;
    rangeForUserParagraphAttributeChange<R = _NSRange>(): R;
    rangesForUserCharacterAttributeChange<R = NSArray>(): R;
    rangeForUserCharacterAttributeChange<R = _NSRange>(): R;
    rangesForUserTextChange<R = NSArray>(): R;
    rangeForUserTextChange<R = _NSRange>(): R;
    defaultParagraphStyle<R = NSParagraphStyle>(): R;
    setDefaultParagraphStyle<R = void, P0 = NSParagraphStyle>(_v: P0): R;
    typingAttributes<R = NSDictionary>(): R;
    setTypingAttributes<R = void, P0 = NSDictionary>(_v: P0): R;
    spellCheckerDocumentTag<R = number>(): R;
    usesRolloverButtonForSelection<R = boolean>(): R;
    setUsesRolloverButtonForSelection<R = void, P0 = boolean>(_v: P0): R;
    usesInspectorBar<R = boolean>(): R;
    setUsesInspectorBar<R = void, P0 = boolean>(_v: P0): R;
    usesRuler<R = boolean>(): R;
    setUsesRuler<R = void, P0 = boolean>(_v: P0): R;
    grammarCheckingEnabled<R = boolean>(): R;
    setGrammarCheckingEnabled<R = void, P0 = boolean>(_v: P0): R;
    continuousSpellCheckingEnabled<R = boolean>(): R;
    setContinuousSpellCheckingEnabled<R = void, P0 = boolean>(_v: P0): R;
    acceptsGlyphInfo<R = boolean>(): R;
    setAcceptsGlyphInfo<R = void, P0 = boolean>(_v: P0): R;
    markedTextAttributes<R = NSDictionary>(): R;
    setMarkedTextAttributes<R = void, P0 = NSDictionary>(_v: P0): R;
    insertionPointColor<R = NSColor>(): R;
    setInsertionPointColor<R = void, P0 = NSColor>(_v: P0): R;
    displaysLinkToolTips<R = boolean>(): R;
    setDisplaysLinkToolTips<R = void, P0 = boolean>(_v: P0): R;
    linkTextAttributes<R = NSDictionary>(): R;
    setLinkTextAttributes<R = void, P0 = NSDictionary>(_v: P0): R;
    selectedTextAttributes<R = NSDictionary>(): R;
    setSelectedTextAttributes<R = void, P0 = NSDictionary>(_v: P0): R;
    selectionGranularity<R = number>(): R;
    setSelectionGranularity<R = void, P0 = number>(_v: P0): R;
    selectionAffinity<R = number>(): R;
    debugDescription<R = NSString>(): R;
    hash<R = number>(): R;
    superclass<R = unknown>(): R;
    // + NSTextView(PopoverDismissal): 
    clickShouldDismissPopover<R = boolean, P0 = unknown>(_clickShouldDismissPopover: P0): R;
  }
  namespace NSTextView {
    export interface CLASS<T0 = void, T1 = void, T2 = void> extends NSText, NSColorChangingProtocol, NSMenuItemValidationProtocol, NSUserInterfaceValidationsProtocol, NSTextInputClientProtocol, NSTextLayoutOrientationProviderProtocol, NSDraggingSourceProtocol, NSStandardKeyBindingRespondingProtocol, NSTextInputProtocol, NSAccessibilityNavigableStaticTextProtocol {
      alloc<R = NSTextView>(): R;
      new: <R = NSTextView>() => R;
      mapsDocumentColorForColorPickers<R = boolean>(): R;
      stronglyReferencesTextStorage<R = boolean>(): R;
      alwaysReferencesTextStorageStrongly<R = boolean>(): R;
      scrollablePlainDocumentContentTextView<R = unknown>(): R;
      scrollableDocumentContentTextView<R = unknown>(): R;
      fieldEditor<R = unknown>(): R;
      scrollableTextView<R = unknown>(): R;
      _allowKillRing<R = boolean>(): R;
      registerForServices<R = void>(): R;
      _readablePasteboardTypesForRichText_importsGraphics_usesFontPanel_usesRuler_allowsFiltering<R = unknown, P0 = boolean, P1 = boolean, P2 = boolean, P3 = boolean, P4 = boolean>(__readablePasteboardTypesForRichText: P0, _importsGraphics: P1, _usesFontPanel: P2, _usesRuler: P3, _allowsFiltering: P4): R;
      _URLStringForString<R = unknown, P0 = unknown>(__URLStringForString: P0): R;
      _URLForString<R = unknown, P0 = unknown>(__URLForString: P0): R;
      _insertionPointDisabled<R = boolean>(): R;
      _setInsertionPointDisabled<R = void, P0 = boolean>(__setInsertionPointDisabled: P0): R;
      keyPathsForValuesAffectingTouchBar<R = unknown>(): R;
  
  }
  }
}

declare const NSTextView: cocoa.NSTextView.CLASS;
